### ISSUE TITLE
Failed to build Ndless

### ISSUE THREAD

**Issue by MurrayFr** [ndless-nspire/Ndless#100]
Hi,
Sorry to trouble you...
I am on Ubuntu 16.04. The toolchain build was successful (Done! reported and ndless-sdk/bin contains nspire-g++ etc) but when I try to build Ndless and the sdk I fail on
```
nspire-gcc -O2 -funroll-loops -nostdlib -Wall -Werror -Wextra -ffunction-sections -fdata-sections -c usbd_set_idle.c
cc1: error: unrecognized command line option "-fuse-ld=gold"
```
I couldn't find anything very helpful or very recent on google that looks like this.
Also I find 
```
murray@murray-HP-ProBook-6550b:~/Ndless/ndless-sdk/samples/helloworld-sdl$ nspire-gcc
arm-elf-gcc: no input files
```
rather than invoking arm-none-eabi-gcc as in the tutorial.
Hope this is something stupid I did and it can be fixed easily - I only bought the nspire cx to try ndless...
my gcc version is :gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
if that helps.
Cheers
Murray

**Comment by Vogtinator** [comment]
You need to remove your `arm-elf-gcc`, it conflicts with the toolchain built by the SDK.

**Comment by MurrayFr** [comment]
Thanks - that got me most of the way - I was missing a dependency on libboost-program-options-dev which caused genzehn not to build, but with that fixed it all looks good.
Thanks for you quick response.
