### ISSUE TITLE
build_toolchain.sh fails

### ISSUE THREAD

**Issue by PotatoeMaster** [ndless-nspire/Ndless#101]
Recently, when I run `build_toolchain.sh`, the process fails and I get a ton of errors relating to `scm_t_port` not being used correctly. I output all of stderr to a file, and I pasted it [here](https://pastebin.com/GADSU1dY). The errors are mainly near the bottom, but there are quite a few errors near the top. I have all of the requirements installed on Arch Linux with everything completely updated.

**Comment by Legimet** [comment]
Try adding --with-guile=no to the GDB options.

**Comment by PotatoeMaster** [comment]
That seemed to fix it. Thanks
