### ISSUE TITLE
arm-none-eabi-ld: cannot find -lnspireio

### ISSUE THREAD

**Issue by PotatoeMaster** [ndless-nspire/Ndless#102]
I compiled the toolchain without GDB because I don't need a debugger right now, and when I try to compile one of the sample files, it gives this error among others. Here is an image showing the errors after running `make` and the fact that my path is set up correctly.

![arch_ndless_dev](https://user-images.githubusercontent.com/9669188/36347583-a62f37ae-140f-11e8-80ab-b86a4577687c.png)

**Comment by Vogtinator** [comment]
Did `make` in the `ndless-sdk` directory succeed?

Do you have the referenced files in `ndless/ndless-sdk/lib/`?

**Comment by PotatoeMaster** [comment]
`make` did not succeed saying that it could not find `<nspire/nspireio.h>`. In the lib folder, all I have is `libSDL.a`, `libSDL_gfx.a`, `libSDL_image.a`, `libsyscalls.a`, and two `README` files.

**Comment by Vogtinator** [comment]
Did you run `git submodule init` and `git submodule update`?

**Comment by PotatoeMaster** [comment]
That fixed it. Thanks
