### ISSUE TITLE
Ndless install

### ISSUE THREAD

**Issue by HymenopusC** [ndless-nspire/Ndless#103]
I reboot my calculator a lot and whenever I do it, ndless uninstalls like usual, except when I reinstall by running the program, the first time I run it reboots and the second it works. Is this unusual?

**Comment by Vogtinator** [comment]
Not unusual as the success of the installation depends on a lot of factors, including how long the calculator is turned on. It's not intentional though, with some tuning it could be changed to work more reliably for your calculator, but less reliably for others.

**Comment by joaobalugas** [comment]
How i can intall ndless on a version 4.3.0?

**Comment by Vogtinator** [comment]
> How i can intall ndless on a version 4.3.0?

You can't - there is no installer for 4.3. Just upgrade to 4.4 or 4.5.
But that's a different topic - please open a separate issue for that.
