### ISSUE TITLE
Second installation problem

### ISSUE THREAD

**Issue by MilkDromeda99** [ndless-nspire/Ndless#104]
Hi, I have recently installed ndless on my inspire cx, it worked just fine the first time around but restarted the calculator and it doesn't seem to reinstall when I run the program one more time after resetting the calculator. An error briefly shows up saying that there were no resources found, it is displayed in blue and on the top left of the screen for less than a second.

It loads for a while and then opens a blank page

**Comment by Vogtinator** [comment]
Basically the same as https://github.com/ndless-nspire/Ndless/issues/103
