### ISSUE TITLE
Invert colors ASM 

### ISSUE THREAD

**Issue by phyllocrania** [ndless-nspire/Ndless#105]
How could I invert my nspire's screen colors, is there a program to do this?

**Comment by Vogtinator** [comment]
No, why would you do that?

There is a program which demos the nspire's thread functions (you'll have to add the syscalls for your OS manually) and rewrites the screen buffer on https://www.omnimaga.org/ti-nspire-projects/snow-21767/msg398134/#msg398134

**Comment by phyllocrania** [comment]
Oh and related to this, is there a way to change the nspire bar color with ndless

**Comment by Vogtinator** [comment]
Editing the themes.csv should do that, but I don't know whether/how that works on newer OSs.

**Comment by phyllocrania** [comment]
Is there a program to aid with that or where would I change it

**Comment by Legimet** [comment]
https://tiplanet.org/forum/archives_voir.php?id=6070

**Comment by phyllocrania** [comment]
That does look nice

**Comment by phyllocrania** [comment]
Sadly this does not work on my rev. AB

**Comment by Legimet** [comment]
There are some custom syscalls used in the program, so the syscalls will have 
to be updated for recent OS versions for it to work.
