### ISSUE TITLE
Ndless SDK

### ISSUE THREAD

**Issue by phyllocrania** [ndless-nspire/Ndless#106]
How should I install the ndless sdk, I am following the wiki and it is building with lots of lines of code but is there a GUI?

**Comment by Vogtinator** [comment]
The SDK is a toolchain, you can use whatever GUI you like.

**Comment by phyllocrania** [comment]
How should I install a GUI or use one (sorry I am new to ndless sdk)

**Comment by Vogtinator** [comment]
The ndless SDK is only useful to you if you know how to program in C or C++.
Your question indicates that that is probably not the case for you.

**Comment by phyllocrania** [comment]
I know some c++ (not terribly much but some) and I saw this : https://www.omnimaga.org/news/a-new-graphical-sdk-for-ndless/

Is something like that available

**Comment by Vogtinator** [comment]
Not anymore, the referenced editor (SciTE) isn't really that great for actual development.
You can use any C++ IDE you want as long as they support custom Makefiles.

**Comment by phyllocrania** [comment]
Does the Arduino IDE support makefiles (that is most of my C++ experience)

**Comment by Vogtinator** [comment]
Nope, the Arduino IDE is custom and weird.

**Comment by phyllocrania** [comment]
Which GUI would you recommend and how should I build the ndless sdk with it

**Comment by Vogtinator** [comment]
You don't build the Ndless SDK with it. You use the SDK with it to build programs.

Personally I use Qt Creator, but the simplest setup is to just use any text editor (like Notepad++) and run make manually.

**Comment by Vogtinator** [comment]
Anyway, this is IMO off-topic now (definitely not an issue/bug here) so I suggest to ask in one of the usual forums instead.

**Comment by phyllocrania** [comment]
Okay, I will try that
