### ISSUE TITLE
When trying to run build_toolchain.sh , I keep getting dependency errors from Git, and it does not run at all in Cygwin.

### ISSUE THREAD

**Issue by SqugSCX** [ndless-nspire/Ndless#109]
I am trying to recompile Ndless because I wanted to change the text color from bright green to a less noticeable light grey for aesthetics. But after following the provided steps, I tried to run the .sh file in Git, and I get errors, but when I run it with Cygwin, it just sits and does nothing at all... Did I do anything wrong?

**Comment by Vogtinator** [comment]
> I am trying to recompile Ndless because I wanted to change the text color from bright green to a less noticeable light grey for aesthetics.

I have my doubts... Anyway, this is about a build issue so that doesn't matter here.

>  But after following the provided steps, I tried to run the .sh file in Git, and I get errors, but when I run it with Cygwin, it just sits and does nothing at all... Did I do anything wrong?

Where does it sit?

**Comment by GitHubQuestionAsker** [comment]
Run setup and in the top left corner  where it says pending click full then search the dependencies you need and install them then run ./build_toolchain.sh and make sure your in the right directory.

**Comment by Vogtinator** [comment]
Closing due to missing response.
