### ISSUE TITLE
configure: error: /bin/sh ../binutils-2.28/config.sub und failed

### ISSUE THREAD

**Issue by GraxCode** [ndless-nspire/Ndless#110]
It fails at running build_toolchain.sh
https://pastebin.com/cq43v7vk

**Comment by Vogtinator** [comment]
That's trivial: Don't put the SDK into a folder with spaces in it, apparently `configure` does not like that.

**Comment by deadmeatpt** [comment]
Vogtinator, I would like to add that when I tried using Cygwin, I use the 64-bit version, and configure also didn't like it somehow, 32-bit one was fine. But yes, he has spaces in the directory.

**Comment by GraxCode** [comment]
I've put it in a folder without spaces, but it still fails: https://pastebin.com/T01iM9Hx

**Comment by Vogtinator** [comment]
`/cygdrive/c/ndless/Ndless/ndless-sdk/toolchain/binutils-2.28/missing: Zeile 81: makeinfo: Kommando nicht gefunden.` - So install makeinfo?

**Comment by deadmeatpt** [comment]
The correct package is texinfo, makeinfo is a command from it. GraxCode, type "sudo apt-get install texinfo"

**Comment by GraxCode** [comment]
after installing many packages i got it to work, now i'm stuck at make, https://pastebin.com/URRT3AnA

**Comment by Vogtinator** [comment]
> The correct package is texinfo, makeinfo is a command from it. GraxCode, type "sudo apt-get install texinfo"

`apt-get` in cygwin?

> after installing many packages i got it to work, now i'm stuck at make, https://pastebin.com/URRT3AnA

Apparently git/cygwin/windows still doesn't handle symlinks correctly. Workaround that with
`rm ndless-sdk/tools/genzehn/zehn.h; cp ndless-sdk/include/zehn.h ndless-sdk/tools/genzehn/`

**Comment by deadmeatpt** [comment]
> apt-get in cygwin?
Good point, it's been a while since I used it.

**Comment by deadmeatpt** [comment]
> apt-get in cygwin?

Good point. It's been a while since I used cygwin

**Comment by GraxCode** [comment]
utils.c:1:1: Fehler: expected identifier or »(« before ».« token
 ../resources/utils.c
 ^
make[3]: *** [Makefile:16: utils.o] Fehler 1

What do i have to do with that file?

**Comment by Vogtinator** [comment]
The same, delete it and replace it with a copy.

You can also just run `make` in the `ndless-sdk` folder to skip building ndless itself.

**Comment by GraxCode** [comment]
Had to install many things and it took vwry long but finally i got it working on windows, maybe it would be easier without this compiling mess
