### ISSUE TITLE
arm-none-eabi-g++: Command not found when building the Ndless SDK

### ISSUE THREAD

**Issue by GitHubQuestionAsker** [ndless-nspire/Ndless#115]
make -C ndless-sdk
make[1]: Entering directory '/home/littl/Ndless/ndless-sdk'
make -C libsyscalls
make[2]: Entering directory '/home/littl/Ndless/ndless-sdk/libsyscalls'
arm-none-eabi-g++ -mcpu=arm926ej-s -std=c++11 -nostdlib -O3 -fPIE -fno-exceptions -fno-rtti -mlong-calls -Wall -Werror -I ../include/ -I ../thirdparty/nspire-io/include/ -D_TINSPIRE -ffunction-sections -fdata-sections -c stubs.cpp -o stubs.o
**make[2]: arm-none-eabi-g++: Command not found**
make[2]: *** [Makefile:18: stubs.o] Error 127
make[2]: Leaving directory '/home/littl/Ndless/ndless-sdk/libsyscalls'
make[1]: *** [Makefile:14: build-libsyscalls] Error 2
make[1]: Leaving directory '/home/littl/Ndless/ndless-sdk'
make: *** [Makefile:19: build-ndless-sdk] Error 2

Whenever I run ./build_toolchain.sh
echo $? the returned value is 0 (meaning it worked).

I don't know if I'm exporting the PATH properly.
C:/cygwin/home/littl/.bash_profile export PATH="C:/cygwin/home/littl/Ndless/ndless-sdk/toolchain/install/bin:C:/cygwin/home/littl/Ndless/ndless-sdk/bin:${PATH}"

I'm using Cygwin on Windows 10.
P.S. when I enter C:/cygwin/home/littl/Ndless/ndless-sdk/toolchain/instal/arm-none-eabi/bin/
I don't see arm-none-eabi-g++.exe

**Comment by Vogtinator** [comment]
You need to use the cygwin path forms, so in your case:

`export PATH="/home/littl/Ndless/ndless-sdk/toolchain/install/bin:/home/littl/Ndless/ndless-sdk/bin:${PATH}"`

**Comment by GitHubQuestionAsker** [comment]
Thank you so much!
