### ISSUE TITLE
memalign / posix_memalign missing 

### ISSUE THREAD

**Issue by yobson** [ndless-nspire/Ndless#117]
Hello!

I'm trying to get haskell to work on Ndless and am using the jhc compiler. This compiler compiles first to plain C, then uses GCC to cross compile. Sadly the garbage collector uses either `_aligned_malloc` for `__WIN32__`, `memalign` for `__ARM_EABI__`, `valloc` for OS X et al, or, if none else `posix_memalign`. None are avalable for Ndless

Not a big issue. It was just a mad idea trying to get this to work, but it's the one thing getting in the way!

Thanks

James

**Comment by Vogtinator** [comment]
libsyscalls' malloc already enforces 8 byte alignment, so you can just implement your own `posix_memalign` by ignoring the alignment.

**Comment by yobson** [comment]
You legend! I'll give it a go
