### ISSUE TITLE
"Make" Command on Top-Level Directory of Repository Fails

### ISSUE THREAD

**Issue by redjohn360** [ndless-nspire/Ndless#118]
When I try to run 'make' make I just get this error message and I can't figure out what it is.

_~/Ndless $ make
make -C ndless-sdk
make[1]: Verzeichnis „/home/oem/Ndless/ndless-sdk“ wird betreten
make -C libsyscalls
make[2]: Verzeichnis „/home/oem/Ndless/ndless-sdk/libsyscalls“ wird betreten
arm-none-eabi-gcc -mcpu=arm926ej-s -std=c11 -nostdlib -O3 -fPIE -mlong-calls -Wall -Werror -I ../include/ -I ../thirdparty/nspire-io/include/ -D_TINSPIRE -ffunction-sections -fdata-sections -c realpath.c -o realpath.o
realpath.c: In function 'realpath1':
realpath.c:50:12: error: 'PATH_MAX' undeclared (first use in this function)
  char left[PATH_MAX], next_token[PATH_MAX];
            ^
realpath.c:50:12: note: each undeclared identifier is reported only once for each function it appears in
realpath.c:50:23: error: unused variable 'next_token' [-Werror=unused-variable]
  char left[PATH_MAX], next_token[PATH_MAX];
                       ^
realpath.c:50:7: error: unused variable 'left' [-Werror=unused-variable]
  char left[PATH_MAX], next_token[PATH_MAX];
       ^
realpath.c: In function 'realpath':
realpath.c:159:25: error: 'PATH_MAX' undeclared (first use in this function)
   m = resolved = malloc(PATH_MAX);
                         ^
cc1: all warnings being treated as errors
Makefile:21: die Regel für Ziel „realpath.o“ scheiterte
make[2]: *** [realpath.o] Fehler 1
make[2]: Verzeichnis „/home/oem/Ndless/ndless-sdk/libsyscalls“ wird verlassen
Makefile:14: die Regel für Ziel „build-libsyscalls“ scheiterte
make[1]: *** [build-libsyscalls] Fehler 2
make[1]: Verzeichnis „/home/oem/Ndless/ndless-sdk“ wird verlassen
Makefile:19: die Regel für Ziel „build-ndless-sdk“ scheiterte
make: *** [build-ndless-sdk] Fehler 2_

**Comment by redjohn360** [comment]
Thank you for your fast answer.
I ecexuted the build_toolchain.sh Yesterday, so the build should be recent.

syslimits.h contains:

/*
 * Copyright (c) 1988, 1993
 *	The Regents of the University of California.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *	This product includes software developed by the University of
 *	California, Berkeley and its contributors.
 * 4. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 *	@(#)syslimits.h	8.1 (Berkeley) 6/2/93
 * $FreeBSD: src/sys/sys/syslimits.h,v 1.10 2001/06/18 20:24:54 wollman Exp $
 */

#ifndef _SYS_SYSLIMITS_H_
#define _SYS_SYSLIMITS_H_

#define	ARG_MAX			65536	/* max bytes for an exec function */
#ifndef CHILD_MAX
#define	CHILD_MAX		   40	/* max simultaneous processes */
#endif
#define	LINK_MAX		32767	/* max file link count */
#define	MAX_CANON		  255	/* max bytes in term canon input line */
#define	MAX_INPUT		  255	/* max bytes in terminal input */
#define	NAME_MAX		  255	/* max bytes in a file name */
#define	NGROUPS_MAX		   16	/* max supplemental group id's */
#ifndef OPEN_MAX
#define	OPEN_MAX		   64	/* max open files per process */
#endif
#define	PATH_MAX		 1024	/* max bytes in pathname */
#define	PIPE_BUF		  512	/* max bytes for atomic pipe writes */
#define	IOV_MAX			 1024	/* max elements in i/o vector */

#define	BC_BASE_MAX		   99	/* max ibase/obase values in bc(1) */
#define	BC_DIM_MAX		 2048	/* max array elements in bc(1) */
#define	BC_SCALE_MAX		   99	/* max scale value in bc(1) */
#define	BC_STRING_MAX		 1000	/* max const string length in bc(1) */
#define	COLL_WEIGHTS_MAX	    0	/* max weights for order keyword */
#define	EXPR_NEST_MAX		   32	/* max expressions nested in expr(1) */
#define	LINE_MAX		 2048	/* max bytes in an input line */
#define	RE_DUP_MAX		  255	/* max RE's in interval notation */

#endif

**Comment by Vogtinator** [comment]
Hm, does it work if you add `#include <sys/syslimits.h>` to realpath.c (just above the `sys/params.h` include)?

**Comment by redjohn360** [comment]
Ok thank you very much, That seems to work now. But now I'm getting this error:

stdlib.cpp:15:20: fatal error: typeinfo: No such file or directory
 #include <typeinfo>

**Comment by Vogtinator** [comment]
That means something is really wrong with your toolchain. Are you sure that `arm-none-eabi-gcc` invokes the correct compiler?

**Comment by redjohn360** [comment]
The only thing called 'arm-none-eabi-gcc' is a shortcut in 'bin-docker'. Could you specify where this folder should exist?

**Comment by Vogtinator** [comment]
`arm-none-eabi-gcc` is the name of the compiler executable generated by `build_toolchain.sh`. Run `which arm-none-eabi-gcc` to make sure that it points to the right path.

**Comment by redjohn360** [comment]
This gives me the path '/usr/bin/arm-none-eabi-gcc' is that right?

**Comment by Vogtinator** [comment]
No, that means you have $PATH not set correctly.

You have to add the ndless-sdk paths before everything else.

**Comment by Vogtinator** [comment]
As long as $PATH is not set correctly, it won't work. Which distro you use does not matter.

**Comment by redjohn360** [comment]
My $PATH should be set. When I `echo $PATH` this is the Output: `/home/luca/bin:/home/luca/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/luca/Ndless/ndless-sdk/toolchain/install/bin:/home/luca/Ndless/ndless-sdk/bin:/snap/bin`. Isn't that right?

**Comment by Vogtinator** [comment]
Try `/home/luca/Ndless/ndless-sdk/toolchain/install/bin:/home/luca/Ndless/ndless-sdk/bin:/home/luca/bin:/home/luca/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

**Comment by redjohn360** [comment]
Thank you that seems to work. I'm really sorry to bother you again, but I'm getting this error from `make`: `genzehn.cpp:8:37: fatal error: boost/program_options.hpp: Datei oder Verzeichnis nicht gefunden
compilation terminated.
genzehn.cpp:8:37: fatal error: boost/program_options.hpp: Datei oder Verzeichnis nicht gefunden
compilation terminated.`. Is it bad or is that normal when nothing is compiled?

**Comment by Vogtinator** [comment]
That means you're missing boost headers on your system. You need them to compile anything.

**Comment by redjohn360** [comment]
Ok that worked. Thank you very much.

**Comment by Mudkip909** [comment]
Just commenting here for anyone who might come here in the future, don't put the C:/cygwin64/ in your path. It should begin with /home

I learned this the hard way.
