### ISSUE TITLE
Repeated searching for ndless.cfg is extremely slow if you have a lot of documents

### ISSUE THREAD

**Issue by pbfy0** [ndless-nspire/Ndless#120]
`cfg_locate_cfg_file` means that to open a document with an association, ndless has to (very slowly) trawl through the entire filesystem. This adds a delay of 10-15 seconds on my calculator with a pretty full internal filesystem. I'm not clear on why it has to search the entire filesystem for a file that's supposed to be in a specific place. If it's for compatibility with Hide Manager, maybe there should be an API for changing the `ndless` folder location. At the minimum, can we cache the location after finding it the first time? I'm willing to implement any of these changes, but I want to understand why it's the way it is now before I start changing things.

**Comment by Vogtinator** [comment]
I'm not sure either. I'd say that always checking for `get_documents_dir()/ndless/ndless.cfg` is ok.

**Comment by parrotgeek1** [comment]
You just fixed this with the last commit I think

**Comment by Vogtinator** [comment]
Indeed.
