### ISSUE TITLE
Startup folder not working in press to test mode

### ISSUE THREAD

**Issue by FrostyPenguin** [ndless-nspire/Ndless#122]
I recently managed to install [ControlX](https://tiplanet.org/forum/viewtopic.php?t=18920&p=206415) on my calculator. It now automatically patches the OS so that I have ndless installed after rebooting. Surprisingly this works in Press-To-Test mode as well. The only problem is that it ignores the `startup` folder and its contents (not loading simple patches at boot).

**Comment by Vogtinator** [comment]
That is intentional.

**Comment by FrostyPenguin** [comment]
> That is intentional.

Does `intentional` mean intended by Texas Instruments or by the ndless developers?
I kinda get the point of not allowing anybody to completely disable TI's exam mode though, as this would probably result in schools banning the calculator.

**Comment by Vogtinator** [comment]
> Does intentional mean intended by Texas Instruments or by the ndless developers?
I kinda get the point of not allowing anybody to completely disable TI's exam mode though, as this would probably result in schools banning the calculator.

By ndless developers. It would require extra code to get this to work. As it would only benefit cheating, it was never implemented that way.
