### ISSUE TITLE
ndless_resouces Won't Run

### ISSUE THREAD

**Issue by GammaVoid** [ndless-nspire/Ndless#126]
As the title says, when I try to uninstall ndless using ndless_resources, the file won't run and ndless is always installed. Im on a CX P-0315U and used nBoot + ControlX to install the CAS software, I don't know if this is the conflict or not.

**Comment by Vogtinator** [comment]
With ControlX, ndless can't be uninstalled.

All ndless_resources does when uninstalling is a reboot, which has no effect with controlx.
