### ISSUE TITLE
Generated binary is invalid ?

### ISSUE THREAD

**Issue by gameblabla** [ndless-nspire/Ndless#127]
So i attempted to port Quake 2 to the Ti Nspire here
https://github.com/gameblabla/quake2_nsp

It does compile, generating a .tns but when you attempt to run it, it complains as if the file was not an executable, even after running Ndless after. (?)
Running anything else still work though. 
What could cause this, maybe it's due to the use of floating point ?
Here's the tns file for tests.
[quake2.zip](https://github.com/ndless-nspire/Ndless/files/2128634/quake2.zip)

**Comment by Vogtinator** [comment]
The file indicates that it needs 24MiB of RAM for program and data - that's more than can be allocated (contiguously) on a calc.

**Comment by Vogtinator** [comment]
Removing the use of `QARY` in `src/common/shared/rand.c`  makes it build, but the executable crashes instantly.

**Comment by gameblabla** [comment]
Indeed, i could confirm that, now the binary works (before crashing horribly, presumably due to memory constraints ?).
The crash is unrelated to the use of QARY btw and unfortunately i found more issues with the code.
Thanks for debugging it though, i guess this could be documented hackspire. You can close the issue
