### ISSUE TITLE
Building and installing toolchain

### ISSUE THREAD

**Issue by tigre200** [ndless-nspire/Ndless#128]
I am using Xubuntu.
In the script I changed: erased in OPTIONS_GDB the flag --with-python, and commented line 51.
Can someone help me?
When I run the script, it fails giving the following lines:

/bin/bash: line 1: 28490 Killed                  build/genautomata ../../gcc-7.3.0/gcc/common.md ../../gcc-7.3.0/gcc/config/arm/arm.md insn-conditions.md > tmp-automata.c
Makefile:2278: recipe for target 's-automata' failed
make[1]: *** [s-automata] Error 137
make[1]: *** Waiting for unfinished jobs....
/bin/bash ../../gcc-7.3.0/gcc/../move-if-change tmp-attrtab.c    insn-attrtab.c
/bin/bash ../../gcc-7.3.0/gcc/../move-if-change tmp-dfatab.c     insn-dfatab.c
/bin/bash ../../gcc-7.3.0/gcc/../move-if-change tmp-latencytab.c insn-latencytab.c
echo timestamp > s-attrtab
rm gcc.pod
make[1]: Leaving directory '/home/hugo/Documents/Ndless/ndless-sdk/toolchain/build/gcc'
Makefile:4221: recipe for target 'all-gcc' failed
make: *** [all-gcc] Error 2

I then installed the python package and redid everything from scratch and got this now:

g++ -fno-PIE -c   -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -I. -I. -I../../gcc-7.3.0/gcc -I../../gcc-7.3.0/gcc/. -I../../gcc-7.3.0/gcc/../include -I../../gcc-7.3.0/gcc/../libcpp/include  -I../../gcc-7.3.0/gcc/../libdecnumber -I../../gcc-7.3.0/gcc/../libdecnumber/dpd -I../libdecnumber -I../../gcc-7.3.0/gcc/../libbacktrace   -o insn-extract.o -MT insn-extract.o -MMD -MP -MF ./.deps/insn-extract.TPo insn-extract.c
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Makefile:1099: recipe for target 'insn-emit.o' failed
make[1]: *** [insn-emit.o] Error 4
make[1]: *** Waiting for unfinished jobs....
rm gcc.pod
make[1]: Leaving directory '/home/hugo/Documents/Ndless/ndless-sdk/toolchain/build/gcc'
Makefile:4221: recipe for target 'all-gcc' failed
make: *** [all-gcc] Error 2

**Comment by Vogtinator** [comment]
Try to set `PARALLEL="-j1"` in the script and try again.

If it worked, you most likely ran out of memory. If it still fails, please file a bug report at Xubuntu, it ships a broken compiler.

**Comment by tigre200** [comment]
I did what you suggested, and there seems to be more progress. But now I get a new error, that seems to be related to running out of memory as you suggested. I'm running Xubuntu on Virtual Box, does this mean I need to increase the memory of the virtual machine?
Here is the new error:

mkdir -p ./arm-none-eabi/bits/stdtr1c++.h.gch
/home/hugo/Documents/Ndless/ndless-sdk/toolchain/build/./gcc/xgcc -shared-libgcc -B/home/hugo/Documents/Ndless/ndless-sdk/toolchain/build/./gcc -nostdinc++ -L/home/hugo/Documents/Ndless/ndless-sdk/toolchain/build/arm-none-eabi/libstdc++-v3/src -L/home/hugo/Documents/Ndless/ndless-sdk/toolchain/build/arm-none-eabi/libstdc++-v3/src/.libs -L/home/hugo/Documents/Ndless/ndless-sdk/toolchain/build/arm-none-eabi/libstdc++-v3/libsupc++/.libs -B/home/hugo/Documents/Ndless/ndless-sdk/toolchain/install/arm-none-eabi/bin/ -B/home/hugo/Documents/Ndless/ndless-sdk/toolchain/install/arm-none-eabi/lib/ -isystem /home/hugo/Documents/Ndless/ndless-sdk/toolchain/install/arm-none-eabi/include -isystem /home/hugo/Documents/Ndless/ndless-sdk/toolchain/install/arm-none-eabi/sys-include    -x c++-header -nostdinc++ -DHAVE_RENAME -DMALLOC_PROVIDED -DABORT_PROVIDED -DNO_FORK -mcpu=arm926ej-s -ffunction-sections -Ofast -funroll-loops  -I/home/hugo/Documents/Ndless/ndless-sdk/toolchain/build/arm-none-eabi/libstdc++-v3/include/arm-none-eabi -I/home/hugo/Documents/Ndless/ndless-sdk/toolchain/build/arm-none-eabi/libstdc++-v3/include -I/home/hugo/Documents/Ndless/ndless-sdk/toolchain/gcc-7.3.0/libstdc++-v3/libsupc++  -O2 -g /home/hugo/Documents/Ndless/ndless-sdk/toolchain/gcc-7.3.0/libstdc++-v3/include/precompiled/stdtr1c++.h -o arm-none-eabi/bits/stdtr1c++.h.gch/O2g.gch
In file included from /home/hugo/Documents/Ndless/ndless-sdk/toolchain/gcc-7.3.0/libstdc++-v3/include/precompiled/stdtr1c++.h:53:0:
/home/hugo/Documents/Ndless/ndless-sdk/toolchain/build/arm-none-eabi/libstdc++-v3/include/tr1/utility:106:1: fatal error: can’t write PCH file: No space left on device
 }
 ^
compilation terminated.
Makefile:1746: recipe for target 'arm-none-eabi/bits/stdtr1c++.h.gch/O2g.gch' failed
make[4]: *** [arm-none-eabi/bits/stdtr1c++.h.gch/O2g.gch] Error 1
make[4]: Leaving directory '/home/hugo/Documents/Ndless/ndless-sdk/toolchain/build/arm-none-eabi/libstdc++-v3/include'
Makefile:510: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/hugo/Documents/Ndless/ndless-sdk/toolchain/build/arm-none-eabi/libstdc++-v3'
Makefile:417: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/hugo/Documents/Ndless/ndless-sdk/toolchain/build/arm-none-eabi/libstdc++-v3'
Makefile:10376: recipe for target 'all-target-libstdc++-v3' failed
make[1]: *** [all-target-libstdc++-v3] Error 2
make[1]: Leaving directory '/home/hugo/Documents/Ndless/ndless-sdk/toolchain/build'
Makefile:889: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Vogtinator** [comment]
You're out of disk space.

**Comment by tigre200** [comment]
The File Manager says I have 5.1 MB free. What do you suggest increasing it to?

**Comment by Vogtinator** [comment]
You need at least 3 GiB more.

**Comment by nunopenim** [comment]
Xubuntu works fine lol, I have it with ndless-sdk and it compiled fine

**Comment by tigre200** [comment]
Not yet. When I have time, I'll increase the virtual machine's disk space, as Vogtinator suggested, and try again.

**Comment by tigre200** [comment]
I increased the disk space on the virtual machine, but I still get out of memory errors. I think it is because the disk space is set to be dynamically allocated (I set it to 16GB, but the machine says only 10GB), but the script doesn't trigger an increase of  the allocated disk space as, say, installing a package would.
Do you know how to solve this?

**Comment by nunopenim** [comment]
You need to go to gparted and expand partition :P Not sure if gnome disk tool does this, but gparted is better
