### ISSUE TITLE
how can i do to install CAS  in my N-0118AC...?

### ISSUE THREAD

**Issue by CHARLY-ANGEL** [ndless-nspire/Ndless#129]
I have got  SN:3769014152  / N-0118AC / TI-NSPIRE CX  running 4.5.0.1180...doesn't have CAS....how can i made to upgrade to CAS version , ive got some  experience with jailbreaks process but this is my son calculator...i dont get any help or videos from internet...it seems is a very delicate thing.....somebody help me please...!!!!!! .....regards.!

**Comment by Vogtinator** [comment]
> but this is my son calculator

Your son is a calculator? My condolences...

Putting CAS software on a non-CAS calc is illegal, you don't have a license for the software. So we won't help you doing that.
