### ISSUE TITLE
Documentation for building the SDK for languages other than C/C++/asm

### ISSUE THREAD

**Issue by coolreader18** [ndless-nspire/Ndless#132]
In [this](https://www.omnimaga.org/ti-basic-language/what-does-ndless-3-6-do-exactly-how-to-code/msg396123/#msg396123) thread on omnimaga, @Vogtinator mentions that you can build go, java, and llvm-compatible languages with the GNU toolchain. I think I'll probably be able to figure out how to enable those languages for gcc, but for others who want to do so I think it'd be good to have documentation for it.

**Comment by Vogtinator** [comment]
That's true - but I never actually tested it so I didn't write any documentation.

Getting go to run might be as easy as listing it in build_toolchain.sh, but as java support got removed from GCC, that's no longer possible.

With llvm it should be relatively straightforward: Just change the Makefile of a program to use whatever other compiler to build a statically linked ELF executable for arm926ej-s with the correct lib and include paths.

**Comment by Vogtinator** [comment]
It needs to either use the `nspire-gcc` wrapper or pass the options `-mcpu=arm926ej-s -D _TINSPIRE -fuse-ld=gold`.

**Comment by coolreader18** [comment]
I've been trying a few things, but [here's](https://gist.github.com/coolreader18/9be7e46cfa9179cbd23b0b239aae508a) the last bit of the output for `export`ing `CFLAGS_FOR_TARGET="-mcpu=arm926ej-s -D _TINSPIRE -fuse-ld=gold"` between binutils and gcc step 1. The error occurs while building gcc step 2, and I couldn't really figure out what was wrong.

**Comment by coolreader18** [comment]
Alright, I'll try that. Thanks for all your help!
