### ISSUE TITLE
Something wrong with gpsp launcher

### ISSUE THREAD

**Issue by ruhanvohra** [ndless-nspire/Ndless#137]
Okay so on sunday I downloaded it and it worked fine. today when I clicked on gpsp launcher it said that it couldn't recognize my bios which were inside my file entitled "gba emulator" (same file s gpsp launcher) I don't know why this is happening, could someone please help me?

**Comment by Vogtinator** [comment]
What's the error message?

**Comment by Vogtinator** [comment]
No response.

**Comment by prady176** [comment]
My error message when I open gpSP launcher is this:
****Sorry, but gpSP requires a Gameboy Advance BIOS image to run correctly. Make sure to get an authentic one, it'll be exactly 16384 bytes large and should have the following value:
a860e8c0b6d573d191e4ec7db1b1e4f6**
**When you do get it name it gba_bios.bin.tns and put it in the same directory as gpSP.
Press any button to exit.**
But I have a BIOS of the exact same name and everything is correct.

**Comment by Vogtinator** [comment]
It's probably not the file gpSP expects. Make sure the hash matches.
