### ISSUE TITLE
Regarding the `sleep` function in libndls

### ISSUE THREAD

**Issue by coolreader18** [ndless-nspire/Ndless#142]
The sleep function in `ndless-sdk/libndls/sleep.c` currently maps to the POSIX `sleep` function defined in `unistd.h`, however the standard defines that function to accept an argument in seconds, and the one in `sleep.c` takes an argument in milliseconds. I understand that that would be a breaking change, but it would be more standards compliant for that to be a different function, perhaps something like `msleep`, while `sleep` would just be `msleep(seconds * 1000)`.

**Comment by Vogtinator** [comment]
I agree - can you open a PR and rename `sleep` to `msleep`? By not providing `sleep` anything relying on the broken behaviour would fail to build.
