### ISSUE TITLE
SDK fails on Fedora Linux

### ISSUE THREAD

**Issue by leyei** [ndless-nspire/Ndless#144]
Can anyone help?

I have successfully ran the SDK's build_toolchain.sh but when I need to Build Ndless and the SDK, in the top level of the repository using make command, I get an errror:

`# make
make -C ndless-sdk
make[1]: Entering directory '/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk'
make -C libsyscalls
make[2]: Entering directory '/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/libsyscalls'
arm-none-eabi-g++ -mcpu=arm926ej-s -std=c++11 -nostdlib -O3 -fPIE -fno-exceptions -fno-rtti -mlong-calls -Wall -Werror -I ../include/ -I ../thirdparty/nspire-io/include/ -D_TINSPIRE -ffunction-sections -fdata-sections -c stubs.cpp -o stubs.o
make[2]: arm-none-eabi-g++: Command not found
make[2]: *** [Makefile:18: stubs.o] Error 127
make[2]: Leaving directory '/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/libsyscalls'
make[1]: *** [Makefile:14: build-libsyscalls] Error 2
make[1]: Leaving directory '/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk'
make: *** [Makefile:19: build-ndless-sdk] Error 2
`

I have PATH environment correctly added to .bash_profile and the below shows no error
`$ ./build_toolchain.sh
Building and installing to '/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/install'...
Building Binutils...
Building GCC (step 1)...
Building Newlib...
Building GCC (step 2)...
Building GDB...
Done!
Don't forget to add '/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/install/bin' to your $PATH along with /home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/../bin.
` 

Path with the following:
`export PATH="/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/install/bin:/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/../bin:${PATH}"`

**Comment by Vogtinator** [comment]
If that's your `$PATH`, it should work correctly.

Did you restart bash after editing `.bash_profile`?

**Comment by leyei** [comment]
Yes I did and no changes

**Comment by Vogtinator** [comment]
Does `/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/install/bin/arm-none-eabi-g++` exist?

**Comment by leyei** [comment]
Yes it does (5.3 MB) @Vogtinator

**Comment by Vogtinator** [comment]
Make sure you're running `make` in the same environment then.

https://github.com/ndless-nspire/Ndless/issues/144#issue-374106667 shows a `#` as the prompt, which .means you're running it as root. You must not do that.

**Comment by leyei** [comment]
This is the output @Vogtinator 

```
File: /home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/install/bin/arm-none-eabi-g++
  Size: 5329480   	Blocks: 10416      IO Block: 4096   regular file
Device: fd02h/64770d	Inode: 6317901     Links: 2
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/      xi)   Gid: ( 1000/      xi)
Context: unconfined_u:object_r:user_home_t:s0
Access: 2018-10-25 21:55:48.460348920 +0300
Modify: 2018-10-25 21:55:48.467348933 +0300
Change: 2018-10-25 21:55:48.474348946 +0300
 Birth: -
stat: cannot stat 'echo': No such file or directory
stat: cannot stat '/usr/lib64/qt-3.3/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin:/home/xi/.local/bin:/home/xi/bin': No such file or directory
stat: cannot stat 'which': No such file or directory
stat: cannot stat 'arm-none-eabi-g++': No such file or directory
stat: cannot stat 'arm-none-eabi-g++': No such file or directory
stat: cannot stat 'make': No such file or directory

```

**Comment by Vogtinator** [comment]
Those were multiple commands, you ran it as a single command.

It appears like you're using SELinux, you might try without.

**Comment by leyei** [comment]
Any idea how to do that? @Vogtinator

**Comment by Vogtinator** [comment]
Run the commands first to ensure it's indeed SELinux.

**Comment by leyei** [comment]
ok i did and this is the result
`$ arm-none-eabi-g++
bash: arm-none-eabi-g++: command not found...
Install package 'arm-none-eabi-gcc-cs-c++' to provide command 'arm-none-eabi-g++'? [N/y] y


 * Waiting in queue... 
The following packages have to be installed:
 arm-none-eabi-binutils-cs-1:2.30-1.fc28.x86_64	GNU Binutils for cross-compilation for arm-none-eabi target
 arm-none-eabi-gcc-cs-1:7.1.0-5.fc27.x86_64	GNU GCC for cross-compilation for arm-none-eabi target
 arm-none-eabi-gcc-cs-c++-1:7.1.0-5.fc27.x86_64	Cross Compiling GNU GCC targeted at arm-none-eabi
Proceed with changes? [N/y] y


 * Waiting in queue... 
 * Waiting for authentication... 
 * Waiting in queue... 
 * Downloading packages... 
 * Requesting data... 
 * Testing changes... 
 * Installing packages... 
arm-none-eabi-g++: fatal error: no input files
compilation terminated.
`

**Comment by Vogtinator** [comment]
You ran the commands in the wrong order.

Also, now you need to remove the packages you installed again.

**Comment by leyei** [comment]
I think i ran it in the right order.
What packages exactly I need to remove? @Vogtinator

**Comment by Vogtinator** [comment]
> I think i ran it in the right order.

I don't think so, the `echo` is missing completely.

> What packages exactly I need to remove? @Vogtinator

The ones you agreed to installing:

```
arm-none-eabi-binutils-cs-1:2.30-1.fc28.x86_64	GNU Binutils for cross-compilation for arm-none-eabi target
arm-none-eabi-gcc-cs-1:7.1.0-5.fc27.x86_64	GNU GCC for cross-compilation for arm-none-eabi target
arm-none-eabi-gcc-cs-c++-1:7.1.0-5.fc27.x86_64	Cross Compiling GNU GCC targeted at arm-none-eabi``

**Comment by leyei** [comment]
ok thanks @Vogtinator  packages removed

**Comment by leyei** [comment]
@Vogtinator Wish you could help. Trying to do this now on WSL-Ubuntu since it doesnt seem to work on Fedora no matter how many times I tried to do it over again.

This is what I get after running make:

```
$ make
make -C ndless-sdk
make[1]: Entering directory '/home/ubuntu/toolz/Ndless/ndless-sdk'
make -C libsyscalls
make[2]: Entering directory '/home/ubuntu/toolz/Ndless/ndless-sdk/libsyscalls'
arm-none-eabi-gcc -mcpu=arm926ej-s -std=c11 -nostdlib -O3 -fPIE -mlong-calls -Wall -Werror -I ../include/ -I ../thirdparty/nspire-io/include/ -D_TINSPIRE -ffunction-sections -fdata-sections -c realpath.c -o realpath.o
realpath.c: In function 'realpath1':
realpath.c:50:12: error: 'PATH_MAX' undeclared (first use in this function)
  char left[PATH_MAX], next_token[PATH_MAX];
            ^~~~~~~~
realpath.c:50:12: note: each undeclared identifier is reported only once for each function it appears in
realpath.c:50:23: error: unused variable 'next_token' [-Werror=unused-variable]
  char left[PATH_MAX], next_token[PATH_MAX];
                       ^~~~~~~~~~
realpath.c:50:7: error: unused variable 'left' [-Werror=unused-variable]
  char left[PATH_MAX], next_token[PATH_MAX];
       ^~~~
realpath.c: In function 'realpath':
realpath.c:159:25: error: 'PATH_MAX' undeclared (first use in this function)
   m = resolved = malloc(PATH_MAX);
                         ^~~~~~~~
cc1: all warnings being treated as errors
Makefile:21: recipe for target 'realpath.o' failed
make[2]: *** [realpath.o] Error 1
make[2]: Leaving directory '/home/ubuntu/toolz/Ndless/ndless-sdk/libsyscalls'
Makefile:14: recipe for target 'build-libsyscalls' failed
make[1]: *** [build-libsyscalls] Error 2
make[1]: Leaving directory '/home/ubuntu/toolz/Ndless/ndless-sdk'
Makefile:19: recipe for target 'build-ndless-sdk' failed
make: *** [build-ndless-sdk] Error 2
```

When I echo $path from the same shell, I get variables from the Windows machine. I havent seen any where online where I can add path ti WSL successfully. Can you help here?

**Comment by Vogtinator** [comment]
Run `which arm-none-eabi-gcc` and make sure it's pointing to the one built for Ndless.

**Comment by leyei** [comment]
Thank you for your help @Vogtinator 

I get this 

```
$ which arm-none-eabi-gcc
/usr/bin/arm-none-eabi-gcc
```

I need to find a way to set path with this WSL

**Comment by leyei** [comment]
Thank you @Vogtinator .

It didnt work so I am doing it again from scratch on Fedora because that is the only place I can get to build SDK's toolchain successfully now until
```
Done!
Don't forget to add '/home/xi/Ndless/ndless-sdk/toolchain/install/bin' to your $PATH along with /home/xi/Ndless/ndless-sdk/toolchain/../bin.
```

Now i added this
`export PATH="/home/xi/Ndless/ndless-sdk/toolchain/install/bin:/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/../bin:${PATH}"`
to the bash_profile file from /home and went back to issue [here](https://github.com/ndless-nspire/Ndless/issues/144#issuecomment-433313372)


So I followed your steps [here](https://github.com/ndless-nspire/Ndless/issues/144#issuecomment-433313680) and it want me to install those packages again. Please see the output:

```
Ndless]$ make
make -C ndless-sdk
make[1]: Entering directory '/home/xi/Ndless/ndless-sdk'
make -C libsyscalls
make[2]: Entering directory '/home/xi/Ndless/ndless-sdk/libsyscalls'
arm-none-eabi-g++ -mcpu=arm926ej-s -std=c++11 -nostdlib -O3 -fPIE -fno-exceptions -fno-rtti -mlong-calls -Wall -Werror -I ../include/ -I ../thirdparty/nspire-io/include/ -D_TINSPIRE -ffunction-sections -fdata-sections -c stubs.cpp -o stubs.o
make[2]: arm-none-eabi-g++: Command not found
make[2]: *** [Makefile:18: stubs.o] Error 127
make[2]: Leaving directory '/home/xi/Ndless/ndless-sdk/libsyscalls'
make[1]: *** [Makefile:14: build-libsyscalls] Error 2
make[1]: Leaving directory '/home/xi/Ndless/ndless-sdk'
make: *** [Makefile:19: build-ndless-sdk] Error 2
[xi@FedoraBeast Ndless]$ stat /home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/install/bin/arm-none-eabi-g++
stat: cannot stat '/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/install/bin/arm-none-eabi-g++': No such file or directory
[xi@FedoraBeast Ndless]$ echo $PATH
/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/install/bin:/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/../bin:/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/install/bin:/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/../bin:/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/install/bin:/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/../bin:/usr/lib64/qt-3.3/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin:/home/xi/.local/bin:/home/xi/bin
[xi@FedoraBeast Ndless]$ which arm-none-eabi-g++
/usr/bin/which: no arm-none-eabi-g++ in (/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/install/bin:/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/../bin:/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/install/bin:/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/../bin:/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/install/bin:/home/xi/Downloads/Ndless-4.5/git/Ndless/ndless-sdk/toolchain/../bin:/usr/lib64/qt-3.3/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin:/home/xi/.local/bin:/home/xi/bin)
[xi@FedoraBeast Ndless]$ arm-none-eabi-g++
bash: arm-none-eabi-g++: command not found...
Install package 'arm-none-eabi-gcc-cs-c++' to provide command 'arm-none-eabi-g++'? [N/y] y


 * Waiting in queue... 
The following packages have to be installed:
 arm-none-eabi-binutils-cs-1:2.30-1.fc28.x86_64	GNU Binutils for cross-compilation for arm-none-eabi target
 arm-none-eabi-gcc-cs-1:7.1.0-5.fc27.x86_64	GNU GCC for cross-compilation for arm-none-eabi target
 arm-none-eabi-gcc-cs-c++-1:7.1.0-5.fc27.x86_64	Cross Compiling GNU GCC targeted at arm-none-eabi
Proceed with changes? [N/y] 

```

**Comment by leyei** [comment]
Another update @Vogtinator :+1:  :)

With a fresh ubuntu live, I figured that working from the same shell (top level repo) doesn't show correct $PATH even though it was corrected assigned. With a new shell, I get the correct $PATH info. Then i attempted your steps but get fatal error when I run arm-non-eabi-g++ :(

What can I be doing wrong? Kindly help

```
echo $PATH
/home/ubuntu/Ndless/ndless-sdk/toolchain/install/bin:/home/ubuntu/Ndless/ndless-sdk/toolchain/../bin:/home/ubuntu/Ndless/ndless-sdk/toolchain/install/bin:/home/ubuntu/Ndless/ndless-sdk/toolchain/../bin:/home/ubuntu/Ndless/ndless-sdk/toolchain/install/bin:/home/ubuntu/Ndless/ndless-sdk/toolchain/../bin:/home/ubuntu/Ndless/ndless-sdk/toolchain/install/bin:/home/ubuntu/Ndless/ndless-sdk/toolchain/../bin:/home/ubuntu/Ndless/ndless-sdk/toolchain/install/bin:/home/ubuntu/Ndless/ndless-sdk/toolchain/../bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
ubuntu@ubuntu:~$ which arm-none-eabi-g++
/home/ubuntu/Ndless/ndless-sdk/toolchain/install/bin/arm-none-eabi-g++
ubuntu@ubuntu:~$ arm-none-eabi-g++
arm-none-eabi-g++: fatal error: no input files
compilation terminated.

```

**Comment by Vogtinator** [comment]
> With a new shell, I get the correct $PATH info. Then i attempted your steps but get fatal error when I run arm-non-eabi-g++ :(

That's normal, everything is fine.

**Comment by leyei** [comment]
thanks @Vogtinator :+1: 

But make still brings the same  error messages :?



$make
make -C ndless-sdk
make[1]: Entering directory '/home/xi/Ndless/ndless-sdk'
make -C libsyscalls
make[2]: Entering directory '/home/xi/Ndless/ndless-sdk/libsyscalls'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/xi/Ndless/ndless-sdk/libsyscalls'
make -C libndls
make[2]: Entering directory '/home/xi/Ndless/ndless-sdk/libndls'
nspire-gcc -O2 -funroll-loops -nostdlib -Wall -Werror -Wextra -ffunction-sections -fdata-sections -c usbd_set_idle.c
make[2]: nspire-gcc: Command not found
make[2]: *** [Makefile:18: usbd_set_idle.o] Error 127
make[2]: Leaving directory '/home/xi/Ndless/ndless-sdk/libndls'
make[1]: *** [Makefile:14: build-libndls] Error 2
make[1]: Leaving directory '/home/xi/Ndless/ndless-sdk'
make: *** [Makefile:19: build-ndless-sdk] Error 2
$

**Comment by leyei** [comment]
OK @Vogtinator  some magic happened! :dancer: 

Was trying on Fedora again... got the same error then closed the shell. Went back to top level directory and ran make and suddenly something happened....bunch of lines and then this last few lines:

```
genzehn.cpp:8:10: fatal error: boost/program_options.hpp: No such file or directory
 #include <boost/program_options.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
genzehn.cpp:8:10: fatal error: boost/program_options.hpp: No such file or directory
 #include <boost/program_options.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:4: ../../bin/genzehn] Error 1
make[3]: Leaving directory '/home/xi/Ndless/ndless-sdk/tools/genzehn'
make[2]: *** [Makefile:4: all] Error 1
make[2]: Leaving directory '/home/xi/Ndless/ndless-sdk/tools'
make[1]: *** [Makefile:14: build-tools] Error 2
make[1]: Leaving directory '/home/xi/Ndless/ndless-sdk'
make: *** [Makefile:19: build-ndless-sdk] Error 2

```

**Comment by Vogtinator** [comment]
> But make still brings the same error messages :? 

Those are different. nspire-gcc is in a different directory, make sure that both are in PATH.

> Was trying on Fedora again... got the same error then closed the shell. Went back to top level directory and ran make and suddenly something happened....bunch of lines and then this last few lines:

You're missing boost.

**Comment by leyei** [comment]
Wow! Thank you @Vogtinator I had boost installed and not boost-devel :+1: 

Now I get this:

```
mkdir -p zlib
cd zlib && CC=nspire-gcc CHOST=arm-none-eabi CFLAGS="-Os -fPIE -ffunction-sections -fdata-sections -DNO_GZIP -c" ../../../thirdparty/zlib/configure --static
Using arm-none-eabi-ar
Using arm-none-eabi-ranlib
Using arm-none-eabi-nm
Compiler error reporting is too harsh for ../../../thirdparty/zlib/configure (perhaps remove -Werror).
** ../../../thirdparty/zlib/configure aborting.
make[3]: *** [Makefile:21: zlib/Makefile] Error 1
make[3]: Leaving directory '/home/xi/Ndless/ndless-sdk/tools/zehn_loader'
make[2]: *** [Makefile:4: all] Error 1
make[2]: Leaving directory '/home/xi/Ndless/ndless-sdk/tools'
make[1]: *** [Makefile:14: build-tools] Error 2
make[1]: Leaving directory '/home/xi/Ndless/ndless-sdk'
make: *** [Makefile:19: build-ndless-sdk] Error 2

```

**Comment by Vogtinator** [comment]
Did you fix the nspire-gcc issue?

**Comment by leyei** [comment]
I added this to bash_profile

`export PATH="/home/xi/Ndless/ndless-sdk/bin:/home/xi/Ndless/ndless-sdk/bin:${PATH}"`

**Comment by Vogtinator** [comment]
Why `libndls`? The correct folder is `bin`.

**Comment by leyei** [comment]
I have bin there too and I get the last error output without the nspire-gcc so I thought I try that. @Vogtinator 


This is my PATH:
```
export PATH="/home/xi/Ndless/ndless-sdk/toolchain/install/bin:/home/xi/Ndless/ndless-sdk/toolchain/../bin:${PATH}"
export PATH="/home/xi/Ndless/ndless-sdk/bin:/home/xi/Ndless/ndless-sdk/bin:${PATH}" 
```

**Comment by leyei** [comment]
This is getting interesting @Vogtinator :D Now my errors are same as mentioned [here](https://github.com/ndless-nspire/Ndless/issues/55)

```
make[3]: Entering directory '/home/xi/Ndless/ndless-sdk/samples/freetype'
nspire-gcc -Wall -W -marm -Os -c freetype_demo.c
freetype_demo.c: In function ‘main’:
freetype_demo.c:98:40: error: ‘droid_DroidSans_ttf’ undeclared (first use in this function)
   error = FT_New_Memory_Face( library, droid_DroidSans_ttf, droid_DroidSans_ttf_len, 0, &face ); /* create face object */
                                        ^~~~~~~~~~~~~~~~~~~
freetype_demo.c:98:40: note: each undeclared identifier is reported only once for each function it appears in
freetype_demo.c:98:61: error: ‘droid_DroidSans_ttf_len’ undeclared (first use in this function)
   error = FT_New_Memory_Face( library, droid_DroidSans_ttf, droid_DroidSans_ttf_len, 0, &face ); /* create face object */
                                                             ^~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [Makefile:42: freetype_demo.o] Error 1
make[3]: Leaving directory '/home/xi/Ndless/ndless-sdk/samples/freetype'
make[2]: *** [Makefile:15: build-freetype] Error 2
make[2]: Leaving directory '/home/xi/Ndless/ndless-sdk/samples'
make[1]: *** [Makefile:14: build-samples] Error 2
make[1]: Leaving directory '/home/xi/Ndless/ndless-sdk'
make: *** [Makefile:19: build-ndless-sdk] Error 2

```

And yes, I have done make clean and make again... same error :/

**Comment by Vogtinator** [comment]
Looking better now. You don't have `xxd` installed.

That's only needed for the freetype sample though.

**Comment by leyei** [comment]
Yes I did `make clean` @Vogtinator . Unfortunately that file is empty :O

**Comment by Vogtinator** [comment]
It looks like `make clean` doesn't remove it. Delete it manually and run make again.

**Comment by leyei** [comment]
ok nice! @Vogtinator that seem to solve that but few errors still there

```
make[3]: Entering directory '/home/xi/Ndless/ndless/src/tools'
make -C EscapeInstaller
make[4]: Entering directory '/home/xi/Ndless/ndless/src/tools/EscapeInstaller'
gcc -W -Wall -std=c11 EscapeInstaller.c -o EscapeInst
make[4]: Leaving directory '/home/xi/Ndless/ndless/src/tools/EscapeInstaller'
make -C LuaBin
make[4]: Entering directory '/home/xi/Ndless/ndless/src/tools/LuaBin'
g++ -std=c++11    luabin.cpp   -o luabin
make[4]: Leaving directory '/home/xi/Ndless/ndless/src/tools/LuaBin'
make -C MakeLuaInst
make[4]: Entering directory '/home/xi/Ndless/ndless/src/tools/MakeLuaInst'
gcc -W -Wall MakeLuaInst.c -o MakeLuaInst
make[4]: Leaving directory '/home/xi/Ndless/ndless/src/tools/MakeLuaInst'
make -C MakeHotRebootPatches
make[4]: Entering directory '/home/xi/Ndless/ndless/src/tools/MakeHotRebootPatches'
gcc -W -Wall main.c -o MakeHotRebootPtch
make[4]: Leaving directory '/home/xi/Ndless/ndless/src/tools/MakeHotRebootPatches'
make -C MakeSyscalls
make[4]: Entering directory '/home/xi/Ndless/ndless/src/tools/MakeSyscalls'
php ./mkSyscalls.php "idc" "../../../../ndless-sdk/include/syscall-addrs.h"
/bin/sh: php: command not found
make[4]: *** [Makefile:9: ../../../../ndless-sdk/include/syscall-addrs.h] Error 127
make[4]: Leaving directory '/home/xi/Ndless/ndless/src/tools/MakeSyscalls'
make[3]: *** [Makefile:10: build-MakeSyscalls] Error 2
make[3]: Leaving directory '/home/xi/Ndless/ndless/src/tools'
make[2]: *** [Makefile:9: build-tools] Error 2
make[2]: Leaving directory '/home/xi/Ndless/ndless/src'
make[1]: *** [Makefile:9: build-src] Error 2
make[1]: Leaving directory '/home/xi/Ndless/ndless'
make: *** [Makefile:19: build-ndless] Error 2
$ 
```

**Comment by Vogtinator** [comment]
You need to install php.

**Comment by leyei** [comment]
OMG @Vogtinator ! :+1: Finally got to completely build Ndless and the SDK. :100:  I have learnt a lot from this... So thankful and your help is highly appreciated. Now time to play, try sample programs & see if I can come up with something !
