### ISSUE TITLE
Make error (another one)

### ISSUE THREAD

**Issue by nbenm** [ndless-nspire/Ndless#146]
`git clone --recursive https://github.com/ndless-nspire/Ndless.git` **=> OK**

`cd ndless-sdk/toolchain/`
`./build_toolchain.sh` **=> OK**

in the top level of the repository:
`make` **=> ERROR**

```
make -C ndless-sdk
make[1] : on entre dans le répertoire « /opt/Ndless/ndless-sdk »
make -C libsyscalls
make[2] : on entre dans le répertoire « /opt/Ndless/ndless-sdk/libsyscalls »
arm-none-eabi-gcc -mcpu=arm926ej-s -std=c11 -nostdlib -O3 -fPIE -mlong-calls -Wall -Werror -I ../include/ -I ../thirdparty/nspire-io/include/ -D_TINSPIRE -ffunction-sections -fdata-sections -c realpath.c -o realpath.o
realpath.c: In function 'realpath1':
realpath.c:50:12: error: 'PATH_MAX' undeclared (first use in this function); did you mean 'RAND_MAX'?
  char left[PATH_MAX], next_token[PATH_MAX];
            ^~~~~~~~
            RAND_MAX
realpath.c:50:12: note: each undeclared identifier is reported only once for each function it appears in
realpath.c:50:23: error: unused variable 'next_token' [-Werror=unused-variable]
  char left[PATH_MAX], next_token[PATH_MAX];
                       ^~~~~~~~~~
realpath.c:50:7: error: unused variable 'left' [-Werror=unused-variable]
  char left[PATH_MAX], next_token[PATH_MAX];
       ^~~~
realpath.c: In function 'realpath':
realpath.c:159:25: error: 'PATH_MAX' undeclared (first use in this function); did you mean 'RAND_MAX'?
   m = resolved = malloc(PATH_MAX);
                         ^~~~~~~~
                         RAND_MAX
cc1: all warnings being treated as errors
make[2]: *** [Makefile:21: realpath.o] Error 1
make[2] : on quitte le répertoire « /opt/Ndless/ndless-sdk/libsyscalls »
make[1]: *** [Makefile:14: build-libsyscalls] Error 2
make[1] : on quitte le répertoire « /opt/Ndless/ndless-sdk »
make: *** [Makefile:19: build-ndless-sdk] Error 2
```

dpkg -L gcc-arm-none-eabi|grep bin
/usr/bin
/usr/bin/arm-none-eabi-c++
/usr/bin/arm-none-eabi-cpp
/usr/bin/arm-none-eabi-g++
**/usr/bin/arm-none-eabi-gcc**
/usr/bin/arm-none-eabi-gcc-7.3.1
/usr/bin/arm-none-eabi-gcc-ar
/usr/bin/arm-none-eabi-gcc-nm
/usr/bin/arm-none-eabi-gcc-ranlib
/usr/bin/arm-none-eabi-gcov
/usr/bin/arm-none-eabi-gcov-dump
/usr/bin/arm-none-eabi-gcov-tool

which  arm-none-eabi-gcc
**/usr/bin/arm-none-eabi-gcc**

I have added #include <sys/syslimits.h> to realpath.c (just above the sys/params.h include) but it's the same.

Please, help.

**Comment by Vogtinator** [comment]
Same as #118 and friends - your toolchain is not set up correctly and probably pointing to the distro provided one.

**Comment by nbenm** [comment]
Thanks @Vogtinator. 
It was in my PATH environment variable but not in the beginning
