### ISSUE TITLE
Installing ndless 

### ISSUE THREAD

**Issue by Jediadam** [ndless-nspire/Ndless#153]
When I click on the installer it just opens up a blank document.

**Comment by Vogtinator** [comment]
Did you transfer ndless_resource as well? Into the correct folder?

Matching OS version?

**Comment by Jediadam** [comment]
I transferred ndless_installer_4.5.0 which has the matching OS of my calculator into the ndless folder. Then I transferd ndless_resources and ndless.cfg into the ndless folder. I can  send the a picture of the files in my ndless folder later if that will help.

**Comment by nunopenim** [comment]
What is your HW revision? On the back of your calculator, there is a serial number and a P-XXXXY, where X are numbers and Y is letter (could exist 2 letters too), what is the letter?

**Comment by Jediadam** [comment]
The letter is J

**Comment by Jediadam** [comment]
> The letter is J



> what is the letter?

The letter is J

**Comment by Jediadam** [comment]
I found out the problem! My ndless folder was in the MyLib folder.

**Comment by Jediadam** [comment]
Thanks for all the help anyway.
