### ISSUE TITLE
Can't build genzehn (WSL)

### ISSUE THREAD

**Issue by PowerUser00** [ndless-nspire/Ndless#154]
Hi, I am trying to compile C for my nspire cx. However, whenever I run "make" in the /Ndless dir, it always returns 
```
genzehn.cpp:8:10: fatal error: boost/program_options.hpp: No such file or directory
#include <boost/program_options.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
I have researched other threads, but I can't seem to find how to fix this. Seggustions?

**Comment by Vogtinator** [comment]
Install the boost headers.

**Comment by PowerUser00** [comment]
Okay. I'll give that a shot when I get home. I haven't used boost in my programming class yet. Just stdlib. I'm sure this will work. Thanks!
