### ISSUE TITLE
https://ndlessly.wordpress.com/ can not work in China

### ISSUE THREAD

**Issue by zaoqi** [ndless-nspire/Ndless#160]

**Comment by Vogtinator** [comment]
Why not? Please provide more information.

**Comment by Tadakune** [comment]
https://en.greatfire.org/https/ndlessly.wordpress.com
Shouldn't be any issues when connecting to the site from China. Ran it through this site and it returned a not enough data. In the report it didn't look like it was being blocked, but I could be wrong.
