### ISSUE TITLE
ndless can change refresh rate ?

### ISSUE THREAD

**Issue by ammjy** [ndless-nspire/Ndless#167]
Hi. My cx cas revision is W and yesterday i received. 
problem is i think display refresh rate is so low ! eyeball is painful and
when my eye has movement, i can see burn/boiling colors.
i had 2015 revision also before. and that one was fine. 

if i install ndless, can i change refresh rate ?
this issue is different with flickering 
of  backlight.

**Comment by Vogtinator** [comment]
I'm unfortunately not sure which of the LCD configuration might have an impact on that.

Different applications change different registers, so I recommend you try out a couple of applications (crafti, gpsp_nspire, gbc4nspire, ndoom and nQuake) and report which one(s) improved display.

**Comment by ammjy** [comment]
Thanks you for comment Vogtinator !
if i install externel custom os, install history will be saved on hadware or in memory ?
 i worry about warranty.

**Comment by Vogtinator** [comment]
There is no external custom OS - ndless is only a runtime change in memory and if you delete ndless' files again, it's gone. To be absolutely sure, you could format the filesystem in the maintenance menu.

**Comment by ammjy** [comment]
Thanks you for your time, Vogtinator !
now i understanded more perfectly about ndless.

**Comment by ammjy** [comment]
Vogtinator,
i have tested with crafti. and on the screen,
when object or view has movement,
same situation happend. 
it looks little bit kinda when we watch lcd monitor through smartphone camera.

**Comment by adriweb** [comment]
I saw a topic like that on reddit (is it you?) - looks like a hardware problem then, so try resetting fully the Nspire, get the latest OS, and contact TI or wherever you bought the calc from, for warranty options.

**Comment by ammjy** [comment]
Hello. Adriweb.
Thanks for your time.
yes that is me. 
thanks for advise. ive tried already everything what i can do as you said. but everything still same. 
now i waiting answer from ti development team.

**Comment by ammjy** [comment]
i think it can be solved refresh rate configration simply. 
from 2017 revision, as i know LCD model has been changed and mpu clock also increased. and in my opinion, i think resent latest os dosent considered new lcd model.

**Comment by adriweb** [comment]
I mean, you're apparently the only one complaining about such an issue, so clearly there's something wrong with your calc

**Comment by ammjy** [comment]
Ok... yes now i think so too..
i used 2015 revision before. and that one had clear lcd.

**Comment by Vogtinator** [comment]
I assume this turned out to be a hardware issue? If not, please reopen and write which application (or ndless itself?) caused this.
