### ISSUE TITLE
Question not an issue - unwanted string when program starts

### ISSUE THREAD

**Issue by nbenm** [ndless-nspire/Ndless#168]
Every time a C program starts, the following string "TI_PM_DIM_disable: Stop dim Timer. " is sent on TX channel. If a device is connected, it doesn't understand, and garbage may occur.
Is there a way to avoid this.

**Comment by Vogtinator** [comment]
Not directly - it's just debugging output from the OS.

While interrupts are disabled, the OS isn't running and the serial port is entirely under the program's control. If data before that is an issue, I recommend adding a handshake.

**Comment by nbenm** [comment]
Thanks.
After the "garbage", in fact error messages, the device sends a "start message".
So I'll simply ignore what's before.
