### ISSUE TITLE
is it possible to read a Ctrl-key character ?

### ISSUE THREAD

**Issue by nbenm** [ndless-nspire/Ndless#169]
All is said in the title.
I want to catch Ctrl-C, Ctrl-anything, but I can't.
Is there a way to do that ?

**Comment by Vogtinator** [comment]
You can do that just fine with the `isKeyPressed` function.

If you're using nspire-io though, there's no symbol defined for those so nothing gets returned.

**Comment by nbenm** [comment]
Thanks @Vogtinator 
I have read about isKeyPressed, and read some examples.
Is it possible to do something like:
```
while (1) {
    if ((isKeyPressed(KEY_NSPIRE_CTRL)) && (isKeyPressed(KEY_NSPIRE_C))) {
      return 1; // exit program, no need to display anything
    } else {
      handle this character (but what is this character?)
    }
}
```

**Comment by Vogtinator** [comment]
Yes, that should work just fine.
