### ISSUE TITLE
Ndless Compatibility Problems with GBA4Nspire

### ISSUE THREAD

**Issue by 5up3rN00b** [ndless-nspire/Ndless#172]
My ndless does work and so does my gpsp and I can play games such as pokemon emerald, or super mario bros 3. However, I tried downloading a rom-hack of pokemon, Pokemon Gaia, and my calculator would crash after encountering a wild pokemon. My ndless worked for other pokemon rom-hacks such as Pokemon Flora Sky, just not this one. Can you admins help fix this? You guys don't have to because I know it still works for other games, but thanks for your time anyways. You guys are the best and I really appreciate your help with being able to use python and play gba games. You guys are the best and I hope you guys continue doing what you are doing!

**Comment by Led1-ch** [comment]
This is a problem with the gpsp emulator itself unfortunately and nothing to do with it being on the calculator. You will also notice that Pokemon Liquid Crystal will also not work. As an active romhacker I noticed that both of these take advantage of certain C scripts, some of which are used for flagging battles. I suspect that there is some memory access stuff going on but long story short it has nothing to do with the calculator but the original emulator that was ported over.

**Comment by Vogtinator** [comment]
> This is a problem with the gpsp emulator itself unfortunately and nothing to do with it being on the calculator.

If that's the case, there's unfortunately nothing that can be fixed in Ndless, but has to be fixed in gpsp.
