### ISSUE TITLE
Not working in 4.5.1.. (How should I downgrade it to 4.5.0)

### ISSUE THREAD

**Issue by felixlee0530** [ndless-nspire/Ndless#175]
So, as someone said a few days ago, ndless is currently not working in 4.5.1 due to some issues yet.. I accidentally updated my handheld to 4.5.1 and now this became a problem.. Of course, the computer link software prevents me to downgrade it to 4.5.0.. :(

I need to delete nLoader using the app 'Btmg' and it needs to have a ndless installation to work.

Are there any possible ways to downgrade my handheld to 4.5.0 without getting help of ndless?

Or do I just need to wait until the new ndless comes out?

Any responses would be appreciated.

**Comment by KhiemmyT** [comment]
Backup everything you have using TI-Nspire Computer Link, then reset your CAS.
First turn off the unit and remove all batteries; then re-install them and

a) On the clickpad version press Home+Enter+P and On all at the same time.
b) on the touchpad version press Doc+EE+Enter and On all at the same time.

Make sure On is the last key of the combination you press. Hold all keys pressed until the maintenance menu appears. Then select the reset option.

Then install the old OS using the Computer Link Software.

**Comment by felixlee0530** [comment]
> Backup everything you have using TI-Nspire Computer Link, then reset your CAS.
> First turn off the unit and remove all batteries; then re-install them and
> 
> a) On the clickpad version press Home+Enter+P and On all at the same time.
> b) on the touchpad version press Doc+EE+Enter and On all at the same time.
> 
> Make sure On is the last key of the combination you press. Hold all keys pressed until the maintenance menu appears. Then select the reset option.
> 
> Then install the old OS using the Computer Link Software.

It still shows the error message of being unable to install old version (downgrade protection)...

**Comment by felixlee0530** [comment]
> > Backup everything you have using TI-Nspire Computer Link, then reset your CAS.
> > First turn off the unit and remove all batteries; then re-install them and
> > a) On the clickpad version press Home+Enter+P and On all at the same time.
> > b) on the touchpad version press Doc+EE+Enter and On all at the same time.
> > Make sure On is the last key of the combination you press. Hold all keys pressed until the maintenance menu appears. Then select the reset option.
> > Then install the old OS using the Computer Link Software.
> 
> It still shows the error message of being unable to install old version (downgrade protection)...
