### ISSUE TITLE
Is a given path a file or directory? (broken stat)

### ISSUE THREAD

**Issue by lights0123** [ndless-nspire/Ndless#178]
How can I identify whether a path is a file or directory? The normal way would be to call `stat` and look at the `st_mode`, but it is set to 0 for both files and directories. Is there any way to differentiate them other than opening the file and checking for an error?

**Comment by Vogtinator** [comment]
Hm, stat is the correct method to use. Which OS version does it not work for?
As a workaround, you could try fopen/opendir to check.

**Comment by lights0123** [comment]
@Vogtinator as it turns out, plain `stat` does *not* work—it does what I described, where `st_ino` and `st_nlink` are the only variables populated. **However**, `nuc_stat` works as expected. Can we replace [`_stat`](https://github.com/ndless-nspire/Ndless/blob/1662d2a189b32a380d53cce287213e9585bf536d/ndless-sdk/libsyscalls/stdlib.cpp#L271) with a call to `nuc_stat` and translate it over?

**Comment by lights0123** [comment]
For reference, here's examples of outputs of both.
# Directory (I used /documents/)
## `stat`
```c
stat {
  st_dev: 0,
  st_ino: 16832,
  st_nlink: 1,
  st_mode: 0, // incorrect—set to 0
  st_uid: 0,
  st_gid: 0,
  st_rdev: 0,
  st_size: 0,
  st_blksize: 0,
  st_blocks: 0,
  st_atim: timespec {
    tv_sec: 0,
    tv_nsec: 0
  },
  st_mtim: timespec {
    tv_sec: 0,
    tv_nsec: 0
  },
  st_ctim: timespec {
    tv_sec: 0,
    tv_nsec: 0
  }
}
```
## `nuc_stat`
```c
nuc_stat {
  st_dev: 0,
  st_ino: 0,
  st_mode: 16832, // Correct - has a value
  st_nlink: 1,
  st_uid: 0,
  st_gid: 0,
  st_rdev: 0,
  st_size: 0,
  st_atime: 0,
  st_mtime: 0,
  st_ctime: 0,
}
```
# File (I used /documents/ndless/ndless.cfg.tns)
## `stat`
```c
stat {
  st_dev: 0,
  st_ino: 33152,
  st_nlink: 1,
  st_mode: 0, // incorrect—set to 0
  st_uid: 180,
  st_gid: 0,
  st_rdev: 0,
  st_size: 0,
  st_blksize: 0,
  st_blocks: 2067,
  st_atim: timespec {
    tv_sec: 0,
    tv_nsec: 0
  },
  st_mtim: timespec {
    tv_sec: 0,
    tv_nsec: 2067
  },
  st_ctim: timespec {
    tv_sec: 0,
    tv_nsec: 0
  }
}
```
## `nuc_stat`
```c
nuc_stat {
  st_dev: 0,
  st_ino: 0,
  st_mode: 33152, // correct - has a value
  st_nlink: 1,
  st_uid: 0,
  st_gid: 0,
  st_rdev: 0,
  st_size: 180,
  st_atime: 0,
  st_mtime: 2067,
  st_ctime: 2067,
}
```

**Comment by Vogtinator** [comment]
> @Vogtinator as it turns out, plain `stat` does _not_ work—it does what I described, where `st_ino` and `st_nlink` are the only variables populated. **However**, `nuc_stat` works as expected. Can we replace [`_stat`](https://github.com/ndless-nspire/Ndless/blob/1662d2a189b32a380d53cce287213e9585bf536d/ndless-sdk/libsyscalls/stdlib.cpp#L271) with a call to `nuc_stat` and translate it over?

That's exactly what `_stat` already does.

In stubs.cpp (autogenerated):

```
int nuc_stat(const char *p1, struct nuc_stat *p2)
{
        return syscall<e_stat, int>(p1,p2);
}
```

in stdlib.c:

```
int _stat(const char *path, struct stat *st)
{
        struct nuc_stat nuc_st;
        int ret = syscall<e_stat, int>(path, &nuc_st);
        if(ret < 0)
                return errno_update(ret);

        st->st_dev = nuc_st.st_dev;
        st->st_ino = nuc_st.st_ino;
        st->st_mode = nuc_st.st_mode;
        st->st_nlink = nuc_st.st_nlink;
        st->st_uid = nuc_st.st_uid;
        st->st_gid = nuc_st.st_gid;
        st->st_rdev = nuc_st.st_rdev;
        st->st_size = nuc_st.st_size;
        st->st_atime = nuc_st.st_atime;
        st->st_mtime = nuc_st.st_mtime;
        st->st_ctime = nuc_st.st_ctime;

        return 0;
}
```

However, I see that the `struct stat` you're showing there is just completely corrupt. It looks like `struct stat` was used in a call to `nuc_stat` somewhere. Can you post your example code?

> I'm running 4.5.0 in firebird.

Ok.

**Comment by adriweb** [comment]
@lights0123 so what did you end up doing? What did you code look like?

**Comment by lights0123** [comment]
@adriweb This was part of my Rust port. It seems to have gotten incorrect bindings to the [`stat` struct](https://docs.rs/ndless-sys/0.2.0/ndless_sys/struct.stat.html), that got the padding incorrect. I then converted it to use [`nuc_stat`](https://docs.rs/ndless-sys/0.2.0/ndless_sys/struct.nuc_stat.html), where it worked successfully.

**Comment by adriweb** [comment]
Alright!
