### ISSUE TITLE
<dirent.h> in newlib build step.

### ISSUE THREAD

**Issue by Choups314** [ndless-nspire/Ndless#18]
I have noticed that the directory newlib/libc/posix is not built at all (newlib compiles fine, but it probably skip this folder). The Makefile of this directory  is generated but it fails with this error : 
```
error: #error "<dirent.h> not supported"
```
while trying to build closedir.c.

In fact it tries to use newlib/libc/include/sys/dirent.h which does not seem to be supported ... Maybe it should use Ndless/ndless-sdk/include/dirent.h instead ?

I don't know if the posix directory has been disabled, but I need popen and pclose functions ... (popen.c does not rely on dirent.h, so maybe I could skip closedir.c and the other files that require dirent.h)

**Comment by Vogtinator** [comment]
> I have noticed that the directory newlib/libc/posix is not built at all
This is deliberate, most of POSIX is not supported, sadly.

> I don't know if the posix directory has been disabled, but I need popen and pclose functions 
Not implemented, and it's definitely not easy to do.

**Comment by Choups314** [comment]
Ok, thanks for this very quick reply ;)

I needed it to build the cairo graphic lib but I found a workaround (The functions were just needed in the test/perf steps, so I just removed them).
