### ISSUE TITLE
Support for OS 4.5.1

### ISSUE THREAD

**Issue by trueToastedCode** [ndless-nspire/Ndless#180]
Is/Will be there a 4.5.1 ndless development or is the project dead... i mean how many security issues did the texas instruments develop. team fixed? I am asking for this because i looked for the time between previous OS releases and the mating ndless jailbreak... and for me this version is a little bit a exception to the distance between os / ndless realease. I know it was already said that it is not possible give any ETA but i am only asking if there is even a development...

**Comment by Vogtinator** [comment]
> Is/Will be there a 4.5.1 ndless development

Yes.

> or is the project dead...

No.

> i mean how many security issues did the texas instruments develop. team fixed?

The one used for 4.5.1.

> I am asking for this because i looked for the time between previous OS releases and the mating ndless jailbreak... and for me this version is a little bit a exception to the distance between os / ndless realease. 

Don't forget the gap between 3.1 and 3.6.

The reason for the delay is that there's now much more to do with the new CX II model.

> I know it was already said that it is not possible give any ETA but i am only asking if there is even a development...

There is.

**Comment by Vogtinator** [comment]
Closing as dup of #173.
