### ISSUE TITLE
Error in Ndless 4.5 with Startup folder and PTT

### ISSUE THREAD

**Issue by Nick768** [ndless-nspire/Ndless#182]
I've been running ControlX and Ndless on my nspire CX for some time, but now I've noticed that the apps in the Startup folder don't work in Press-to-Test mode. For example the CAS-Patcher: It works fine as long as the calculator is not in Press-to-Test mode. Otherwise the calculator crashes immediately when I try to run a CAS calculation. What could be the reason? Is it possible to fix this?

**Comment by Vogtinator** [comment]
During PTT mode all files are hidden, this includes startup programs. You need to create a startup folder in PTT mode and copy the files in there.

**Comment by Nick768** [comment]
Thanks for your fast help, but I always thought, because OS 3.1 had all these PTT hacks running through the Startup folder, that the Startup folder would still work in Press-to-Test mode. Interestingly, it is possible to call nText in Press-to-Test mode by simply opening a .txt.tns file in it. You don't even have to have nText in any folder in Press-to-Test mode.

**Comment by Nick768** [comment]
But that gives me an idea, which I will try out later. I will try to bind the CAS patch to a file extension in the ndless configs and create a file with this extension in press-to-test mode. If I call it, the patcher should start theoretically, right?

**Comment by adriweb** [comment]
The fact that you are able to transfer things when you are in PTT means that you have access to a computer or another device at the very least. So it's by definition a non-secure/restricted environment. At this point, there's nothing preventing you from doing anything. PTT is only useful if it's used in a controlled environment (and more so when PTT is enabled on premises, not before)

**Comment by Nick768** [comment]
This is actually the case in my school for exams. Now that I've finished all my mathematics exams, I wanted to experiment a bit with the calculator. I hadn't even installed ndless in the exams (despite ControlX).
But back to the subject. I will definitely check my idea and then report if it works.

**Comment by Vogtinator** [comment]
If you have ndless.cfg.tns for the file associations and the program that's associated with it visible in PTT mode, it should work fine.

**Comment by Arudarin** [comment]
@Nick768 What were your results (if any)?

**Comment by Vogtinator** [comment]
No reply, closing. Please reopen if the issue remains.
