### ISSUE TITLE
Support for 4.5.2.8

### ISSUE THREAD

**Issue by XxTopKillerzZ** [ndless-nspire/Ndless#186]
Is there any suport for 4.5.2.8?
I acidentaly installed the latest version from the ti-nspire oficial website as i tought it was suported cuz its still 4.5, but when i try to install i get a white screen.

**Comment by Vogtinator** [comment]
Nope, same story as for 4.5.1: https://github.com/ndless-nspire/Ndless/issues/173

**Comment by XxTopKillerzZ** [comment]
Is there any way to rollback my software version?

**Comment by XxTopKillerzZ** [comment]
Btw, i already did the 
Part C of this toturial: https://www.reddit.com/r/nspire/comments/6a2cd7/tutorial_install_cas_on_tinspire_cx_works_on/

**Comment by DIVKING12** [comment]
> Is there any way to rollback my software version?

there is no way to downgrade your software. I am stuck in 4.5.1 lmao
