### ISSUE TITLE
Malloc leaks memory

### ISSUE THREAD

**Issue by gameblabla** [ndless-nspire/Ndless#19]
I noticed that malloc, when used and even if freed,
leaks memory and can cause the calculator to become unstable.
(happens when you make heavy use of malloc)
For my Picodrive port, when i (mostly) switched from malloc
to just a bunch of arrays, the weird issues i had were gone.

**Comment by lkjcalc** [comment]
On which OS and calculator model?

**Comment by gameblabla** [comment]
OS 3.1 Ndless r914. If it's really the old version of Ndless the issue, then it might be a good idea to release the latest for OS 3.1...

**Comment by Vogtinator** [comment]
This is known and a bug in the OS (or syscall handler, not sure).
Ndless 3.9 is already compatible with OS 3.6 and 3.1 as long as you use the appropriate installers.

**Comment by gameblabla** [comment]
So this is an OS bug then, didn't know. You might want to put more instructions on how to install ndless 3.9 on OS 3.1 though because i tried it myself and failed. Anyways, i think you should close this.

**Comment by Vogtinator** [comment]
Install the old ndless 3.1 and then swap ndless_resources.tns and reboot. If that doesn't work, please open another issue here, that'd be a bug.
