### ISSUE TITLE
Ndless crashes my nspire

### ISSUE THREAD

**Issue by geekpersonman** [ndless-nspire/Ndless#191]
I have a revision E nspire running nBoot and ControlX 5.0.2 and 4.5.1 OS, I have successfully compiled ndless from scratch but when I use the ndless_resources.tns file it produces it boot loops my calculator. The ndless_resources.tns file that is on the releases page works with my calculator on 4.5.1. I'll add the file it produces so you can take a look at it. [https://drive.google.com/file/d/1yJNNQ2U7KPRXuk5CVTbhC0z20rXY0G4h/view?usp=sharing](url)

**Comment by Vogtinator** [comment]
Does it work if you `git checkout 84c05df`?

**Comment by Vogtinator** [comment]
Nope, the issue seems to be a different one. You have to use `ndless_resources.tns`, not `ndless_resources_zehn.tns`. The former is in the `ndless/calcbin` directory.

**Comment by Vogtinator** [comment]
No reply, closing. Please reopen if the issue remains.
