### ISSUE TITLE
usb_register_driver?

### ISSUE THREAD

**Issue by nspiredev500** [ndless-nspire/Ndless#193]
I want to try making my own usb driver. I looked at HIDn and tried to recompile it, but it gives me loads of errors. It seems the sdk changed quite a bit over that time. I just took the ums.c file and commented out the body of the methods and replaced them with a change of a status variable that gets printed to the screen. I call usb_register from my programm and even clear the cache afterwards, so the changes should be made, and my programm is resident. However, it doesn't seem the methods get called at all. That's why I looked for documentation what usb_register_driver expects as parameters, but I couldn't find anything.
Or maybe it's just my usb device, but it works with the HIDn binary.

**Comment by Vogtinator** [comment]
It seems like the code for usbHIDn is the only documentation available...

The definition for `struct s_usb_pipe_buf` apparently got lost some time ago, but might be somewhere in git. You should try getting hidn to compile by fixing the errors instead of pasting some code together. Without any code snippets I can't help more than that.

**Comment by nspiredev500** [comment]
I already found the definition for struct s_usb_pipe_buf, it was in the [nspiretool-history repository](https://github.com/ndless-nspire/nsptools-history) somewhere in the old Ndless-sdk, I think it was os.h. Maybe the definition could get included in the current Ndless-sdk.
`static struct s_usb_pipe_buf { // strangely needed by TI's usbd_open_pipe_intr
 	u_char *buf;
 	int dummy1; // set to 0
 	int dummy2; // set to 0
 };`

**Comment by nspiredev500** [comment]
I managed to recompile it without errors, but it doesn't work on my calculator. I commented out the nl_no_scr_redraw and nio_grid_puts because they weren't found. Probably nio changed, but nl_no_scr_redraw should work. They were only there to indicate that hidn is installed, so that should be no problem. Do you have to include specific header files nl_no_scr_redraw to work or is my sdk broken? I also commented out the nl_relocdata because I read that that call is obsolete now.

**Comment by Vogtinator** [comment]
> I managed to recompile it, but it doesn't work on my calculator. I commented out the nl_no_scr_redraw and nio_grid_puts because they weren't found. Probably nio changed, but nl_no_scr_redraw should work. They were only there to indicate that hidn is installed, so that should be no problem. Do you have to include specific header files nl_no_scr_redraw to work or is my sdk broken?

The syscall is still there, but there is no C function for calling it anymore.

> I also commented out the nl_relocdata because I read that that call is obsolete now.

Correct.

> There were also some warnings, but unless the syscall declarations changed they probably were there in the original, too.
> If I try the original makefile, it also works, but displays the message that the format isn't recongized when trying to start it. From the makefile it's looking like it just uses objcopy to copy from the elf to the tns. I don't know enough about elf and ndless to know whether ndless should be capable of loading such a file.

No, the old SDK built .elf files differently so that objcopy resulted in an old-style `PRG\0` executable file.

I had a look at the `usb_register_driver` syscall, it looks broken:

```
int usb_register_driver(int p1, int(*p2[])(device_t), const char* p3, int p4, unsigned int p5) {
       return syscall<e_usb_register_driver, int>(p1,p2,p3,p4);
 }
```

Parsing C function declarations with regular expressions wasn't a good idea, now that's the result...
Wasn't hard to fix thankfully, please try with #194.

**Comment by nspiredev500** [comment]
If I replace the files with the new ones, which part of the sdk do I have to rebuild? Or don't I have to rebuild at all?

**Comment by Vogtinator** [comment]
You have to rebuild `libsyscalls`, but rebuilding everything doesn't take more than a minute anyway.

**Comment by nspiredev500** [comment]
I copied the files into their locations, ran `make clean` and then `make` in libsyscalls, but I get the same warnings and it doesn't work. Somehow it hadn't noticed the files changed so I had to clean. Maybe that messed things up. Which file format is the old HIDn binary? Can I disassemble it to look for differences?

**Comment by nspiredev500** [comment]
If I try to use my version with function call indication it just freezes, so that's at least something different.

**Comment by Vogtinator** [comment]
> Which file format is the old HIDn binary? Can I disassemble it to look for differences?

Just `objdump -D -b binary -marm file.tns`
