### ISSUE TITLE
Ndless 5.0?

### ISSUE THREAD

**Issue by 101-00-0-100-0** [ndless-nspire/Ndless#195]
Will there ever be support for Ndless 5.0 or 5.1? I got my Nspire CX II CAS a while ago, and I can't wait to install some games and widgets on it. I have searched around and saw that 5.0 support has been announced to be in development since about half a year ago, so I'm assuming that it is difficult to find a breaking point(?) in the OS or that there's just something very different about the 5.0 OS. I would love to hear about the progress of the development now.
On the other hand, I am curious if it is possible to downgrade my calculator's OS to 4.5.0. If it's possible, what do I need to do, and do I need to worry about bricking my calculator?

**Comment by ifonefox** [comment]
There is already an open issue for 5.0 and 5.1 #177

**Comment by Vogtinator** [comment]
Dup of #177.
