### ISSUE TITLE
Any ETA's on the 5.0 update?

### ISSUE THREAD

**Issue by DogeMomentt** [ndless-nspire/Ndless#196]
Thats it just want to know

**Comment by Vogtinator** [comment]
Unfortunately my time machine is currently broken, so I can't ask the future when it was ready.

Dup of #177

**Comment by DogeMomentt** [comment]
> Unfortunately my time machine is currently broken, so I can't ask the future when it was ready.
> 
> Dup of #177 

It's still coming right?

**Comment by MyChemicalAddiction** [comment]
> > Unfortunately my time machine is currently broken, so I can't ask the future when it was ready.
> > Dup of #177
> 
> It's still coming right?

Yes, it's coming; and it's coming faster the less questions you ask about it.
