### ISSUE TITLE
Ndless 4.5.1 or 4.5.2 update

### ISSUE THREAD

**Issue by GameHerobrine** [ndless-nspire/Ndless#197]
<div class="main" style="font-size:20;">So... The ndless update hasn't been around for about 7 month</div>
When will the update be to <b>4.5.1</b> or <b>4.5.2 version<b>?

**Comment by lights0123** [comment]
https://github.com/ndless-nspire/Ndless/issues/196#issuecomment-575887444

**Comment by MyChemicalAddiction** [comment]
> So... The ndless update hasn't been around for about 7 month
> When will the update be to 4.5.1 or 4.5.2 version?

It'll be when it'll be. Stop friggin' asking

**Comment by KhiemmyT** [comment]
Bruh why you even responding to a 21 day old post
