### ISSUE TITLE
Idk if this will work maybe its dumb but idk

### ISSUE THREAD

**Issue by confused-student** [ndless-nspire/Ndless#198]
do you guys think that we, as a community, can convince Texas instruments to kindly allow downgrading os? i know it sounds kinda dumb but who knows, maybe Ti _can_ have a change of heart.

**Comment by adriweb** [comment]
Nope, it's done on purpose. even regardless of whether there is an Ndless available for the version. They have basically always done it, they keep doing it, and will likely always do it.
But anyway, it's always a matter of time until a new Ndless will be available, making it probably possible to allow downgrading (if that version has something you don't want for some reason)
