### ISSUE TITLE
Is There a Way to Differentiate Between Versions of the Nspire Visually?

### ISSUE THREAD

**Issue by moonpiedumplings** [ndless-nspire/Ndless#199]
Ok, so I see a lot of people asking about newer OS support for Ndless, so I intend to buy an older, used model of the calculator to avoid having to wait for a jailbreak to be created. 

On Ebay, multiple people are selling used versions of the Ti Nspire CX CAS. However, they do not list the date they purchased it, so I can not tell what version of the Ti Nspire they have. 

However, I noticed some differences in the battery cover on the back. I have attached some images to be used as examples of this. 
![image](https://user-images.githubusercontent.com/43561042/73587096-cd03f700-446b-11ea-8448-9ac21fd19ed1.png)
![image](https://user-images.githubusercontent.com/43561042/73587100-de4d0380-446b-11ea-9a97-946bc2ee3210.png)

Can these be used to differentiate between versions of the Nspire? If so, which one is the one that should work with Ndless. If not, is there another way?

**Comment by adriweb** [comment]
You can only tell/read the Hardware Revision from the datecode written on the back. But the OSes run on all the hardware revisions, and Ndless targets specific OS versions. So, no, it's not really helpful. Right now, even an old rev could have been updated to OS v4.5.2, which would make it incompatible with Ndless so far. Your best bet when buying a calc online would be to ask the seller. That said, I'm not sure new calcs come with the very latest OS... if they still come with 4.5.0 then that's OK for Ndless.

**Comment by moonpiedumplings** [comment]
The new calcs come with 4.5.0? Can anyone verify this? I don't want to waste 130+ dollars on something that like this, just to have to return it.
