### ISSUE TITLE
Error while building ndless and sdk

### ISSUE THREAD

**Issue by deadmeatpt** [ndless-nspire/Ndless#20]
In top level of ndless, when i type "make" this appears:

cygwinusr@antonio-laptop ~/ndless
$ make
make all in ndless-sdk...
make[1]: Entering directory '/home/cygwinusr/ndless/ndless-sdk'
make all in tools...
make[2]: Entering directory '/home/cygwinusr/ndless/ndless-sdk/tools'
make all in luna...
make[3]: Entering directory '/home/cygwinusr/ndless/ndless-sdk/tools/luna'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/cygwinusr/ndless/ndless-sdk/tools/luna'
make all in zehn_loader...
make[3]: Entering directory '/home/cygwinusr/ndless/ndless-sdk/tools/zehn_loader'
"" -g -Os -Wall -Wextra -march=armv5te -fPIE -std=c++11 -fno-rtti -fno-exceptions -Wl,-Tldscript -nostdlib -nostartfiles -I ../../include -D _LDBL_EQ_DBL loader.cpp -o zehn_loader.tns.elf
/bin/sh: : command not found
Makefile:12: recipe for target 'zehn_loader.tns.elf' failed
make[3]: *** [zehn_loader.tns.elf] Error 127
make[3]: Leaving directory '/home/cygwinusr/ndless/ndless-sdk/tools/zehn_loader'
Makefile:4: recipe for target 'all' failed
make[2]: *** [all] Error 1
make[2]: Leaving directory '/home/cygwinusr/ndless/ndless-sdk/tools'
Makefile:4: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/cygwinusr/ndless/ndless-sdk'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 1

Can anyone tell me what I'm doing wrong?

**Comment by Vogtinator** [comment]
You don't have nspire-gcc in your $PATH.

**Comment by deadmeatpt** [comment]
*epic facepalm* Yes, i forgot that part :D thanks mate, sorry for bothering
