### ISSUE TITLE
Linking with SDL_img gives undefined references to libc

### ISSUE THREAD

**Issue by herrhotzenplotz** [ndless-nspire/Ndless#205]
```bash
$ nspire-ld file.o -o file.elf
arm-none-eabi-ld: Ndless/ndless-sdk/bin/../lib/libSDL_image.a(IMG_pnm.o): in function `ReadNumber':
IMG_pnm.c:(.text+0xe4): undefined reference to `__ctype_ptr__'
```

This is a symbol that should exist in LibC. Apparently, newlib does not export it. A quick nm gives:
```bash
$ find ./lib/ -name \*.a | xargs nm | grep __ctype_ptr__
         U __ctype_ptr__
nm: SDL_malloc.o: no symbols
nm: SDL_stdlib.o: no symbols
nm: SDL_yuv_mmx.o: no symbols
$ find ./toolchain/install -name \*.a | xargs nm | grep __ctype_ptr__
$ (no results)
```
The first result comes from the libSDL_image.a itself.

The toolchain is freshly built, so #141 is unrelated.

**Comment by Vogtinator** [comment]
Yeah, `__ctype_ptr__` was dropped in newlib 3.0 and libSDL.a was rebuilt (b0e84cfaab5fc0791d551c6d4b967665dc3be107). It looks l ike SDL_image.a needs the same treatment.

**Comment by herrhotzenplotz** [comment]
I just rebuilt SDL_image. I'll open a pull request if you don't mind.

**Comment by Vogtinator** [comment]
Sounds good! Can you add reproducible instructions on how to rebuild it in the PR as well? That might be very useful in the future.

**Comment by herrhotzenplotz** [comment]
Of course :smiley:
