### ISSUE TITLE
fatal: pack has bad object at offset 318368: inflate returned -3

### ISSUE THREAD

**Issue by Kunait** [ndless-nspire/Ndless#217]
Sadly it's me again, different issue now tho. I am trying to pull the repo from github but I get this error "error: inflate: data stream error (incorrect data check)
fatal: pack has bad object at offset 318368: inflate returned -3
fatal: index-pack failed"

This is the complete output, I don't know what I am doing wrong.

**Comment by adriweb** [comment]
looks like something got corrupted when downloading the repo?
I guess delete the folder and try again. Not much we can do about it.

**Comment by Kunait** [comment]
I tried several times, but there is nothing to delete. It doesn't even create a folder, I don't know why like this should work especially on my new Virtual Machine...

Ndless really doesn't want me to use it xD

**Comment by Vogtinator** [comment]
Try to clone it in a different directory. If that doesn't work, maybe try git with `-c protocol.version=0`.

**Comment by Kunait** [comment]
I tried, but it didn't work. But I changed to VMWare and now it works, I really don't know why. I even removed and reinstalled git but to no avail. I'm closing this issue, currently building the toolchain again, pray for me :/
