### ISSUE TITLE
Extension association should ignore .prg when searching program

### ISSUE THREAD

**Issue by lkjcalc** [ndless-nspire/Ndless#22]
IMO it doesn't make sense that e.g. the association "ext.txt=nTxt" fails if the prg-version of the program is used (i.e. filename nTxt.prg.tns)

**Comment by Vogtinator** [comment]
That's why the standard Makefile does not add ".prg" anymore..
Considering that only a few programs have a .prg.tns version and renaming is pretty simple, it doesn't need to be fixed IMO.

**Comment by lkjcalc** [comment]
I guess it's not worth the slowdown then.
