### ISSUE TITLE
4.5.2.8

### ISSUE THREAD

**Issue by NONS3NS3** [ndless-nspire/Ndless#220]
been getting into jailbreaking devices, started with a TI-nspire cx, but the os got updated to the latest.
is there any news on the latest version of endless being released,
thanks always
NON

**Comment by lights0123** [comment]
Look around. https://github.com/ndless-nspire/Ndless/issues/177#issuecomment-646142216

**Comment by Vogtinator** [comment]
Closing as dup.

**Comment by Mordy24** [comment]
when will 4.5.2.8 be out to download!!!
