### ISSUE TITLE
call a destructor for lua libraries

### ISSUE THREAD

**Issue by nspiredev500** [ndless-nspire/Ndless#223]
I want to make a lua library, but it needs to deallocate ressources, even if the lua app didn't do it itself.
Could you call the main function with specific arguments when shutting down the interpreter or something like that, so the libraries get a change to do deinitialize themselves?

Maybe instead of passing nothing to the library main method, pass a uint32_t* where the library can put it's destructor address, if it has one?

**Comment by Vogtinator** [comment]
> I want to make a lua library, but it needs to deallocate ressources, even if the lua app didn't do it itself.

That's what finalizers are for. Is there a reason you can't use them?

> Could you call the main function with specific arguments when shutting down the interpreter or something like that, so the libraries get a change to do deinitialize themselves?

That would not be compatible with existing libraries, those would then intialize themselves again, achieving the exact opposite of the desired behaviour...

> Maybe instead of passing nothing to the library main method, pass a uint32_t* where the library can put it's destructor address, if it has one?

The signature is `int main(int argc, char *argv[])`, passing a pointer there wouldn't be very nice, it would at least have to be converted to a hex number.

What would be possible is to have a syscall which registers a cleanup handler called by `ld_free`. However, Ndless only knows which executable is calling it before it returns from `main`...

**Comment by nspiredev500** [comment]
Thanks to you, I now found the finalizers in the Lua documentation for C libraries.
