### ISSUE TITLE
Error running make in git root directory

### ISSUE THREAD

**Issue by ttmx** [ndless-nspire/Ndless#224]
This is what I am getting. I ran the build tools.sh beforehand and added stuff to path.
Didn't do anything else that I remember that could have affected it.
If it makes any difference, I'm on Arch.
```make -C ndless-sdk
make[1]: Entering directory '/home/tiago/Documents/src/Ndless/ndless-sdk'
make -C libsyscalls
make[2]: Entering directory '/home/tiago/Documents/src/Ndless/ndless-sdk/libsyscalls'
arm-none-eabi-g++ -mcpu=arm926ej-s -std=c++11 -nostdlib -O3 -fPIE -fno-exceptions -fno-rtti -mlong-calls -Wall -Werror -I ../include/ -I ../thirdparty/nspire-io/include/ -D_TINSPIRE -ffunction-sections -fdata-sections -c stdlib.cpp -o stdlib.o
stdlib.cpp: In function 'int _stat(const char*, stat*)':
stdlib.cpp:286:6: error: 'struct stat' has no member named 'st_atime'; did you mean 'st_atim'?
  286 |  st->st_atime = nuc_st.st_atime;
      |      ^~~~~~~~
      |      st_atim
stdlib.cpp:287:6: error: 'struct stat' has no member named 'st_mtime'; did you mean 'st_mtim'?
  287 |  st->st_mtime = nuc_st.st_mtime;
      |      ^~~~~~~~
      |      st_mtim
stdlib.cpp:288:6: error: 'struct stat' has no member named 'st_ctime'; did you mean 'st_ctim'?
  288 |  st->st_ctime = nuc_st.st_ctime;
      |      ^~~~~~~~
      |      st_ctim
make[2]: *** [Makefile:18: stdlib.o] Error 1
make[2]: Leaving directory '/home/tiago/Documents/src/Ndless/ndless-sdk/libsyscalls'
make[1]: *** [Makefile:14: build-libsyscalls] Error 2
make[1]: Leaving directory '/home/tiago/Documents/src/Ndless/ndless-sdk'
make: *** [Makefile:19: build-ndless-sdk] Error 2
```

**Comment by lights0123** [comment]
What's the output of `which arm-none-eabi-g++m`?

**Comment by Vogtinator** [comment]
Hm, this mismatch could be avoided by using `$(nspire-tools _toolchainpath)` in `ndless-sdk/tools/zehn_loader/Makefile` and `ndless-sdk/libsyscalls/Makefile` as well.

**Comment by ttmx** [comment]
> What's the output of `which arm-none-eabi-g++`?

`/usr/bin/arm-none-eabi-g++`

> Hm, this mismatch could be avoided by using `$(nspire-tools _toolchainpath)` in `ndless-sdk/tools/zehn_loader/Makefile` and `ndless-sdk/libsyscalls/Makefile` as well.

Is that something I can fix?
Also, look at IRC if possible.

**Comment by lights0123** [comment]
> `/usr/bin/arm-none-eabi-g++`

You messed up when adding stuff to your path—you have `/usr/bin` before the Ndless bin directories.

> Is that something I can fix?

Yes. Untested, but it's going to be along the lines of: replace `GXX := "$(shell (which arm-elf-g++ arm-none-eabi-g++ arm-linux-gnueabi-g++ | head -1) 2>/dev/null)"` in `ndless-sdk/tools/zehn_loader/Makefile` with `GXX := $(shell ($(nspire-tools _toolchainpath)/arm-none-eabi-g++)` (there's possibly a simpler way, I'm not very familiar with Makefiles). Then, in `ndless-sdk/libsyscalls/Makefile`, add to the top:
```
GXX := $(shell ($(nspire-tools _toolchainpath)/arm-none-eabi-g++)
GCC := $(shell ($(nspire-tools _toolchainpath)/arm-none-eabi-gcc)
```

and everywhere you see `arm-none-eabi-g++`, replace it with `$(GXX)`, and same thing for `arm-none-eabi-gcc` and `$(GCC)`.

**Comment by ttmx** [comment]
Fixed it by uninstalling the package that I installed by mistake. I don't actually need to compile for other arm devices. Thank you either way.
Thanks vog and lights!
