### ISSUE TITLE
Ndless 5.2.0 does not work well with N-0320AK models

### ISSUE THREAD

**Issue by FerdinandoPH** [ndless-nspire/Ndless#236]
I have a TI Nspire CX II CAS T with the 5.2.0.771 os, and whenever I try to launch an app which needs compatibility mode, I will get the pop up message, and after clicking OK my calculator will crash, being the reset button the only way to make it work again.
I haven't found any app which needs compatibility mode that does not crash when I try to open it yet.

Does anyone know what could be the problem?

**Comment by chenxi050402** [comment]
I have the problem too when trying to run gbsp

**Comment by Facts-and-Logic** [comment]
For me gpsp works fine on 5.2.0.711 OS. Some apps such as nclock and nover doesn't display and freezes with the reset button making it work again.

**Comment by Vogtinator** [comment]
nClock and Nover do not support CX II, so that is expected.

**Comment by chenxi050402** [comment]
It freezes sometime before you click ok

**Comment by FerdinandoPH** [comment]
> For me gpsp works fine on 5.2.0.711 OS. Some apps such as nclock and nover doesn't display and freezes with the reset button making it work again.

How did you do it?

**Comment by Facts-and-Logic** [comment]
it just worked for me

**Comment by chenxi050402** [comment]
It's not freezing, it's just extremely slow, you can still move the cursor around for a few frames

**Comment by chenxi050402** [comment]
I haven't found any app that doesn't need compatibility mode yet

**Comment by Facts-and-Logic** [comment]
nSonic doesn't work either

**Comment by adriweb** [comment]
Yes critor said nSonic needs a specific syscall and its not available yet, so I'll guess an update will be needed. Check back later on its archive page on TI-Planet. 

Reminder: System utilities (writing to the nand) not working right now is expected, it's done on purpose by Ndless 5.2 to prevent damage caused by old apps not knowing the CX II hardware (obviously). You'll have to wait for updates. Some things are already being updated

**Comment by chenxi050402** [comment]
> Yes critor said nSonic needs a specific syscall and its not available yet, so I'll guess an update will be needed. Check back later on its archive page on TI-Planet. Reminder: System utilities (writing to the nand) not working right now is expected, it's done on purpose by Ndless 5.2 to prevent damage caused by old apps not knowing the CX II hardware (obviously). You'll have to wait for updates. Some things are already being updated

So no app works now?

**Comment by adriweb** [comment]
?
Almost everything works (games, emulators, some utilities...), just not system apps that may try to use `write_nand`.

**Comment by chenxi050402** [comment]
> ?
> Almost everything works (games, emulators, some utilities...), just not system apps that may try to use `write_nand`.

But why I freeze on launching any app with compatibility mode?

**Comment by FerdinandoPH** [comment]
The only ndless app that I have managed to get working is crafti, and it had some problems as well

**Comment by adriweb** [comment]
Well I'm not sure what to tell you, do you have the latest version of everything? What hardware revision/date is your calculator?

Here are some tests made along the way before the release (and updated to reflect the status after some programs got updated / rebuilt with the new SDK)
![image](https://user-images.githubusercontent.com/660896/93796900-82f1a080-fc09-11ea-90a3-7da412da80c6.png)

**Comment by FerdinandoPH** [comment]
Where do I look at my hardware revision/date?

**Comment by FerdinandoPH** [comment]
Also, could you please send the excel file? As it has the link of the tested apps, these might work (maybe the problem is that I am taking obsolete apps)

**Comment by adriweb** [comment]
> Where do I look at my hardware revision/date?

On the back of the calculator, to the right of the serial number, there should be a few characters, like `N-0719AH`.

**Comment by FerdinandoPH** [comment]
n-0320AK

**Comment by chenxi050402** [comment]
> n-0320AK

me too

**Comment by chenxi050402** [comment]
> The only ndless app that I have managed to get working is crafti, and it had some problems as well

crafti doesn't work for me

**Comment by adriweb** [comment]
Oh wow, `N-0320AK` is very new, maybe TI changed some stuff recently :(

**Comment by FerdinandoPH** [comment]
It came with OS 5.1

**Comment by FerdinandoPH** [comment]
> Oh wow, `N-0320AK` is very new, maybe TI changed some stuff recently :(
> What OS version did those calculators come with, do you remember?
> 
> Added to [the spreadsheets](https://docs.google.com/spreadsheets/d/1N_2tBusqjVzefKb4impi-VwdM-RgOSIMmXBemJymxA0/edit#gid=0&range=D106)...
> 
> Maybe you can try this too [Vogtinator/crafti#7 (comment)](https://github.com/Vogtinator/crafti/issues/7#issuecomment-696315733)

I tried it, the results are in the crafti issue you mentioned

**Comment by chenxi050402** [comment]
It works, you just need to spam enter when opening an app

**Comment by FerdinandoPH** [comment]
Gpsp worked with me when doing that

**Comment by nickycheezo** [comment]
When I open the Ndless installer nothing happens it’s just a white screen with the text Ndless for OS 5.2.0.771

**Comment by chenxi050402** [comment]
> When I open the Ndless installer nothing happens it’s just a white screen with the text Ndless for OS 5.2.0.771

reboot the calculator and don't create or open any document before opening the installer

**Comment by adriweb** [comment]
it may take up to 10s when the clock is spinning.

**Comment by nickycheezo** [comment]
Still not installing

**Comment by Atrate** [comment]
I've seen an issue where Ndless installs succesfully but fails to show up in the status bar as installed — all the ndless-utilizing programs work, there is just no text saying "ndless is installed".

**Comment by adriweb** [comment]
Yes after a few refresh/display of the home screen the text is gone, it's [a feature, not a bug](https://github.com/ndless-nspire/Ndless/commit/06f2ebb9fee8d6c5829a8bba8fbd1f0a2ded4728) (see the commit message at the top for the explanation).

You can try to launch the `ndless_resources.tns` file to see if Ndless is installed (if it is installed, it will ask you if you want to uninstall it or not).

Remember that as long as the calc doesn't crash/reset, Ndless will still be there, regardless of the status text on the homescreen.

**Comment by adriweb** [comment]
> Still not installing

Can you tell which datecode/revision your calculator is? Same as above, it's the few characters on the back, next to the serial number. Looks like `N-0320AK`.

**Comment by nickycheezo** [comment]
It’s because my calculator is running 5.1.0.177 
How do I update my calculator

**Comment by FerdinandoPH** [comment]
> It’s because my calculator is running 5.1.0.177
> How do I update my calculator
Download the os from here: https://education.ti.com/en/software/search
Then download the ti software program which you will also find on the webpage and use it to install the OS

**Comment by FerdinandoPH** [comment]
Ok, so I have tried executing some programs spamming enter, and most of them will open (however, you ha e to do it very quickly or else the compatibility pop up will appear an then the calculator will crash.

So the final to-fix bug list for the n0320AK would be:
1: Having to spam enter to have a chance to open any ndless app

2: Touchpad not working at all when using any ndless app

3: Calculator crashing after trying to open any ndless app for the second time after pressing the reset button

I hope this list is helpful, @adriweb @Vogtinator

**Comment by adriweb** [comment]
@Vogtinator was able to identify the technical differences regarding the touchpad, he's working on a fix, including (first) for Firebird in order to better handle the hardware differences.

**Comment by Vogtinator** [comment]
Got emulation working and implemented compatibility in Ndless. Please try the tns from #236.

**Comment by lights0123** [comment]
Do you mean #241?

**Comment by Vogtinator** [comment]
Yes, copy-paste error.

**Comment by FerdinandoPH** [comment]
Awesome! All the problems I listed a few days ago are no longer there after using the resource file you posted. You killed 3 birds with one stone! 
Thank you so much, Ndless is way more usable now!

**Comment by Ti64CLi** [comment]
I have been contacted by someone having troubles using gpsp. It was freezing the calc each time he launched it. It came up that he was using a Nspire CX II-T N-0320L.
So Adriweb told me to give him a new version of the ndless_ressources.tns, this one : https://github.com/ndless-nspire/Ndless/files/5286710/ndless_resources.zip
Since it fixed the problem, I write this to let you know, as Adriweb gave me the advice ;)
