### ISSUE TITLE
SDK compiling issues

### ISSUE THREAD

**Issue by FerdinandoPH** [ndless-nspire/Ndless#238]
I'm trying to install the SDK in order to try the latest version from the git apps, but when I try compiling the sdk, an error appears saying:
`make: se entra en el directorio '/home/ferdinandoph/Ndless/ndless-sdk'
make -C libsyscalls
make[1]: se entra en el directorio '/home/ferdinandoph/Ndless/ndless-sdk/libsyscalls'
arm-none-eabi-gcc -mcpu=arm926ej-s -std=c11 -nostdlib -O3 -fPIE -mlong-calls -Wall -Werror -I ../include/ -I ../thirdparty/nspire-io/include/ -D_TINSPIRE -ffunction-sections -fdata-sections -c realpath.c -o realpath.o
realpath.c: In function 'realpath1':
realpath.c:50:12: error: 'PATH_MAX' undeclared (first use in this function); did you mean 'RAND_MAX'?
  char left[PATH_MAX], next_token[PATH_MAX];
            ^~~~~~~~
            RAND_MAX
realpath.c:50:12: note: each undeclared identifier is reported only once for each function it appears in
realpath.c:50:23: error: unused variable 'next_token' [-Werror=unused-variable]
  char left[PATH_MAX], next_token[PATH_MAX];
                       ^~~~~~~~~~
realpath.c:50:7: error: unused variable 'left' [-Werror=unused-variable]
  char left[PATH_MAX], next_token[PATH_MAX];
       ^~~~
realpath.c: In function 'realpath':
realpath.c:159:25: error: 'PATH_MAX' undeclared (first use in this function); did you mean 'RAND_MAX'?
   m = resolved = malloc(PATH_MAX);
                         ^~~~~~~~
                         RAND_MAX
cc1: all warnings being treated as errors
make[1]: *** [Makefile:21: realpath.o] Error 1
make[1]: se sale del directorio '/home/ferdinandoph/Ndless/ndless-sdk/libsyscalls'
make: *** [Makefile:13: build-libsyscalls] Error 2
make: se sale del directorio '/home/ferdinandoph/Ndless/ndless-sdk'`

It seems as a problem in the source files. How can I fix it?

**Comment by adriweb** [comment]
is your PATH env var correctly setup? https://github.com/ndless-nspire/Ndless/issues/144. Along the way you might need to install some deps.

Basically, `git clone --recursive` the repo, then go inside ndless-sdk/toolchain, then launch build_toolchain.sh. Once done, follow the instructions at the end (about the PATH env var). Then launch another terminal, make sure PATH is ok, then do `make` in the ndless-sdk folder.

**Comment by FerdinandoPH** [comment]
I think that my PATH is correctly set up, but I'm not sure. What do you mean by deps?
I will add some photos so you can see my path and the error in a more organised way
![Captura de pantalla de 2020-09-22 09-38-43](https://user-images.githubusercontent.com/29411787/93855527-ec2fed00-fcb7-11ea-82a9-468da693f3e7.png)

**Comment by adriweb** [comment]
I meant dependencies.

But anyway, I'm not sure what's going on.

Another arm compiler got invoked? If you do that, what does it say: `which arm-none-eabi-gcc`

@Vogtinator any idea?

**Comment by FerdinandoPH** [comment]
Excuse me, but I am a rookie and this is my first time compiling something, so could you please explain what does the arm compiler invokes and the which arm none wabi gcc mean?

**Comment by Vogtinator** [comment]
The PATH looks good. In addition to `which arm-none-eabi-gcc`, what's the output of `find . -name limits.h`?

**Comment by adriweb** [comment]
No worries. 

When you launch this command in the terminal, when you are in the ndless-sdk folder, what does it say?

`which arm-none-eabi-gcc`

Also did the `build_toolchain.sh` script run successfully? I assume yes and that's where you got the PATH things from.

**Comment by FerdinandoPH** [comment]
The build tool chain sh worked fine. I will try executing the which arm command when I'm back from school

**Comment by FerdinandoPH** [comment]
![Captura de pantalla de 2020-09-22 21-27-58](https://user-images.githubusercontent.com/29411787/93928444-9e989c00-fd1a-11ea-9d0c-fb6d52b52b2c.png)
This is the output I got

**Comment by lights0123** [comment]
That's not the correct compiler path. Does the file `arm-none-eabi-gcc` exist within `/home/ferdinandoph/Ndless/ndless-sdk/toolchain/install/bin`?

**Comment by Vogtinator** [comment]
If you run `build_toolchain.sh` (will finish quickly), what does it say? My guess is that something with `$PREFIX` is odd.

**Comment by FerdinandoPH** [comment]
![Captura de pantalla de 2020-09-22 22-13-46](https://user-images.githubusercontent.com/29411787/93933064-63e63200-fd21-11ea-8460-a6d846ea3954.png)
this is what I get after running the toolchain. How do I check if the file arm none eabi exists within the toolchain folder?

**Comment by Vogtinator** [comment]
Something is overriding $PREFIX for some reason. `env` would show that.

However, if you prepend what it says in the last line of the output to your `PATH`, it might actually work.

**Comment by FerdinandoPH** [comment]
How do I do that?

**Comment by FerdinandoPH** [comment]
Nevermind, I solved the problem. It seems that I accidentally changed the Prefix location of the build toolchain.sh, so the arm none eabi gcc was not found. Then, when I was told that the arm non eabi gcc was not found, I installed it myself with apt get, and that's why it didn't work.
I fixed, and it seems it has worked.

**Comment by FerdinandoPH** [comment]
Just some quick questions before closing this:
1: In the tutorial, ( https://hackspire.org/index.php/C_and_assembly_development_introduction ), you need many lines of code to compile the program:
`$ make
nspire-gcc -Wall -W -marm -Os -c hello-sdl.c
mkdir -p .
nspire-ld hello-sdl.o -o ./helloworld-sdl.elf 
genzehn --input ./helloworld-sdl.elf --output ./helloworld-sdl.tns --name "helloworld-sdl"
make-prg ./helloworld-sdl.tns ./helloworld-sdl.prg.tns`

For other programs (such as, for example crafti), how do I know what commands do I have to execute? Is it told in some file? Or do I have to figure it out myself?

2: When a new SDK version is released, how do I update the SDK?

**Comment by lights0123** [comment]
@FerdinandoPH 

> you need many lines of code

no you don't. That's showing the *output* of `make`—`make` runs all those commands for you. You just need to run `make` to build most projects.

> When a new SDK version is released, how do I update the SDK?

For changes not affecting the compilers (not a GCC upgrade), run `make` in the top level after `git pull && git submodule update --recursive --remote`ing. I've always deleted and re-cloned when there was a compiler upgrade.

**Comment by FerdinandoPH** [comment]
I tried to compile crafti, but I get an error saying: go.h not found. Does anyone know how to fix that?

**Comment by lights0123** [comment]
https://stackoverflow.com/a/4438292

You probably want the last code block

**Comment by FerdinandoPH** [comment]
Sorry, I meant gl.h

**Comment by lights0123** [comment]
Yeah, that's in the nGL submodule. You need to run one of those commands I linked—look in the `nGL` directory and make sure that there's something there.

**Comment by FerdinandoPH** [comment]
Ok, thanks. I'll try it as soon as I arrive to my home

**Comment by FerdinandoPH** [comment]
It sais that the repository is not found

**Comment by FerdinandoPH** [comment]
Any other way to do it?

**Comment by adriweb** [comment]
Did you follow the steps here? https://github.com/ndless-nspire/Ndless/issues/238#issuecomment-696997547

**Comment by FerdinandoPH** [comment]
> https://stackoverflow.com/a/4438292 You probably want the last code block
> […](#)
> On Sep 23, 2020, at 7:32 AM, FerdinandoPH ***@***.***> wrote: ﻿ I tried to compile crafti, but I get an error saying: go.h not found. Does anyone know how to fix that? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

I meant that, when trying to use the commands from this webpage, I will get an error saying: repository not found

**Comment by FerdinandoPH** [comment]
Ok, so I finally figured out how to download the nGL library, but now there is a new error
`nGL/gldrawarray.cpp:145:15: error: exception handling disabled, use ‘-fexceptions’ to enable
  145 |         throw "Not implemented";
`
Any clues on how to fix this one?

**Comment by FerdinandoPH** [comment]
![Captura de pantalla de 2021-01-07 21-28-45](https://user-images.githubusercontent.com/29411787/103941600-65e8cb00-512f-11eb-854b-698d82145210.png)

**Comment by Vogtinator** [comment]
That's something I fixed a while ago, but apparently never pushed. I just did that: https://github.com/Vogtinator/nGL/commit/1f810f8c11cd6d89d20ab65502222caafc857987

**Comment by FerdinandoPH** [comment]
It finally worked!! thank you so much for your help!
