### ISSUE TITLE
When I play GBA or GBC/GB roms on CX IIT CAS, there would be a screen glitch: multiple short black and white parallel lines across the middle of the screen.

### ISSUE THREAD

**Issue by anoopsk** [ndless-nspire/Ndless#239]
Also at gbc4nspire emulator, I can't turn the brightness down, and can't turn off the green screen mode.

**Comment by anoopsk** [comment]
![IMG_20200923_160106](https://user-images.githubusercontent.com/65862092/94032226-a3f7f400-fdb7-11ea-948c-3befc0964345.jpg)

**Comment by anoopsk** [comment]
![IMG_20200923_160132](https://user-images.githubusercontent.com/65862092/94032302-b96d1e00-fdb7-11ea-953d-0530a8951ec9.jpg)

**Comment by Vogtinator** [comment]
That's an artifact of the lcd compatibility mode which for some reason disappears after a while. Restarting the application might help.

**Comment by anoopsk** [comment]
How else can I turn the brightness of calc's screen down. That function does not work on gbc4nspire on this unit, but it worked on the CX I

**Comment by Vogtinator** [comment]
Does it not work if you do it before starting gbc4nspire?

**Comment by anoopsk** [comment]
It does work (still too bright), but gbc4nspire has its own brightness feature where the brightness can go extremely low.

**Comment by anoopsk** [comment]
The brightness feature can be controlled by + and - buttons on gbc4nspire, which worked on my CX I but not CX II

**Comment by Vogtinator** [comment]
The brightness can be controlled by writing to 0x90130014: https://hackspire.org//index.php?title=Memory-mapped_I/O_ports_on_CX_II#90130000_-_Unknown_Controller_for_the_LCD_Backlight

It would just have to be implemented in gbc4nspire, but that's not that simple as the source code was lost.

Closing as this is not an issue with Ndless itself.
