### ISSUE TITLE
5.2 won't install on CX II CAS

### ISSUE THREAD

**Issue by Dinoway** [ndless-nspire/Ndless#242]
I have been waiting for months for 5.2 to come out and I was very excited when I saw that ndless has released the new version. I followed the instructions and ran the installation program. The calculator restarted and booted back up. I checked the version, and it is still using 5.1.3.73. I went to run the installer again, because I saw that some people were saying you need to run it multiple times for it to install correctly. Well when I open the installation program again, it will just sit there and do nothing. I wondered if the file was broken, so I uninstalled all of the ndless files off of the calculator and reinstalled it from online and reinstalled the files onto the calculator. Same result. I do notice that when I open up doc menu, the key responses are extremely slow, so I assume it is doing something.

**Comment by lights0123** [comment]
> I checked the version, and it is still using 5.1.3.73.

So you're not running OS 5.2? The ndless installer installs _ndless_ on OS 5.2, not OS 5.2 itself. Get that from TI first.

**Comment by adriweb** [comment]
You know you need OS 5.2 and yet you have OS 5.1.3... why aren't you installing OS 5.2?
