### ISSUE TITLE
Ndless not actually installing 5.2.0.771

### ISSUE THREAD

**Issue by Danke-Boi** [ndless-nspire/Ndless#243]
When I followed the directions to install ndless, I created a new folder named ndless, moved ndless-installer.tns to the folder (or whatever its called) then I hit execute, the little clock icon went for a while, but when I left it alone to finish, then came back, the Ndless activated thing in the top right wasn't there, but the calculator was on the homepage. So I executed it again, and it was on a black screen that wouldn't turn on for a while until it finally turned back on after I hit the on button. (it turned off while plugged in?) still without the ndless activated thing.
What is going on? should I be worried? Is the CAS feature messing anything up? My calculator is a TI-nspire cx _ii_ CAS, and the ndless folder is in My Documents, If that isn't the right folder, how do I make a folder outside of the My Documents folder?

**Comment by Vogtinator** [comment]
>  I created a new folder named ndless, moved ndless-installer.tns to the folder (or whatever its called) then I hit execute,

Did you also transfer `ndless_resources.tns`?

**Comment by Danke-Boi** [comment]
I didn’t see that in the folder that I downloaded. I’ll look right now.
Thanks for responding so quickly.  Anyways, when I tried copying over a
folder (crafti) it said only .tns files were allowed will that be fixed
when I install ndless? In the folder there was a lot of important stuff for
the game including rendering programs. And I can’t find instructions on how
to install it. If you can find some, or know where to look could you let
me know? Thanks!

**Comment by Vogtinator** [comment]
Only the `.tns` files can be sent to the calc, but you don't need any of the others.

**Comment by Danke-Boi** [comment]
Thanks for being patient with me, I see it now. Here’s hoping it works!

**Comment by Danke-Boi** [comment]
Alright, so I copied over the resources.tns thing, and it hasn't worked. It
is doing the exact same thing. Do I need to delete both files and copy them
both back to the calculator?

**Comment by Danke-Boi** [comment]
I used the student software to open it on my computer, and when it sent the file over, ndless said it was installed; however, the little Ndless installed thing was there for less than a second, and I cannot run it again to install. Did I screw things up? Or is this what is supposed to happen?

**Comment by lights0123** [comment]
If you attempt to run ndless_resources.tns, and get a popup asking if you'd like to uninstall, you did it correctly.

**Comment by Danke-Boi** [comment]
I ran crafti, and ndless ran in completely stability mode, so it seems to
work now. Thanks!

**Comment by Danke-Boi** [comment]
Completely? COMPATIBILITY! Sorry if that previous thing makes no sense. It's solved, thanks!
