### ISSUE TITLE
Touchpad not working on TI-nspire CX II CAS

### ISSUE THREAD

**Issue by mimounsuperstar** [ndless-nspire/Ndless#244]
Hello!
I recently installer Ndless r2016 (the latest version) on my TI-nspire CX II CAS and the touchpad isn't working on Ndless apps.
(I've tried with GBC4NSPIRE and Mini vMac so far, and every time I try to use it, I only goes on the left for every button and the mouse isn't detected on Mini vMac).
Is it an issue with my calculator or with the apps that I'm using?

(The trackpad is working correctly on the TI software tho)

**Comment by Facts-and-Logic** [comment]
What's your calculator model?

**Comment by Vogtinator** [comment]
Which hardware revision is that? If it's less than AK, please try r2015.

**Comment by Facts-and-Logic** [comment]
I can confirm that ndless r2016 works perfectly on my N-0719AH.

**Comment by mimounsuperstar** [comment]
> What's your calculator model?

I have the N-1119AI

**Comment by mimounsuperstar** [comment]
> Which hardware revision is that? If it's less than AK, please try r2015.

My calculator is the N-1119AI one and every time I open an app with the r2015 it freezes

**Comment by Facts-and-Logic** [comment]
Which app were you trying to open?

**Comment by mimounsuperstar** [comment]
> Which app were you trying to open?

gbc4nspire

**Comment by mimounsuperstar** [comment]
> > Which app were you trying to open?
> 
> gbc4nspire

it works fine on r2016 tho

**Comment by Facts-and-Logic** [comment]
Did you download gbc4nspire from TI-Planet?
Here is the link: https://tiplanet.org/forum/archives_voir.php?id=1649
It has added support for HW-W+ screens. If you got it from ticalc, then its probably the old unsupported version.

**Comment by mimounsuperstar** [comment]
> Did you download gbc4nspire from TI-Planet?
> Here is the link: https://tiplanet.org/forum/archives_voir.php?id=1649
> It has added support for HW-W+ screens. If you got it from ticalc, then its probably the old unsupported version.

yup it was from ti-planet

**Comment by adriweb** [comment]
> > > Which app were you trying to open?
> > 
> > 
> > gbc4nspire
> 
> it works fine on r2016 tho

Well then what's the issue?
You have to have the latest version yes, which is currently r2016.

**Comment by mimounsuperstar** [comment]
> > > > Which app were you trying to open?
> > > 
> > > 
> > > gbc4nspire
> > 
> > 
> > it works fine on r2016 tho
> 
> Well then what's the issue?
> You have to have the latest version yes, which is currently r2016.

The touchpad isn't correctly working with r2016

**Comment by adriweb** [comment]
You said "it works fine on r2016 tho". Did you mean r2015?

Or did it work before (2015) and not now (2016)?

**Comment by mimounsuperstar** [comment]
> You said "it works fine on r2016 tho". Did you mean r2015?
> 
> Or did it work before (2015) and not now (2016)?

I apologize if I wasn't really clear... The r2015 doesn't work at all (it freezes when launching an app). The r2016 works fine, except for the touchpad. The others buttons are working well tho.

**Comment by Danke-Boi** [comment]
I have gbc4nspire, and none of the games need trackpad, try getting crafti
from the ndless website, and play it using the trackpad. If it doesn’t
work, then you have a problem. But otherwise, the games just don’t have
trackpad support. That made sense right?

**Comment by Danke-Boi** [comment]
Try playing a trackpad game, something designed for trackpad specifically, like crafti, or nquake. If it works then, then you don’t have a problem, if not, then you have an issue. I suggest crafti.

**Comment by Vogtinator** [comment]
> every time I try to use it, I only goes on the left for every button

Sounds like the touchpad is detected and has some effect, but every press has a too low X coordinate.

Please try the program from https://github.com/Vogtinator/crafti/issues/7#issuecomment-696315733 and provide the values it shows when pressing the left and right buttons.
