### ISSUE TITLE
Ndless Emulators Don't Work For Ndless 5.2?

### ISSUE THREAD

**Issue by raymondyao9056** [ndless-nspire/Ndless#246]
I think I successfully downloaded ndless on my TI-nspire CX II, but whenever I try to run an emulator (such as GBA or GBC), all it tells me is that "This document format is not supported". Is this supposed to be like this, or am I just stupid and doing something wrong? Thanks!

**Comment by Vogtinator** [comment]
If running `ndless_resources` also fails, ndless was not installed correctly.

**Comment by raymondyao9056** [comment]
is that the ndless_resources.tns thing?

**Comment by Vogtinator** [comment]
Yes.

**Comment by raymondyao9056** [comment]
oh, okay that did fail, but im really not sure what I did wrong?

**Comment by adriweb** [comment]
Yes, launching `ndless_resources.tns` will allow you to determine for sure if Ndless is actually installed: if it is, there will be a popup asking you whether you want to uninstall Ndless (i.e. reboot the calc).

Make sure to correctly follow the install tutorial?

Also, what's your calculator datecode? On the back of the calc, to the right of the serial number, if should be a few characters like 'M-1234XX'.

**Comment by raymondyao9056** [comment]
Wow, you guys reply fast! My calculator code is M-0419AH

**Comment by raymondyao9056** [comment]
Ok, thanks, I ended up getting ndless to work, but one more question: Is anyone in charge of the ndless apps website? I just downloaded the Pokemon Mini game, and it loaded up on my calculator, but now there's a screen that says "no cart"?

**Comment by Vogtinator** [comment]
Whoever is responsible for the website isn't the developer of most of the applications on it, so you'd have to ask someone else anyway. For Pokemon Mini see https://tiplanet.org/forum/viewtopic.php?t=16410.
