### ISSUE TITLE
Nespire won't work on ti nspire cx II calculators

### ISSUE THREAD

**Issue by FerdinandoPH** [ndless-nspire/Ndless#247]
When I try to open it, nothing happens. I have seen a photo of the compatibility chart, and it seems that the tns file needs to be patched. Where can I find the patch?

**Comment by Facts-and-Logic** [comment]
What calculator OS do you have? Also, have you transferred "ndless_resources.tns" into the same folder as the installer?

**Comment by FerdinandoPH** [comment]
5.2.0.771. The resources folder is in the same folder as the installer, and many other apps work fine

**Comment by Vogtinator** [comment]
Try this: [NESpire_031.zip](https://github.com/ndless-nspire/Ndless/files/5373574/NESpire_031.zip)

**Comment by FerdinandoPH** [comment]
Ok, so it does open now, but the touchpad does not work at all. My calculator's model is N-0320AK, so that might be the problem

**Comment by Vogtinator** [comment]
Looks like nespire calls `touchpad_read(0x02, 0x0A, ...)` but ndless only implements `0x00, 0x0A` in the compatibility code. Try this: [ndless_resources.zip](https://github.com/ndless-nspire/Ndless/files/5373667/ndless_resources.zip)

**Comment by FerdinandoPH** [comment]
Great! It works fine now! Thank you once again!
