### ISSUE TITLE
'make' giving some erros on linux

### ISSUE THREAD

**Issue by Hugoverissimo21** [ndless-nspire/Ndless#252]
Hi, whenever i run make i got this errors:

`make[2]: *** [Makefile:18: stdlib.o] Error 1
make[2]: Leaving directory '/home/hugo/Project-Zebra/ndless-sdk/libsyscalls'
make[1]: *** [Makefile:14: build-libsyscalls] Error 2
make[1]: Leaving directory '/home/hugo/Project-Zebra/ndless-sdk'
make: *** [Makefile:19: build-ndless-sdk] Error 2
`
Any help please?

**Comment by debrouxl** [comment]
The actual error is above that. In the output you copied, all that appears is that building stdlib.o triggers a failure, but there's no clue why :)

Also, you didn't mention which distro, version and processor architecture you're using.

**Comment by Hugoverissimo21** [comment]
Just runned make clean and then make and this is what appears after run make:
`stdlib.cpp: In function 'int _stat(const char*, stat*)':
stdlib.cpp:286:6: error: 'struct stat' has no member named 'st_atime'; did you mean 'st_atim'?
  st->st_atime = nuc_st.st_atime;
      ^~~~~~~~
      st_atim
stdlib.cpp:287:6: error: 'struct stat' has no member named 'st_mtime'; did you mean 'st_mtim'?
  st->st_mtime = nuc_st.st_mtime;
      ^~~~~~~~
      st_mtim
stdlib.cpp:288:6: error: 'struct stat' has no member named 'st_ctime'; did you mean 'st_ctim'?
  st->st_ctime = nuc_st.st_ctime;
      ^~~~~~~~
      st_ctim
stdlib.cpp: In function 'char* get_current_dir_name()':
stdlib.cpp:473:45: error: 'PATH_MAX' was not declared in this scope
  char *buf = reinterpret_cast<char*>(malloc(PATH_MAX));
                                             ^~~~~~~~
stdlib.cpp:473:45: note: suggested alternative: 'INT8_MAX'
  char *buf = reinterpret_cast<char*>(malloc(PATH_MAX));
                                             ^~~~~~~~
                                             INT8_MAX
make[2]: *** [Makefile:18: stdlib.o] Error 1
make[2]: Leaving directory '/home/hugo/Project-Zebra/ndless-sdk/libsyscalls'
make[1]: *** [Makefile:14: build-libsyscalls] Error 2
make[1]: Leaving directory '/home/hugo/Project-Zebra/ndless-sdk'
make: *** [Makefile:19: build-ndless-sdk] Error 2`
It appears other stuff before but i guess this is what matters...
btw, Im using kali linux terminal

**Comment by Vogtinator** [comment]
Same as https://github.com/ndless-nspire/Ndless/issues/144. Make sure the toolchain was fully built and $PATH is correct.
