### ISSUE TITLE
Will DeSmuME ever be ported to the TI-Nspire using the Ndless SDK?

### ISSUE THREAD

**Issue by logantischler0** [ndless-nspire/Ndless#253]
I've played every Pokémon GBA game on my TI-Nspire CX II CAS using Ndless and gpSP-Nspire. I was wondering if a Nintendo DS emulator would be possible to port to the TI-Nspire (Possibly DeSmuME). If not, how would I go about porting DeSmuME to the TI-Nspire myself?

Thank you in advance.

**Comment by adriweb** [comment]
pinging @gameblabla, he likes porting emus to the Nspire...

**Comment by gameblabla** [comment]
Desmume would ever work for very small games and even then, it still would be very slow. GBA games don't even run that well btw... Maybe a port of Drastic could run better once it becomes open source but so far, nothing.
Of course the small NAND space rules out some games like Pokemon Black 2.

The port is possible but it would be pointless and run at 2 FPS at best. Why bother ?
Also, if you want me to port things, someone would need to send me a CXII CAS so i sold my CX 1 year ago or so.

**Comment by adriweb** [comment]
Actually, GBA runs very well on the CX II now :)

**Comment by gameblabla** [comment]
> Actually, GBA runs very well on the CX II now :)

Good to know i guess, although i still think that it wouldn't run intensive games like Doom 2 GBA very well. (that game doesn't even run that well on the RS-97)

**Comment by logantischler0** [comment]
Is it possible, @gameblabla, to attempt to port any existing Nintendo DS emulators to the TI-Nspire, at the moment?

**Comment by logantischler0** [comment]
Also, which existing Nintendo DS emulators are currently open-source?

**Comment by adriweb** [comment]
Well he's saying it might be technically possible, but even if it ends up compiled correctly etc. for the CX II, it wouldn't run anything correctly, pretty much, it'd be way, way too slow. That's also what I believed.

Regarding Doom II GBA, I tried for a few seconds, here's what it looks like: https://drive.google.com/file/d/1g4x5T0mCoH2lhLKao8j5KtAfdB0iRuK1/view?usp=sharing

**Comment by logantischler0** [comment]
Is there any way I could collaborate with @gameblabla to try to create a Nintendo DS emulator that is optimized for performance? I would really like to see the TI-Nspire emulate the [almost] impossible.

**Comment by Danke-Boi** [comment]
I have doom on my ti nspire cx2 cas, and it runs fine, a game that doesn’t
however is top gear rally for the gba. You have to turn on frameskipping.

**Comment by Vogtinator** [comment]
Let's close this issue here as it's not directly about Ndless itself, but feel free to continue discussion in the closed issue.
