### ISSUE TITLE
Ndless monitor app?

### ISSUE THREAD

**Issue by logantischler0** [ndless-nspire/Ndless#254]
Is there any Ndless app that lets the TI-Nspire behave like a monitor, maybe with HDMI?

**Comment by Danke-Boi** [comment]
I’m no expert, but that sounds like a hardware thing to me.

**Comment by Vogtinator** [comment]
Not that I'm aware of. It would probably be possible to achieve that by writing some custom USB gadget functionality, or simpler (but slower) using NavNet.

What's your use case?

**Comment by Danke-Boi** [comment]
Although theoretically if there were an app for this, it could possible
work (via the usb) it is unlikely to exist, and you would need the
accompanying app on the device you sent the signal from.

**Comment by logantischler0** [comment]
I would like to access my Windows computer that I own, but I lack a monitor, but I do own a TI-Nspire CX II CAS. What is NavNet?

**Comment by Vogtinator** [comment]
Oh, that wouldn't be any fun to use with 320x240px resolution. If you have a smartphone, there are some RDP clients.

**Comment by logantischler0** [comment]
I only have a flip phone with an even smaller display than my TI-Nspire....

**Comment by Danke-Boi** [comment]
What graphics are you using?

**Comment by logantischler0** [comment]
If I remember correctly, it is Intel graphics.

**Comment by Danke-Boi** [comment]
Do you have a tv? If so use that.

**Comment by logantischler0** [comment]
I don't.

**Comment by Danke-Boi** [comment]
How are you accessing this thread then.

**Comment by logantischler0** [comment]
My flip phone.

**Comment by Danke-Boi** [comment]
What Fabian said is your best bet. There are apps that let you use your
phone as a monitor.

**Comment by logantischler0** [comment]
Okay, thank you.

**Comment by Vogtinator** [comment]
Yeah, I don't think Ndless can help here unfortunately.
