### ISSUE TITLE
gpsp games (not gpsp itself) hardlocks and/or crashes sometimes

### ISSUE THREAD

**Issue by RuralAnemone** [ndless-nspire/Ndless#256]
* note: I'm using a TI-nspire CX II on version 5.2.0.771
I got gpsp here, I don't know if there's a new version that I should be using...: https://artofproblemsolving.com/community/c726379h1709307_gpspnspire_gameboy_advance_emulator

Sometimes, when I'm playing a game on gpsp, the game completely stops. I can go to the gpsp menu and exit/reset the game, but it still stops at the same spot.

Here are the places I've noticed it stopping: (also, these are the only games I currently have - I'm planning to transfer more soon)

1. Mario & Luigi Superstar Saga: when you confront an enemy for battle (not a "tutorial" battle, just a regular one), it seems like this is the frame when it loads the battle...? I've tried changing lots of things, but nothing (so far) has worked
and
2. One time I got hardlocked on Super Mario Advance 3 - Yoshi's Island right before the "game over" screen. The only thing I could do was restart my calc.

Also, I can't re-configure the keybinds, gpsp just hardlocks and I have to reset my calc.

**Comment by logantischler0** [comment]
Re-configuring the keybinds doesn't work for me, either. I have to press the reset button on the back of the calulator, too.

**Comment by RuralAnemone** [comment]
Also, I should probably define hard vs softlocks.
Softlocks are when the game is kind of playable, but you can't do anything to get out of the glitchy state
Hardlocks are when the game completely freezes

For me, superstar saga hardlocks, but I can still access gpsp.
When I try to re-configure the keybinds, gpsp itself hardlocks


Also, I get this message whenever I boot gpsp:
![IMG_20201116_140816](https://user-images.githubusercontent.com/64103005/99302629-40b59b80-2815-11eb-8a8f-23492b825101.jpg)

I'm wondering if gpsp has an update...?

**Comment by RuralAnemone** [comment]
Maybe these are the "weird issues"

**Comment by adriweb** [comment]
More reports here: https://tiplanet.org/forum/viewtopic.php?f=15&t=24408

**Comment by RuralAnemone** [comment]
and if you care, here's an example of a softlock (not in gpsp though): https://youtu.be/7rPdbTaBrBQ?t=780
there's no way out of this besides quitting and restarting

again, with a hardlock, you have to turn everything off and back on again (which is what the calc's restart button does)

**Comment by RuralAnemone** [comment]
Does anyone know of a gpsp update?

**Comment by adriweb** [comment]
Nope, although @Vogtinator may have a fork to test some things.
It may have to be debugged on the emu first though

**Comment by Vogtinator** [comment]
The hard lockup when rebinding is the usual issue with a hardcoded address for the On key. I fixed it, build with the latest toolchain (more optimizations and doesn't require gpsp_resources anymore) is attached: [gpsp.zip](https://github.com/ndless-nspire/Ndless/files/5568928/gpsp.zip)

**Comment by RuralAnemone** [comment]
Thanks, I'll try it out!
I'll close when I've confirmed that it works

**Comment by Facts-and-Logic** [comment]
Here's the summary of the new gpsp build:
- Games run slower
- Loading a save freezes the program and a restart is required (I was loading a save from the previous version of gpsp)
- Key rebinds work
- The time it takes to launch gpsp is slightly shorter.

**Comment by RuralAnemone** [comment]
@Facts-and-Logic you tried this on a CX-II, right?

**Comment by Vogtinator** [comment]
> Games run slower

That's surprising. This was built with much more optimizations and a newer toolchain. Here I don't see any difference in speed.
I added some caching for `on_key_pressed` here, maybe that helps? [gpsp.zip](https://github.com/ndless-nspire/Ndless/files/5575826/gpsp.zip)

> Loading a save freezes the program and a restart is required (I was loading a save from the previous version of gpsp)

Yeah, that might not work, the savestate layout probably changed.

**Comment by RuralAnemone** [comment]
> * Loading a save freezes the program and a restart is required (I was loading a save from the previous version of gpsp)
Save meaning savestate?

**Comment by RuralAnemone** [comment]
as opposed to what would normally happen on a real gamboy

**Comment by RuralAnemone** [comment]
Also, what do you mean by game runs slower? What is slower?

- the framerate
- the input delay
- or something else...?

**Comment by Facts-and-Logic** [comment]
I'll clear some things up here:
- Games run slower
The framerate is lower so the game doesn't run as smoothly. Its like as if I downgraded my CX II to a CX I.
- Saves don't work
I was supposed to say savestates. Its where you press S to create one and L to load one. Actual game saves have not been tested yet.

Everything I test is on a CX II CAS running 5.2.0.771. Model is N-0719AH.
I'll post an update on the newest build tonight.

**Comment by Facts-and-Logic** [comment]
My results of the new build:
MD5 (zip): `FD856F29128F353144CDB8E59AA32131`

- Games still run slowly (lower framerates, gameplay is choppy)
Games tested: Advanced Wars 2, Rayman Advance, Mario Kart Super Circuit
- One game stopped working during startup (Super Mario Advance 3). It froze my calculator and had to restart it. Before it stopped responding, I saw the game boy startup animation. 
- Saves DO work, NOT savestates. (it bricks your calculator).
- Key rebinds works

Verdict: Stick to the original working build.

Tested with ndless r2016. For calculator specs, see above post.

**Comment by Vogtinator** [comment]
> MD5 (zip): FD856F29128F353144CDB8E59AA32131

Matches.

> Games still run slowly (lower framerates, gameplay is choppy)

Can't confirm. On hardware, it feels like it's running at least as fast as before. There are reports that the CPU clocks slower depending on whether it's connected via USB or not, maybe that's the case here.

> One game stopped working during startup (Super Mario Advance 3). It froze my calculator and had to restart it. Before it stopped responding, I saw the game boy startup animation.

Worked fine here.

> Saves DO work, NOT savestates. (it bricks your calculator).

Both work fine here...

**Comment by RuralAnemone** [comment]
So... in the new version, savestates work (as well as normal states), games still run fine, and keybinds work...?

**Comment by RuralAnemone** [comment]
> One game stopped working during startup (Super Mario Advance 3). It froze my calculator and had to restart it. Before it stopped responding, I saw the game boy startup animation.

That happens to me sometimes too (on the original gpsp, and only with that game, but I savestate a lot so it doesn't really matter)

**Comment by adriweb** [comment]
Yes, please test with and without USB plugged in, see if you see any difference in speed (and report how much of a difference you see if possible?)

**Comment by Facts-and-Logic** [comment]
Ok, this is weird. Unplugging the USB cable from my calculator fixed everything for me. It runs at full speed and all my games work.

Correction: I shouldn't have mentioned savestates because I was loading it from the old version.

Verdict: The new build is better.

**Comment by RuralAnemone** [comment]
Alright then
I'll mark this a closed!

**Comment by RuralAnemone** [comment]
Thank you guys so much for your help!

**Comment by RuralAnemone** [comment]
Okay, here's what I've found with the new version:
Games take a bit longer to load
Keybinds work
Superstar Saga still softlocks at the same frame
