### ISSUE TITLE
File transfer from chromebook to calc

### ISSUE THREAD

**Issue by RuralAnemone** [ndless-nspire/Ndless#259]
I guess this isn't an issue, but I'd like to have a way to transfer files from my Chromebook (Acer C733, can't install Linux/dev mode for some reason) to my calculator (TI-Nspire CX II)...

I found this app for chrome, but it's for the TI-84, so...
https://chrome.google.com/webstore/detail/ti-connect-ce-app-for-chr/aokihcpccmdjjkebakdanncddpdnkfla/
I was wondering if anyone knew of a chrome app that I could get so that I could connect to my Nspire calc.

I hope that all made sense

**Comment by lights0123** [comment]
https://n-link.lights0123.com/

**Comment by lights0123** [comment]
wait actually I think the web version has unresolved issues with the CX-II, but I can take a look at fixing them again

**Comment by RuralAnemone** [comment]
I'll still try it

**Comment by RuralAnemone** [comment]
thanks for finding this for me!

**Comment by lights0123** [comment]
> finding this

well, more like making it :D

**Comment by RuralAnemone** [comment]
oh really nice

**Comment by RuralAnemone** [comment]
yeah it's stuck on the loading animation

**Comment by lights0123** [comment]
Someone else said

> but nothing except for "worker!" is printed in the console

can you check the dev console and see if that is the same for you?

**Comment by RuralAnemone** [comment]
what do you mean by that?

**Comment by lights0123** [comment]
For anyone following along, moving discussion to the linked issue.

**Comment by RuralAnemone** [comment]
This is closed, but we're moving to a different page: https://github.com/lights0123/lights0123.github.io/issues/16
