### ISSUE TITLE
Ndless 4.2 reboots on Ctrl+W

### ISSUE THREAD

**Issue by virtualdxs** [ndless-nspire/Ndless#26]
When I try to install Ndless, I use tilp to transfer installer and resources to calculator under folder ndless. I open the installer and press Ctrl+W as instructed. The calculator reboots and Ndless isn't installed.

I can't think of anything I could be doing wrong. Any ideas?

**Comment by virtualdxs** [comment]
Note: The same thing happened on 4.0.3 with its respective installer.

**Comment by Vogtinator** [comment]
I guess you've got a HW rev. W calc. Support for those isn't quite ready yet.

**Comment by virtualdxs** [comment]
Where do I find that out?

**Comment by virtualdxs** [comment]
My hardware revision that is

**Comment by Legimet** [comment]
Look at the back of your calculator. There is a string beginning with "P-". The last letter in that string is your hardware revision.

**Comment by virtualdxs** [comment]
The string is P-05140, so no other letters in it.

**Comment by Legimet** [comment]
That's probably an O. So no, you don't have HW-W.

**Comment by Legimet** [comment]
Could you attach the NspireLogs.zip file from your calculator?

**Comment by virtualdxs** [comment]
Pretty sure it's a 0 but I'll attach the logs in a couple hours when I get
a chance

**Comment by virtualdxs** [comment]
I'm unable to transfer the logs off of my calc using TILP, and I can't find the official software for Linux (WINE won't even open it).

**Comment by virtualdxs** [comment]
How else can I get them off?

**Comment by parrotgeek1** [comment]
Windows or OS X. sorry

**Comment by Vogtinator** [comment]
It should work with the official software from TI as well, IIRC.

**Comment by sassypantsman** [comment]
hey guys. On my calc it says P-1115W. Do I have a HW-S thing?

**Comment by sassypantsman** [comment]
I have the same problem. I have a ti nspire cx cas with os 4.2.0.532 and I transfered the ndless resources, ndless cfg and the ndless installer 4.2.0 cxcas on my calc into the ndless folder. When i press ctrl+w my calc reboots and there's no greent text saying ndless installed. What can I do? A friend of mine also has ti nspire cx cas with the same os and his p-number is P-1112H and ndless 4.2 worked for him.

**Comment by sassypantsman** [comment]
please help guys. I just want to put a gbc emulator on my calc that's all but without ndless I can't.

**Comment by Vogtinator** [comment]
> "I guess you've got a HW rev. W calc. Support for those isn't quite ready yet."

and
> "P-1115W"

**Comment by sassypantsman** [comment]
but the p string of my friend? it has an H at the end?

**Comment by Vogtinator** [comment]
HW-W != HW-H
As simple as that.

**Comment by sassypantsman** [comment]
So there is no way for me to get ndless on my calc?

**Comment by sassypantsman** [comment]
I don't understand...What is the problem with HW-W models?

**Comment by Vogtinator** [comment]
The latest source works, but programs won't run.
See also https://codewalr.us/index.php?topic=1150.0

**Comment by sassypantsman** [comment]
where can I find the latest source. I'm sorry I'm not very into things like this so sorry for silly questions.

**Comment by Vogtinator** [comment]
Here: https://github.com/ndless-nspire/Ndless

The latest installer is attached. You'll find that it's pretty useless once installed, though...
[ndless_installer_4.2.0_cascx.tns.zip](https://github.com/ndless-nspire/Ndless/files/149888/ndless_installer_4.2.0_cascx.tns.zip)

**Comment by sassypantsman** [comment]
still thank you. Is the ndless team working on a solution for hw-s models?

**Comment by Vogtinator** [comment]
HW-S works fine. I'm actually working on HW-W *right now*.

**Comment by sassypantsman** [comment]
oh i'm sorry. I made a mistake. I actually meant hw-w

**Comment by sassypantsman** [comment]
Ok that's cool if you're working on hw-w. But do you think it is possible that ndless will work on hw-w one day?

**Comment by sassypantsman** [comment]
And I'M just curious..What is the problem with HW-W?

**Comment by Vogtinator** [comment]
It already does. Programs don't.

> And I'M just curious..What is the problem with HW-W?

I gave you a link that you apparently ignored.

**Comment by sassypantsman** [comment]
But if ndless works on HW-W, then why is there no green text on the top left corner sayin "ndless installed". BTW I checked out the link but I didn't understand much because as I said I'm not into these things I'm just a normal person.

**Comment by sassypantsman** [comment]
Hey du kannst ja deutsch!

**Comment by Vogtinator** [comment]
> But if ndless works on HW-W, then why is there no green text on the top left corner sayin "ndless installed". 

You need to use the installer I attached.

> Hey du kannst ja deutsch!

Ist hier in Deutschland so üblich.

**Comment by sassypantsman** [comment]
OK dann bitte hilf mir weil ich kenn mich solchen sachen nicht aus.

**Comment by sassypantsman** [comment]
Ich habe keine Ahnung welche Dateien ich auf den rechner packen muss außer installer und resources. wie heißt der installer den du meinst? Kannst du mir einfach kurz erklären wie ich ndless RICHTIG auf einem hw-w modell installieren kann sodass der grüne text erscheint?

**Comment by Vogtinator** [comment]
Einfach https://github.com/ndless-nspire/Ndless/files/149888/ndless_installer_4.2.0_cascx.tns.zip benutzen. Du wirst aber noch warten müssen, bis du den GBC oder GBA Emulator verwenden kannst.

**Comment by sassypantsman** [comment]
schade...aber trotzdem danke

**Comment by sassypantsman** [comment]
Muss ich dann immernoch das resource file darufpacken, weil das du mir gegeben hast beinhaltet nur den installer?

**Comment by Vogtinator** [comment]
Einfach ndless_resources von Ndless 4.2 benutzen.

**Comment by sassypantsman** [comment]
danke

**Comment by sassypantsman** [comment]
Denks du es ist irgendwann möglich dass man auch programme auf hw-w modellen laufen lassen kann?

**Comment by Vogtinator** [comment]
Gerade in Arbeit. Momentan funktioniert das meiste, bis auf gbc4nspire.

**Comment by sassypantsman** [comment]
So ein Pech! Genau das was ich möchte geht nicht -.- Aber halte mich bitte auf dem laufenden was gbc4nspire angeht. Kann ich meine email adresse hier hinschreiben? Oder ist das keine gute Idee

**Comment by Vogtinator** [comment]
Keine gute Idee. Einfach bei diesem Repo in die Watch-Liste eintragen und abwarten, bis die nächste Release bereit ist.

**Comment by sassypantsman** [comment]
Ok. Gibt es wenigstens andere emuatoren, die funktionieren?

**Comment by sassypantsman** [comment]
Ich werde dann halt ab und zu bei deinem Profil vorbeischauen ob du was hochgeladen hast. Aber ich habe es jetzt in die Watch Liste eingetragen.

**Comment by sassypantsman** [comment]
DANKE dein Link hat funktioniert also ich habe jetzt ndless auf dem taschenrechner

**Comment by sassypantsman** [comment]
Nur so eine Frage, weil du gesagt hast alles geht außer gbc4nspire. Kann ich die funktionierenden Programme einfach herunterladen wie es andere auch tun oder gibt es für die auch einen besonderen Link wie für ndless?

**Comment by sassypantsman** [comment]
Also wenn ich jtz ein programm ganz normal herunterladen würde würde es dann auf meinem rechner gehen weil ich habe ja ein "besonderes" ndless

**Comment by Vogtinator** [comment]
Du hast kein besonderes Ndless, du hast besondere HW. Der compatibility layer funktioniert noch nicht so richtig, weshalb du den auch noch nicht benutzen kannst. Außer khicas wird wohl nichts wirklich benutzbar sein.

**Comment by sassypantsman** [comment]
Und wie lange brauchst du ungefähr bis gbc funktioniert?

**Comment by Vogtinator** [comment]
Zwischen einem Tag und ∞.

**Comment by sassypantsman** [comment]
Aber ist es möglich?

**Comment by Vogtinator** [comment]
Wenn nichts unerwartetes passiert, jep.

**Comment by sassypantsman** [comment]
Gut das freut mich. Ich hoffe gbc geht bald

**Comment by sassypantsman** [comment]
Dir noch viel Glück

**Comment by sassypantsman** [comment]
Kleine Update:

Ich have gbc4nspire draufgetan und super mario bros deluxe. Das spiel lässt sich öffnen nur das bild ist komisch. Es ist verzerrt und quer aber man kann trotzdem spielen. Die steuerungen usw gehen. Ich kann mario steuern. Das einzige problem ist das bild. Ebenso ist das bild komisch beim emulator selber

**Comment by sassypantsman** [comment]
also wenn du es hinkriegen würdest, dass das bild normal aussieht hättest du's geschafft :D

**Comment by sassypantsman** [comment]
:+1:

**Comment by Vogtinator** [comment]
Genau das ist das Problem. HW-W hat einen 240x320px Bildschirm, alles davor 320x240px.

**Comment by sassypantsman** [comment]
Also hat es eine höhere auflösung ich verstehe

**Comment by sassypantsman** [comment]
Ja aber kann man nicht die roms in 240x320p darstellen

**Comment by sassypantsman** [comment]
ok ehrlich gesagt weiß ich nicht ob hw-w eine höhere auflösung. ich will hier nicht wie ein idiot klingen

**Comment by sassypantsman** [comment]
ich wünschte mir echt ich hätte genug wissen und kenntnisse übers programmieren damit ich auch versuchen könnte das problem zu lösen

**Comment by sassypantsman** [comment]
hey du sagtest ja wenn nix unerwartets passiert ist es möglich dass es irgendwann geht. Aber was versuchst du überhaupt zu machen? Ich meinen versuchst du am rom irgendwas zu ändern oder am taschenrechner selber?

**Comment by sassypantsman** [comment]
würd mich nur interessieren

**Comment by sassypantsman** [comment]
hey gibt's schon irgendwelche fortschritte?

**Comment by Vogtinator** [comment]
Bitte hier nur sinnvolle Kommentare und kein double-posting, das nervt!

**Comment by sassypantsman** [comment]
ok

**Comment by sassypantsman** [comment]
hat sich irgendwas getan bei gbc4nspire?

**Comment by Vogtinator** [comment]
Es funktioniert, soweit aber leider nur im Emulator und nicht auf echter HW.

**Comment by sassypantsman** [comment]
Das ist super!

Wann wird es auf echter hardware gehen?

**Comment by parrotgeek1** [comment]
@Vogtinator maybe if you look at datasheet of this lcd, in best case scenario there can be a mode which mirrors the  output to be 320x240? but probably not otherwise TI would have used it

**Comment by sassypantsman** [comment]
are there any other emulators that work on hw-w?

**Comment by Vogtinator** [comment]
Nothing except khicas is works yet.

**Comment by sassypantsman** [comment]
can you give me a download link for khicas and where can i get games for it?

**Comment by sassypantsman** [comment]
when i asked about working emuators i meant emulators for games

**Comment by sassypantsman** [comment]
sorry for asking every day but...is it ready to test?

**Comment by sassypantsman** [comment]
i just want gbc so bad ya know

**Comment by Vogtinator** [comment]
You're double-posting again. And just so you know, I have a job and a life just as everyone else so it may take a while.

**Comment by sassypantsman** [comment]
really? how old are you if i may ask?

**Comment by Vogtinator** [comment]
18.

**Comment by sassypantsman** [comment]
a job with 18?

**Comment by Vogtinator** [comment]
Yes. This isn't an appropriate place to discuss this.

**Comment by Vogtinator** [comment]
It looks like you're lucky, I just got something working. It's a bit slow though, it needs to be tweaked a bit.
Install the attached files and please provide feedback!
[ndlessw.zip](https://github.com/ndless-nspire/Ndless/files/155791/ndlessw.zip)

**Comment by sassypantsman** [comment]
Wow! Thank you!

**Comment by sassypantsman** [comment]
I tried it out andi it's a lot better now. But it's not perfect yet. A quarter of the screen on the right side of the display is grey and not working but the rest of the display is just as it should be.So if you could fix that grey part it would be perfect

**Comment by sassypantsman** [comment]
sorry for double-posting...


How long would it take you to fix these last few problems because you're very close to it

**Comment by Vogtinator** [comment]
I do not have the issue here and can't reproduce it. Can you upload a picture?

**Comment by sassypantsman** [comment]
I'm on my phone right now and I don't know how to upload a picture here. Can we talk somewhere else?

**Comment by sassypantsman** [comment]
And also gbc4nspire itself doesn't work. I can open it but it's all grey. I directly open mario

**Comment by sassypantsman** [comment]
![Uploading image.jpg…]()
![Uploading image.jpg…]()
![Uploading image.jpg…]()

First image is gbc4nspire
The other two are super mario bros deluxe

**Comment by Vogtinator** [comment]
Opening gbc4nspire won't work currently, but as long as games work it shouldn't matter.

You need to wait for the files to finish uploading before you submit the comment.

**Comment by sassypantsman** [comment]
![image](https://cloud.githubusercontent.com/assets/17526972/13492772/5026638c-e13a-11e5-808b-1249ed332d0e.jpg)
![image](https://cloud.githubusercontent.com/assets/17526972/13492774/506f2040-e13a-11e5-89e2-1eadc0ad6079.jpg)

**Comment by sassypantsman** [comment]
![image](https://cloud.githubusercontent.com/assets/17526972/13492805/81dbaf0e-e13a-11e5-8749-cc16b6c48689.jpg)




This is gbc4nspire

**Comment by Vogtinator** [comment]
Ok, I see. I'll look what might be causing this. It seems to stop displaying at exactly 75% of the screen, can you confirm that?

**Comment by sassypantsman** [comment]
The game works. I can play but the grey part is annoying. if you could fix that it would be perfect.

My model is P1115-W

OS 4.2.0.532

**Comment by sassypantsman** [comment]
Yes

**Comment by sassypantsman** [comment]
I just wanted to say that I also tried the legend of zelda and it's the same problem like in mario. 25% of the screen on the right side is grey

**Comment by Vogtinator** [comment]
Are other ndless programs (crafti, gpsp) affected by the same issue?

**Comment by sassypantsman** [comment]
I don't know because I only tested gbc on it.
Can just quickliy post a donwload link for anorther program so I can test it?

**Comment by Vogtinator** [comment]
https://github.com/Vogtinator/crafti/releases/download/v1.1/crafti.prg.tns

**Comment by sassypantsman** [comment]
![image](https://cloud.githubusercontent.com/assets/17526972/13506904/914ed240-e180-11e5-95b2-eff04099224b.jpg)
![image](https://cloud.githubusercontent.com/assets/17526972/13506905/915565e2-e180-11e5-8e41-a6c97fe287ee.jpg)

**Comment by sassypantsman** [comment]
Crafti works fine so I guess there's a problem with gbc roms?

**Comment by Vogtinator** [comment]
I've got a slight suspicion that gbc4nspire tries to reconfigure the LCD controller.
Does it work with 
[ndless_resources.tns.zip](https://github.com/ndless-nspire/Ndless/files/157628/ndless_resources.tns.zip)?

**Comment by sassypantsman** [comment]
Hey, so did you find anything out about it?

**Comment by sassypantsman** [comment]
wait I'll try

**Comment by sassypantsman** [comment]
![image](https://cloud.githubusercontent.com/assets/17526972/13508279/9d18116c-e186-11e5-85e3-b5c9a7725d30.jpg)
![image](https://cloud.githubusercontent.com/assets/17526972/13508280/9d194834-e186-11e5-92c8-925251d1b1d4.jpg)

**Comment by sassypantsman** [comment]
Unfortunately it didn't change anything BUT I discovered something. If I hold the esc button the colors change a little but as long as I hold down the esc button the grey part goes away. Same happened in Zelda

**Comment by sassypantsman** [comment]
It's crazy. As soon as I press the esc button and hold it down the grey part disappeares and becomes normal but the colors change I hope you can see it in the pictures and I HOPE this information helps you

**Comment by Vogtinator** [comment]
Let me guess, it works for all keys except the On key?

**Comment by sassypantsman** [comment]
It only happens when I press the esc button. When I press other buttons nothing happens

**Comment by Vogtinator** [comment]
Ok, so it's actually the program exiting. It undos the palette change on exit, so that's what you see as color change. Can you try [ndless_resources.tns.zip](https://github.com/ndless-nspire/Ndless/files/157654/ndless_resources.tns.zip)?

**Comment by sassypantsman** [comment]
HOLY SH*T MAN! IT WORKS! YOU DID IT! Ok sorry I couldn't control myself...

But it works now the whole screen is normal. The colors still change when I exit the game but that doesn't bother me. gbc itself still doesn't work so I directly open the games

**Comment by Vogtinator** [comment]
> HOLY SH*T MAN! IT WORKS! YOU DID IT! Ok sorry I couldn't control myself...

Thanks for testing! Don't forget to upgrade to the next release of ndless as your current ndless_resources is a bit hacked together and will not work with some newer programs with explicit HW-W+ support.

> gbc itself still doesn't work so I directly open the games

I'm close to solving that too, it may be a a bit too complicated for such a relatively minor issue though.

**Comment by sassypantsman** [comment]
![image](https://cloud.githubusercontent.com/assets/17526972/13509080/0e2d5968-e18a-11e5-8e93-5dd96cb7b17f.jpg)
![image](https://cloud.githubusercontent.com/assets/17526972/13509081/0e3705da-e18a-11e5-973e-dc49fc5357e5.jpg)
![image](https://cloud.githubusercontent.com/assets/17526972/13509082/0e3b1b16-e18a-11e5-9cb5-2f7a4a12da6a.jpg)

**Comment by sassypantsman** [comment]
I appreciate it man.

The first picture is gbc

The second zelda and the third is mario

**Comment by Vogtinator** [comment]
I had a look at it, gbc4nspire uses 4bpp mode to display the menu,
which is a PITA to implement properly, so I'm not going to do that.
As gbc4nspire and other apps run fine otherwise, I consider this fixed :-)

**Comment by sassypantsman** [comment]
There's a new issue. With the new resources file the game slows down every 1 second. So I wa playing mario and I noticed that he runs normally but then he runs a little bit slower and then again faster and then slower. Noticed the same in zelda. The character moves normally but then he moves slower and then faster again. So basically it changes every second: In one second the game speed is normal and in the other second the speed slows down and then in the next second it's normal again

**Comment by Vogtinator** [comment]
Does this also happen with the older resources?

**Comment by sassypantsman** [comment]
No I never noticed it before. I also died a few times in mario becaus of this issue and until now I was pretty good at mario so no it didn't happen before

**Comment by sassypantsman** [comment]
Oh man why does this have to happen :/
I mean you just fixed that one problem and now there's this...

**Comment by Vogtinator** [comment]
It adjusts speed based on the LCD timings, I guess.
I'm not sure how this causes a change every second though.

**Comment by sassypantsman** [comment]
I recorded a video with my phone but that file type isn't supported here

**Comment by sassypantsman** [comment]
I can try to turn it into rar file and upload it

**Comment by sassypantsman** [comment]
man i can't :(

when i try to open the video on my pc it doesn't even work. i recorded it with my iphone

any ideas how i can show you the video?

**Comment by Vogtinator** [comment]
Just upload it somewhere else and link it here

**Comment by sassypantsman** [comment]
https://www.youtube.com/watch?v=OmT1pbH7JIc&feature=youtu.be

**Comment by sassypantsman** [comment]
I hope you see it. It slows down every second or maybe even in a shorter period

**Comment by sassypantsman** [comment]
Do you think you can fix it?

**Comment by Vogtinator** [comment]
That doesn't look like it's changing the speed, that's probably the display synchronization that is not working in lcd_compat mode.
I increased the frame rate to 20Hz [ndless_resources.tns.zip](https://github.com/ndless-nspire/Ndless/files/157751/ndless_resources.tns.zip).

**Comment by sassypantsman** [comment]
nah man, you can still feel it. with the previous resources files where 25% of the screen was grey the game was smooth

**Comment by Vogtinator** [comment]
Is it at least a bit better with the 20Hz one?
Was it smooth with https://github.com/ndless-nspire/Ndless/files/157628/ndless_resources.tns.zip as well?

**Comment by sassypantsman** [comment]
Actually no because the gameplay is generally faster but as long you feel that little lag it's not enjoyable

and no i just tried it and i still have that lag

**Comment by sassypantsman** [comment]
bruh why can't it just be fullscreen and with a constant frame rate...

**Comment by Vogtinator** [comment]
Did you test the ndless_resources from my last comment? Could you clarify the result?

**Comment by sassypantsman** [comment]
Yes i did and it's still the same

**Comment by sassypantsman** [comment]
anything new?

**Comment by Vogtinator** [comment]
I'm afraid I have no idea what's causing this and how to fix it.

**Comment by parrotgeek1** [comment]
@Vogtinator I have the weirdest idea, based on your work to remap the LCD controller to other memory
what if nlaunchy did that, but with 900A0000, and emulated the ASIC user flags to match CAS

**Comment by Vogtinator** [comment]
parrotgeek: The OS rewrites the page tables, so that code would need to be patched as well.
More work for the same outcome.
