### ISSUE TITLE
Error when build_toolchain.sh is run in 32-bit Cygwin on Windows 10

### ISSUE THREAD

**Issue by logantischler0** [ndless-nspire/Ndless#260]
I am trying to install the Ndless SDK.

Whenever I run build_toolchain.sh, it says:

checking whether to use python... /usr/bin/python3
checking for python... no
configure: error: no usable python found at /usr/bin/python3
make[1]: *** [Makefile:9537: configure-gdb] Error 1
make[1]: Leaving directory '/home/staff/Ndless/ndless-sdk/toolchain/build'
make: *** [Makefile:855: all] Error 2

I do have python3.8 installed in the Cygwin directory. Here's its PATH:
C:\cygwin\bin\python3.8.exe

What should I do?

Thanks in advance.

**Comment by Vogtinator** [comment]
You would need python development headers, not sure what they're called in cygwin. Alternatively, just comment out the line containing `--with-python`.

**Comment by logantischler0** [comment]
Thank you! It worked!
