### ISSUE TITLE
Help with compiling SDK?

### ISSUE THREAD

**Issue by Tru-Dev** [ndless-nspire/Ndless#271]
Hello, I was wondering if I could get help with compiling the Ndless SDK for WSL.
![image](https://user-images.githubusercontent.com/29785998/103381167-34755d00-4aa8-11eb-9a8d-cffd01a37e0c.png)
This is what I've got from the console, and I can't find `arm-none-eabi-gcc` for the life of me.
Thanks for your help!

**Comment by lights0123** [comment]
Those logs look like it's actively doing something—does it freeze there?

**Comment by Tru-Dev** [comment]
That's it
It just returns afterwards

**Comment by Tru-Dev** [comment]
Actually, it's a coincidence that you responded because I'm going to be using your Ndless Rust bindings!

**Comment by lights0123** [comment]
Are you using WSL or WSL2?

Also, it'll probably be a week+ out (if I prioritize it, which I can do if I know that someone will use it), but I'm working on an update that lets you use precompiled Ndless files with my Rust support. You'll get full LTO out of the box, without having to manually compile any C files. I believe I can also get native Windows support.

**Comment by Tru-Dev** [comment]
WSL2.

**Comment by lights0123** [comment]
Just confirming—this is after running `./build_toolchain.sh`? What's the output of `ls -a`? If you run `echo $?` immediately after (or run `./build_toolchain.sh; echo Exit code: $?`), what is its output?

**Comment by Tru-Dev** [comment]
This is after running `./build_toolchain.sh`, yes.
$? = 2
ls -a:
![image](https://user-images.githubusercontent.com/29785998/103385537-19124e00-4ab8-11eb-8c65-16b853ead7de.png)

**Comment by Vogtinator** [comment]
That output looks very odd - everything is printed twice. If you run `build_toolchain.sh` again, what't the full output (as attachment please)?

**Comment by Tru-Dev** [comment]
[out.txt](https://github.com/ndless-nspire/Ndless/files/5756027/out.txt)
Also, this was in stderr:
![image](https://user-images.githubusercontent.com/29785998/103386566-a8b9fb80-4abc-11eb-9ca2-29ec8c6beae3.png)

**Comment by Tru-Dev** [comment]
(ignore the first line)

**Comment by Vogtinator** [comment]
Ok, that shows that you don't have `g++` installed, that's required for building. You can install `makeinfo` as well to avoid the warnings about that, but it shouldn't be required.

**Comment by Tru-Dev** [comment]
Now it gets to building NewLib, but then gives this error message:
`configure: error: cannot find sources (move-if-change) in ../download/newlib-3.0.0 or ..`
Newlib is in the download folder though...

**Comment by Tru-Dev** [comment]
I fixed it by manually extracting the archive, but now I have this problem:
![image](https://user-images.githubusercontent.com/29785998/103426313-d747dd00-4b75-11eb-85af-e490f42b7175.png)

**Comment by Vogtinator** [comment]
Something is weirdly broken with your setup. Maybe you ran out of space and so the extraction failed?
Anyway, remove all `newlib` stuff in `download` and run `build_toolchain.sh` again. The full output might be useful.

**Comment by Tru-Dev** [comment]
I got past the configure can't find sources in newlib error by manually extracting the files already, I just need help with whatever this is.

**Comment by Vogtinator** [comment]
That you had to manually extract at all means that something went wrong at that point already. This might be a followup failure.

**Comment by lights0123** [comment]
You're running this on the native WSL2 filesystem, right? Not `/mnt/c/...`?

**Comment by Vogtinator** [comment]
The screenshot shows `/mnt/c`, so probably not. That might indeed cause some issues.

**Comment by lights0123** [comment]
Ah, yes it does. NTFS probably is causing some issues.

**Comment by lights0123** [comment]
(@Tru-Dev you should re-clone instead of just copying files over)

**Comment by Tru-Dev** [comment]
Oh ok!

**Comment by Tru-Dev** [comment]
`make: *** [Makefile:852: all] Error 2` while building Binutils...

**Comment by Tru-Dev** [comment]
(and this was on the native WSL2 filesystem)

**Comment by lights0123** [comment]
Any other errors? Can you give us the log?

**Comment by Tru-Dev** [comment]
... And I am an idiot.
I just read "change the `PREFIX` env variable to the install location" and I didn't do that.
No wonder it isn't working...

**Comment by Vogtinator** [comment]
You're using the default already, which should be fine.

**Comment by Tru-Dev** [comment]
Oh ok!

**Comment by Tru-Dev** [comment]
[out.txt](https://github.com/ndless-nspire/Ndless/files/5758429/out.txt)
This is the erroneous output, complete with stderr.

**Comment by Vogtinator** [comment]
Apparently it thinks that it has to regenerate documentation for `binutils` for some reason, but it shouldn't. I can't tell why, but simplest fix is to just install `makeinfo` and let it regenerate it.

**Comment by Tru-Dev** [comment]
Oh ok!

**Comment by Tru-Dev** [comment]
![image](https://user-images.githubusercontent.com/29785998/103432911-f9a51f00-4ba4-11eb-9980-0e903d47ca1a.png)
I think the SDK is officially compiled! Thank you guys so much! Wish you two a happy new year!

(the helloworld-sdl example was already compiled, so I think it worked? Either way, closing issue.)
