### ISSUE TITLE
Clicking on the ndless_installer_4.5.0 takes me to a blank document

### ISSUE THREAD

**Issue by IIWare** [ndless-nspire/Ndless#274]
I would like to install ndless in my calculator, but when I click on ndless_installer_4.5.0 it takes me to a blank page, any solutions? thanks.

**Comment by Vogtinator** [comment]
Which calculator model and OS version?

**Comment by IIWare** [comment]
Calculator model: TI nspire cx cas

OS Version: 4.5.1.12

**Comment by Vogtinator** [comment]
That's the problem, you're using OS 4.5.1 and trying the 4.5.0 installer. You need to upgrade to 4.5.3 and use the 4.5.3 installer.

**Comment by IIWare** [comment]
@Vogtinator Sorry I didn't realize.
