### ISSUE TITLE
Jobserver tokens only 5 out of 8

### ISSUE THREAD

**Issue by krystalgamer** [ndless-nspire/Ndless#28]
Hey so i'm trying to compile ndless sdk with mingw w64 (x64) in win 7and i'm stuck. I included the log of running build_toolchain.sh if needed http://pastebin.com/SmSCx1xt. I got it with ./build_toolchain.sh > log.txt. For some reason the printed messages were not logged so here's the output on the MinGW shell https://ghostbin.com/paste/3dnxn

I had to clone the thirdparty submodules because freetype2 was giving me a error.

In this latest build i got 7 outta 8. What should i do?

**Comment by Vogtinator** [comment]
MinGW is not supported and does not work. Use Cygwin instead.

**Comment by krystalgamer** [comment]
Thanks, issue closed. Should edit the wiki though.

**Comment by Vogtinator** [comment]
It says so in the Wiki: "On Windows: Install Cygwin".

**Comment by krystalgamer** [comment]
@Vogtinator You're right, sorry, i thought i could use MinGW because it usually is compatible.
Im right now compiling ndless source with cygwin x64(dumb me didn't read the cygwin part of the wiki). Will it cause any problem?

**Comment by krystalgamer** [comment]
Compiled successfully for some reason the ndless i compiled has an vertical bar of pixels with random colors. Couldn't take a picture so here's a recreation in paint: http://i.imgur.com/umudkcf.png
Those horizontal bars are replicated in the verical for some reason.

**Comment by Legimet** [comment]
That is expected behavior, because of the HW-W support.

**Comment by krystalgamer** [comment]
But why the downloaded from ti planet doesnt have that vertical bar? Is it an older version?

**Comment by Legimet** [comment]
Yes, it is.

**Comment by krystalgamer** [comment]
Alright, everything is fine now. Thanks a lot everyone that helped!
