### ISSUE TITLE
Move from make to CMake + ninja

### ISSUE THREAD

**Issue by Bensuperpc** [ndless-nspire/Ndless#280]
Hello Everybody,

I would like to know if you are interested that I update the build automation tool, going from Make to CMake + Ninja,
it uses all the CPU cores for a faster compilation, it is Windows, Linux and Mac compatible... 
it is possible to do unit tests, several types of build, but also to be able to generate documentation (via Doxygen ect ..).
It is very complete.

Bensuperpc,

**Comment by Vogtinator** [comment]
> I would like to know if you are interested that I update the build automation tool, going from Make to CMake + Ninja,
it uses all the CPU cores for a faster compilation, it is Windows, Linux and Mac compatible...

Hi! The Makefiles in this project already compile everything in parallel and build time is really not an issue, `make clean; time make -j8` takes just 12s here.

The Makefiles here are mostly used to run arbitrary commands in the right order, the focus isn't even that much on compiling, especially the installers are very custom in that regard.

All of that means that converting it to CMakeLists.txt would just make it more complex, so I don't think it's worth it.

> it is possible to do unit tests, several types of build, but also to be able to generate documentation (via Doxygen ect ..).

Currently there's (unfortunately) no documentation in this repo... Tests could be added using Makefiles as well, by just adding a `make test` target. CMake doesn't actually make it that much simpler, it only includes the facility to run and display them, but not the actual test harnesses anyway.
