### ISSUE TITLE
Issue with running 'make' in the top level of the ndless repo

### ISSUE THREAD

**Issue by Strata69** [ndless-nspire/Ndless#283]
hi there!
I run Ubuntu 21.04, and am trying to setup the ndless SDK. (whee.)
I've run build_toolchain.sh and it has definitely completed, and I've added the required line to my PATH environment variable. However, I'm running into issues regarding running the make command in the top level of the repository. This is the output when I run the command:

strata69@bigbigchungus:~/Strata69/Ndless$ make
make -C ndless-sdk
make[1]: Entering directory '/home/strata69/Strata69/Ndless/ndless-sdk'
make -C libsyscalls
make[2]: Entering directory '/home/strata69/Strata69/Ndless/ndless-sdk/libsyscalls'
arm-none-eabi-g++ -mcpu=arm926ej-s -std=c++11 -nostdlib -O3 -fPIE -fno-exceptions -fno-rtti -mlong-calls -Wall -Werror -I ../include/ -I ../thirdparty/nspire-io/include/ -D_TINSPIRE -ffunction-sections -fdata-sections -c stdlib.cpp -o stdlib.o
stdlib.cpp: In function 'int _stat(const char*, stat*)':
stdlib.cpp:302:6: error: 'struct stat' has no member named 'st_atime'; did you mean 'st_atim'?
  302 |  st->st_atime = nuc_st.st_atime;
      |      ^~~~~~~~
      |      st_atim
stdlib.cpp:303:6: error: 'struct stat' has no member named 'st_mtime'; did you mean 'st_mtim'?
  303 |  st->st_mtime = nuc_st.st_mtime;
      |      ^~~~~~~~
      |      st_mtim
stdlib.cpp:304:6: error: 'struct stat' has no member named 'st_ctime'; did you mean 'st_ctim'?
  304 |  st->st_ctime = nuc_st.st_ctime;
      |      ^~~~~~~~
      |      st_ctim
stdlib.cpp: In function 'char* get_current_dir_name()':
stdlib.cpp:489:45: error: 'PATH_MAX' was not declared in this scope
  489 |  char *buf = reinterpret_cast<char*>(malloc(PATH_MAX));
      |                                             ^~~~~~~~
make[2]: *** [Makefile:18: stdlib.o] Error 1
make[2]: Leaving directory '/home/strata69/Strata69/Ndless/ndless-sdk/libsyscalls'
make[1]: *** [Makefile:14: build-libsyscalls] Error 2
make[1]: Leaving directory '/home/strata69/Strata69/Ndless/ndless-sdk'
make: *** [Makefile:19: build-ndless-sdk] Error 2

Considering that nspire-gcc isn't recognized as a command when I try to run it (it outputs nspire-gcc: command not found), I think that there's an issue here. Would appreciate any help. Thanks!

**Comment by Vogtinator** [comment]
Hi!

Make sure you set up `$PATH` correctly. It's not using the correct `arm-none-eabi-gcc`, see also #144.

**Comment by Strata69** [comment]
Hmm... I actually couldn't locate .bash_profile, so i put it in .profile, thinking that they were the same thing, if I'm not mistaken. I'll check again when i get the chance, thanks for the prompt help!

**Comment by adriweb** [comment]
Well, it's whatever your shell uses. Could also be .zshrc if you use zsh

**Comment by Strata69** [comment]
sorry , but which of these would be the right place to place the $PATH command? 
![Screenshot_3](https://user-images.githubusercontent.com/78792398/116785359-c5e2f300-aacb-11eb-9df6-a1059ab84158.png)

**Comment by Strata69** [comment]
woohoo! i realised that i should've put it in .bashrc and it's running right now so I think it's fixed! thanks for the help vogt and adriweb, really appreciate it :)
