### ISSUE TITLE
Issue with dirent.h /readdir - opendir - closedir

### ISSUE THREAD

**Issue by SlyVTT** [ndless-nspire/Ndless#284]
Hello everybody,

I am experiencing a bug in my GUI Tollkit when trying to list files and folders in a given folder.

My code is the following :

``` cpp
int FileDialogBoxWidget::listdir(const char *path)
{
    char name[255];
    struct dirent *ent;
    DIR *dir = opendir(path);
    while((ent = readdir(dir)))
    {
        strcpy(name, path);
        strcat(name,"/");
        strcat(name, ent->d_name);
        DIR *test = opendir( name );
        if(test)
        {
            closedir(test);
            folderlist->additem( (char *) ent->d_name );
        }
        else
        {
            filelist->additem( (char *) ent->d_name );
        }
    }
    closedir(dir);
  return 0;
}
```
It loops the correct number of times but ent->d_name always return the name of the first item (in my case the name of the first folder) in the considered folder to scrutinize.

I made the same routine on my linux distribution and it works perfectly well. The code is as follows :

``` cpp
int listdir(const char *path)
{
    char name[255];
    struct dirent *ent;
    DIR *dir = opendir(path);
    while((ent = readdir(dir)))
    {
        //Test whether it's a directory
        strcpy(name, path);
        strcat(name,"/");
        strcat(name, ent->d_name);
        DIR *test = opendir( name );
        if(test)    // This is a directory and we add to the folder list widget
        {
            closedir(test);
            printf( "[ %s ] \n", ent->d_name );
        }
        else    // this is a file and we add to the folder list widget
        {
                printf( " %s  \n", ent->d_name );
        }
    }
    closedir(dir);
  return 0;
}
```

No need to say that I checked many thing to try to identify if the folderlist and filelist works fine, and they do.

I do not understand what's happening,

Could you please check if something is broken with the dirent structure / opendir-readdir functions ?

The bug is in the following file : [https://github.com/SlyVTT/Widget-for-TI-NSpire/blob/main/Toolkit/FileDialogBoxWidget.cpp](url)

Regards

Sylvain

**Comment by SlyVTT** [comment]
Ok Guys,

Spending a lot of time on this, we can conclude I am a bit brainless ...

Now this is working. The problem was coming from the use of the ent->d_name as an allocated (char *) while it is just a pointer. Now I allocate memory on the fly for each iteration of the loop and copy the ent->d_name to the right place.
This avoid pointing (and adding in the lists) always the first item.

below is the working code, note the malloc part that saves my life ;-)

``` cpp
int FileDialogBoxWidget::listdir(const char *path)
{
 char name[255];
    struct dirent *ent;
    DIR *dir = opendir(path);
    while((ent = readdir(dir)))
    {
        //Test whether it's a directory
        strcpy(name, path);
        strcat(name,"/");
        strcat(name, ent->d_name);
        DIR *test = opendir( name );
        if(test)    // This is a directory and we add to the folder list widget
        {
            closedir(test);
            char *temp = (char*) malloc( strlen(ent->d_name) +1 );
            strcpy(temp, ent->d_name );
            folderlist->additem( (char *) temp );
        }
        else    // this is a file and we add to the file list widget
        {
            char *temp = (char*) malloc( strlen(ent->d_name) +1 );
            strcpy(temp, ent->d_name );
            filelist->additem( (char *) temp );
        }
    }
    closedir(dir);
  return 0;
}
```

**Comment by Vogtinator** [comment]
> Now this is working. The problem was coming from the use of the ent->d_name as an allocated (char *) while it is just a pointer. Now I allocate memory on the fly for each iteration of the loop and copy the ent->d_name to the right place.

`ent->d_name` is a pointer to an allocated char array. The same is true on Linux as well and pretty much every other OS. The issue with your code is actually that the ownership isn't clear and you're handling pointers to freed memory. `ent` is only valid until the next call to `readdir` or `closedir` with the corresponding `DIR*`. The man page for `readdir` here says:
> The data returned by readdir() may be overwritten by subsequent calls to readdir() for the same directory stream.

That's what's happening here: You're passing a pointer to your `ListBoxWidget`, which just stores it as-is and then replace the content it points to. If you actually check the address `ent->d_name` points to, you'll see that they're always the same.

Your old `FileDialogBoxWidget::listdir` method would have the same bug on Linux as well. The reason your test code on Linux had the expected result is that you called `printf` with the file name before you reused the pointer.

> below is the working code, note the malloc part that saves my life ;-)

That looks better, though you can save a few lines of code by using `strdup`. Note also that you have to `free` the allocated memory at some point. Your `virtual ~ListBoxWidget()` currently doesn't do that, it just clears the vector (which is equivalent to `listitems.clear()` btw, but `std::vector` does that itself already).

I'd recommend to just use `std::string`. The main downside is that the executable gets noticably bigger when using those STL components, but you're already using them and so it might not make a meaningful difference.

**Comment by SlyVTT** [comment]
Hello Fabian,

Thank you very much for taking the time to answer to that topic.

Yes, I understood my mistake when I used the linux code on the nSpire and it "worked" fine. So with the printf it was Ok and not with the ListBoxWidget::additem. So then I understood that it was jsut a "problem of pointer".

Thank you for the tip of using std::string instead of char* with malloc. This was my new problem: being able to free the memory. As you said, i am already using std::string, so it should not have a significant impact on the size of the executable.

Today my main goal is to reach the "Release Candidate Alpha" with all the widgets "more or less" working and then from this starting point, to clean and optimise the code to make it better for the "Final Revision 1.0". One consideration for the optimisation process will be clearly to switch all char* stuff to std::string.

Once again thanks for the feedback and your help.

Sly
