### ISSUE TITLE
is 5.1.3.73 going to be supported? if so, when?

### ISSUE THREAD

**Issue by Sugayrwaffle** [ndless-nspire/Ndless#286]
on ti nspire cx II

**Comment by pigeonburger** [comment]
Just update your OS to a supported version and it'll work.

**Comment by KCsup** [comment]
I'm wondering about this specifically as well. I've tried to upload an older OS to the calculator through the student software, but it doesn't allow me to do so. Even after deleting the OS of the calculator in Maintenance Mode, the calculator doesn't allow you to upload an older OS than with the one currently on the calculator. Is there absolutely any way to downgrade OSs?
