### ISSUE TITLE
Can't install certain Ndless dependencies on Cygwin, hackspire article may be outdated...?

### ISSUE THREAD

**Issue by RuralAnemone** [ndless-nspire/Ndless#290]
I've decided to try to add sound card support to gpSP, but to do that I need to install the Ndless SDK (obviously)

Some of the dependencies aren't available on Cygwin anymore, and some are obsoleted by others. (2 of the dependencies even obsolete each other)

Is there a more updated list of dependencies to install? (I'm using https://hackspire.org/index.php/C_and_assembly_development_introduction which seems to be the most updated, but I'm not sure)

help

**Comment by RuralAnemone** [comment]
brb with specifics

**Comment by adriweb** [comment]
(Someone over at TI-Planet was able to build the latest master branch just a few days ago so we know it's possible, indeed the list of deps may just need to be updated)

**Comment by RuralAnemone** [comment]
ohh okay
I guess I'll just try to install the listed deps and see if that works...

**Comment by Vogtinator** [comment]
If you have a complete list of dependencies, please update the wiki yourself or write them down here so that someone else can do it.
