### ISSUE TITLE
Ndless Compatible Versions

### ISSUE THREAD

**Issue by itsJavaCoder** [ndless-nspire/Ndless#294]
I checked the website for the compatible versions of Ndless and it said:

- 4.0.3.93
- 4.2.0.532
- 4.4.0.532
- 4.5.0.1180
- 4.5.3.14
- 4.5.4.48

(For the compatible versions.) The latest I can do is 4.5.4 from the website. Is it compatible? If not, How can I find some of the compatible versions?

**Comment by adriweb** [comment]
No, 5.2 and 5.3 are also supported, for the CX II. For the CX, yes indeed 4.5.4 is the latest.

What website did you check? The [Releases page](https://github.com/ndless-nspire/Ndless/releases/latest), the [official website](https://ndless.me), among others, are all updated.

**Comment by itsJavaCoder** [comment]
> No, 5.2 and 5.3 are also supported, for the CX II. For the CX, yes indeed 4.5.4 is the latest.
> 
> What website did you check? The [Releases page](https://github.com/ndless-nspire/Ndless/releases/latest), the [official website](https://ndless.me), among others, are all updated.

I checked the official website.

**Comment by adriweb** [comment]
Then it's pretty clear: 

![image](https://user-images.githubusercontent.com/660896/121544694-ea3dc380-c9d7-11eb-863e-1115fec65a4e.png)

**Comment by itsJavaCoder** [comment]
> Then it's pretty clear:
> 
> ![image](https://user-images.githubusercontent.com/660896/121544694-ea3dc380-c9d7-11eb-863e-1115fec65a4e.png)

oh. I see this on the official ti website. I just went to TI-Planet and found version: 4.5.4.48.
![image](https://user-images.githubusercontent.com/67208310/121545089-d2624180-c9cf-11eb-8b0f-105e92c1b161.png)

**Comment by adriweb** [comment]
Well TI is certainly not going to distribute Ndless, but yes that's where you find the OSes (and also on TI-Planet for some of them, sure)

**Comment by itsJavaCoder** [comment]
> Well TI is certainly not going to distribute Ndless, but yes that's where you find the OSes (and also on TI-Planet for some of them, sure)

Thanks for the help
