### ISSUE TITLE
OS 5 on CX CAS?

### ISSUE THREAD

**Issue by itsJavaCoder** [ndless-nspire/Ndless#295]
Is there a way I could get v5.0 on my CX CAS instead of getting the CX CAS II?

**Comment by Vogtinator** [comment]
No. While the OS builds for the CX II still contain some drivers for the older models, it's not compatible.

**Comment by itsJavaCoder** [comment]
> No. While the OS builds for the CX II still contain some drivers for the older models, it's not compatible.

ah. ok.
