### ISSUE TITLE
Missing header for compilation

### ISSUE THREAD

**Issue by dav20011** [ndless-nspire/Ndless#30]
I used a new installation of Cygwin to compile the SDK, but when trying to compile the helloworld-sdl sample, there's the syscall-decls.h header missing.

Code from make:
`/home/foo/Ndless/ndless-sdk/include/os.h:30:27: schwerwiegender Fehler(==fatal error): syscall-decls.h: No such file or directory
`

In the include directory are syscall and syscall-list present, but not syscall-decls.

**Comment by Vogtinator** [comment]
syscall-decls.h is generated by a PHP script. Run make in ```/home/foo/Ndless/ndless-sdk/```.

**Comment by dav20011** [comment]
Sorry, totally forgot that.
