### ISSUE TITLE
nspire cx cas v.4.5.5.79???

### ISSUE THREAD

**Issue by BosscarG** [ndless-nspire/Ndless#301]
LIke an idiot i updated my tin-nspire cx CAS calculator to version 4.5.5.78 not realising ndless was availble for that version. Do you know if ndless is in development for 4.5.5.78 or is there a way i can downgrade to 4.5.4.48? when i tried to it said you can downgrade

**Comment by Vogtinator** [comment]
Let's close this as a duplicate of #300.

**Comment by Djwillisdareal** [comment]
> LIke an idiot i updated my tin-nspire cx CAS calculator to version 4.5.5.78 not realising ndless was availble for that version. Do you know if ndless is in development for 4.5.5.78 or is there a way i can downgrade to 4.5.4.48? when i tried to it said you can downgrade

I did the same thing I need help too

**Comment by PrazgreenStudios** [comment]
so is this going to be patched?

**Comment by PinkHatGithub** [comment]
this was closed, stop asking about it
