### ISSUE TITLE
Ndless sdk install not working on mac.

### ISSUE THREAD

**Issue by hrtze** [ndless-nspire/Ndless#303]
I don't know where to ask this really, so I opened this. I am nearly sure that I installed all the depends correctly with brew for endless sdk installation, but every time I try to run build_toolchain.sh it spits out errors when it executes the makes at the end, specifically:

make[4]: *** [_saturate1UTA.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [multi-do] Error 1
make[2]: *** [all-multi] Error 2
make[1]: *** [all-target-libgcc] Error 2
make: *** [all] Error 2

I have tried multiple times to resolve the failed attempts, but cant figure it out, I think it might have something to do with gcc; that's the only thing that I can think of right now. Some help would be greatly appreciated, thanks.

:(

**Comment by adriweb** [comment]
Well there's an other error (the actual one) in the log somewhere before what you pasted. Can you find it and copy it here?

**Comment by hrtze** [comment]
I ended up making a linux vm and working on my projects there, this is probably an issue more with my computer than the code seen as no one else has reported to this issue, thanks for the help though!

**Comment by jkcoxson** [comment]
This is also an issue on my Mac, which seems to originate here
``arm-none-eabi-gcc -B/Users/jkcoxson/Local_Code/Ndless/ndless-sdk/toolchain/build/arm-none-eabi/thumb/newlib/ -isystem /Users/jkcoxson/Local_Code/Ndless/ndless-sdk/toolchain/build/arm-none-eabi/thumb/newlib/targ-include -isystem /Users/jkcoxson/Local_Code/Ndless/ndless-sdk/toolchain/download/newlib-3.0.0/newlib/libc/include -B/Users/jkcoxson/Local_Code/Ndless/ndless-sdk/toolchain/build/arm-none-eabi/thumb/libgloss/arm -L/Users/jkcoxson/Local_Code/Ndless/ndless-sdk/toolchain/build/arm-none-eabi/thumb/libgloss/libnosys -L/Users/jkcoxson/Local_Code/Ndless/ndless-sdk/toolchain/download/newlib-3.0.0/libgloss/arm  -mthumb -DPACKAGE_NAME=\"newlib\" -DPACKAGE_TARNAME=\"newlib\" -DPACKAGE_VERSION=\"3.0.0\" -DPACKAGE_STRING=\"newlib\ 3.0.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -I. -I../../../../../../download/newlib-3.0.0/newlib/libc/argz -D__NO_SYSCALLS__ -fno-builtin      -DHAVE_RENAME -DMALLOC_PROVIDED -DABORT_PROVIDED -DNO_FORK -mcpu=arm926ej-s -ffunction-sections -Ofast -funroll-loops -target x86_64-apple-darwin20.3.0  -mthumb -c -o lib_a-argz_append.o `test -f 'argz_append.c' || echo '../../../../../../download/newlib-3.0.0/newlib/libc/argz/'`argz_append.c
arm-none-eabi-gcc: error: x86_64-apple-darwin20.3.0: No such file or directory
arm-none-eabi-gcc: error: x86_64-apple-darwin20.3.0: No such file or directory
arm-none-eabi-gcc: error: x86_64-apple-darwin20.3.0: No such file or directory
arm-none-eabi-gcc: error: x86_64-apple-darwin20.3.0: No such file or directory
arm-none-eabi-gcc: error: unrecognized command-line option ‘-target’
arm-none-eabi-gcc: error: unrecognized command-line option ‘-target’
arm-none-eabi-gcc: error: unrecognized command-line option ‘-target’
arm-none-eabi-gcc: error: unrecognized command-line option ‘-target’
make[8]: *** [lib_a-argz_append.o] Error 1
make[8]: *** Waiting for unfinished jobs....
make[8]: *** [lib_a-argz_add_sep.o] Error 1
make[8]: *** [lib_a-argz_add.o] Error 1
make[8]: *** [lib_a-dummy.o] Error 1``

**Comment by Vogtinator** [comment]
The `-target x86_64-apple-darwin20.3.0` option makes no sense. Did you set `CFLAGS` or similar?

**Comment by jkcoxson** [comment]
No, I haven't touched anything besides setting library paths.

**Comment by Vogtinator** [comment]
What's the output of `env | grep darwin`?
