### ISSUE TITLE
CX CAS I 4.5.5.79 error?

### ISSUE THREAD

**Issue by Danke-Boi** [ndless-nspire/Ndless#305]
Is this OS version supported by any version of ndless? I updated the calc a little too far and now I get the error on line 58 message.

**Comment by adriweb** [comment]
That is indeed too recent and not supported by Ndless currently. 

Just to know, how did you get this version, did you update on purpose, but without knowing it was incompatible with Ndless?

**Comment by Danke-Boi** [comment]
I am the resident expert in Calculator hacking at my school lol, so I do this stuff a lot and it's all running together, 1 of 2 things happened, either our Physics teacher updated it to the newest version, or I did. I updated a CX II to the newest version as well, as my current calc is running the newest version as of a month ago, and I thought they hadn't updated it. Curse Texas Instruments for actually caring occasionally! I downloaded it from their website as I was too lazy to sort through 100's of files to fond it because I couldn't find it by searching.
