### ISSUE TITLE
Segmentation fault when starting GDB (arm-none-eabi-gdb)

### ISSUE THREAD

**Issue by SlyVTT** [ndless-nspire/Ndless#310]
Hi,

I am trying to use the GDB debugger (arm-none-eabi-gdb) to debug my program but I am not able to make it run using :
arm-none-eabi-gdb -ex "target remote :3333" prog.elf

It crashes instantaneously with a segmentation fault (core dumped). I guess it is version 10.1.0 as arm-none-eabi-g++/gcc are corresponding to that version. (even a simple "arm-none-eabi-gdb --version" to get the revision crashes with a segfault).

I am using Ubuntu 21.04.

I do not know if using versions from arm website may solve the problem without creating trouble with the SDK.

Any Idea ?

BR

Sly

**Comment by Vogtinator** [comment]
What's the output of `which arm-none-eabi-gdb` and `LD_TRACE_LOADED_OBJECTS=1 arm-none-eabi-gdb`?

Did you build the toolchain recently? If some system libs changed, it's possible that some of them became incompatible. Should be unlikely though.

**Comment by SlyVTT** [comment]
Hi Fabian,
Yes I am suspecting a kind of mix somewhere causing troubles.
I came back to a KUbuntu VM based on 20.04LTS and GDB is not crashing (it has some timeout issue but at least it works).

Will try to remove all GDB/ARM packages in my 21.04 install and restart from a clean install to check if it works better ?

Regarding your second question, I built it very recently (yesterday).

Will try that and update you.

BR and thanks one more time ;-)

Sly

**Comment by SlyVTT** [comment]
Hi Fabian,

Got the confirmation that the trouble was coming from a mix between Ubuntu's executable/libs and ones of Ndless.

I tried to remove many Ubuntu's packages without success so i restarted from a fresh minimum install of Ubuntu 20.04 to be able to master what is installed or not. Then rebuild completly the Ndless SDK/Toolchain.

And it is now working.

Thanks

Sly
