### ISSUE TITLE
Missing ndless_resources? even though it's IN THE CALCULATOR

### ISSUE THREAD

**Issue by StickyChannel92** [ndless-nspire/Ndless#311]
Attempting to install, can't install because "Missing ndless_resources.tns?", even though ndless_resources.tns is in there.

**Comment by lights0123** [comment]
Can you post a screenshot of your transfer software or a photo of your calculator screen showing its position? It needs to be in a folder named `ndless` in the root directory of your calculator.

**Comment by StickyChannel92** [comment]
![WIN_20210914_20_44_01_Pro](https://user-images.githubusercontent.com/48563620/133356779-7b661fec-b7d4-40c9-8622-f11e393bcf0a.jpg)

**Comment by lights0123** [comment]
You need to create a folder called "ndless" and place both the installer and resources in it.

**Comment by lights0123** [comment]
See a screenshot [here](https://tiplanet.org/forum/viewtopic.php?f=57&t=24264&p=256076#p256076).

**Comment by StickyChannel92** [comment]
It works! Thank you so much!
