### ISSUE TITLE
Adding linking support in gpsp-nspire

### ISSUE THREAD

**Issue by FerdinandoPH** [ndless-nspire/Ndless#312]
https://github.com/Vogtinator/gpsp/issues/8
I don't want to be annoying, but no one seems to be reading the issues in gpsp-nspire's github project, and since it is a ndless app and the author is the same, I thought I could get some answers here.

**Comment by Vogtinator** [comment]
> I don't want to be annoying, but no one seems to be reading the issues in gpsp-nspire's github project

I'm not familiar with the code and so far only did critical fixes. The repo is mostly for providing a place to get the latest version and for discussions.
