### ISSUE TITLE
Ndless 4.5.3-4.5.4 Installer fails to load/install properly 

### ISSUE THREAD

**Issue by toblerone567** [ndless-nspire/Ndless#320]
![image](https://user-images.githubusercontent.com/67667782/140622143-bc8ed5e1-8284-49d7-b54b-2e9cf3f41c1b.png)

I have OS version 4.5.5.79
The installer and resource were moved to /ndless but this error occurs.

Error

Page 1.1 has encountered an error.
Please contact the author with the following information.
Line 58:
cannot add or remove a shape, body, or constaint from this callback

**Comment by lights0123** [comment]
> Ndless 4.5.3-4.5.4 Installer

> I have OS version 4.5.5.79

Your OS version isn't supported yet.

**Comment by toblerone567** [comment]
> > Ndless 4.5.3-4.5.4 Installer
> 
> > I have OS version 4.5.5.79
> 
> Your OS version isn't supported yet.

Ohh alright
Is there any way to downgrade without ndless then?

**Comment by adriweb** [comment]
> Is there any way to downgrade without ndless then?

Nope

**Comment by toblerone567** [comment]
damn...
Thanks anyways
