### ISSUE TITLE
small image directory "bug" on ndless.me

### ISSUE THREAD

**Issue by RuralAnemone** [ndless-nspire/Ndless#321]
The "fork me on github" image on [ndless.me](https://ndless.me) refers to [aral.github.com/...](https://aral.github.com/fork-me-on-github-retina-ribbons/right-green@2x.png) (which doesn't exist) instead of [aral.github.io/...](https://aral.github.io/fork-me-on-github-retina-ribbons/right-green@2x.png) (which seems to be the correct image)

**Comment by Vogtinator** [comment]
That worked some time ago, did the location change recently?

**Comment by RuralAnemone** [comment]
Yeah, I'm assuming it did since http://aralbalkan.com/scribbles/fork-me-on-github-retina-ribbons/ (what I'm assuming is the source) hasn't updated yet either...
![image](https://user-images.githubusercontent.com/64103005/140978080-dfab8327-a9fe-4beb-8cc1-0e25bd35b5be.png)
![image](https://user-images.githubusercontent.com/64103005/140978117-c9b37a85-91f4-4e93-bd42-466dd822c2ed.png)
all of those images exist with the .io domain

**Comment by RuralAnemone** [comment]
all that to say,

yes
it did

**Comment by RuralAnemone** [comment]
‎
