### ISSUE TITLE
Error when making .tns files from .c and .h files

### ISSUE THREAD

**Issue by CamooCodee** [ndless-nspire/Ndless#324]
Hi everyone,
I have some C code that I would like to test on my Ti-Nspire. That's why I am trying to make a .tns. I have genzehn and nspire-gcc installed inside of Ndless/ndless-sdk/bin. However, I don't know why I am getting this error when executing `make` inside of my project directory:

`nspire-gcc  -Wall -W -marm -Os -c nSonic.c -o nSonic.o`
`make: nspire-gcc: No such file or directory`
`make: *** [Makefile:30: nSonic.o] Error 127`

(The project is called nSonic since I think it's a cool plugin and I want to extend it with a bit of custom functionality. Mainly in order to get into coding for the Nspire. It'll be personal usage anyway.)

I didn't modify the Makefile. It's the exact same as this one: [https://tiplanet.org/forum/archives/zipview.php?id=171136&zipFileID=18](url)
Line 30 is this snipped right here:
`$(GCC) $(GCCFLAGS) -c $< -o $@`

I've read that it might have something to do with '$PATH' and something not being in this path but I didn't really understand what to put in there. $PATH seems to just be a collection of default paths where programs are installed. Correct me if I'm wrong.

Finally, I put my project into the 'samples' folder in order to potentially provide any errors with finding directories. Sadly, everything ended with the same error message mentioned above.

Any help will be highly appreciated.

**Comment by adriweb** [comment]
Well it looks like the toolchain is not properly installed (or at the very least, your `PATH` environment variable doesn't have an entry to `Ndless/ndless-sdk/bin` which is necessary.

**Comment by CamooCodee** [comment]
@adriweb Yea that was the issue. I figured the rest out myself. Thanks a lot 👍
