### ISSUE TITLE
Assembler not working properly (nSonic)

### ISSUE THREAD

**Issue by CamooCodee** [ndless-nspire/Ndless#325]
Hello, I am having trouble working with nSonic and trying to compile it. There recently has been an update to it which should've fixed the issues. I now can compile the newly downloaded source code and the program works as expected on my calculator. Unfortunately the second I open a .c file and save it without changing the content, the .tns doesn't work and the calc crashes once I press 2 (open nSonic). In the Makefile, I tried setting debug mode to true which made the .tns build process fail. It's giving me this error:

`/tmp/cc6fJ4Tk.s: Assembler messages:`
`/tmp/cc6fJ4Tk.s:3602: Error: invalid constant (fffffffffffff898) after fixup`
`make: *** [Makefile:30: nSonic.o] Error 1`

When deleting the downloaded .o file and trying to let it generate a new one the make-process fails as well. So there has to be a problem with the assemler.

Downloading the code without opening any file apart from the Makefile in order to turn on debug mode doesn't throw any errors and successfully builds the .tns. I've tried other plugins but it only seems to happen with this plugin specifically.

I know, it's a really weird issue and hard to replicate, explain or debug. That's why I appreciate any help even more :D

There seems to be a problem with the assembler. I don't have any experience with assemblers myself so let me know if you need any additional information.

**Comment by Vogtinator** [comment]
What's the full command that produces the error message?

**Comment by CamooCodee** [comment]
I am executing the make command within the downloaded or downloaded and modified nSonic directory.

**Comment by spv420** [comment]
If I had to guess, it might be that the code is in Unix line format (LF), but you're opening it, and then saving it in Windows/DOS line format (CRLF), which the compiler / assembler / whatever in this case, is getting angry about. Try re-downloading it and checking if the file is in LF or CRLF, and setting your editor to use the same. 

Best of luck!

**Comment by CamooCodee** [comment]
Thanks for the reply but the code seems to be DOS and it's also saved as such. I am using Ubuntu if that matters.

It seems like there is a problem with the make or build process of the nSonic.o file. I guess it's trying to rebuild it whenever there is a modification done. 

I am currently trying out differenct SDK versions. Let me know if there is anything specifc that I should try in this regard.

**Comment by Vogtinator** [comment]
I can reproduce the issue with `DEBUG = TRUE`. It's simply that the function body of `HOOK_DEFINE` is too big, so that the relative address to a variable placed at the beginning does not fit into the instruction. Without `-O0`, the optimization makes it small enough that it fits.

**Comment by Vogtinator** [comment]
I was able to reproduce the crash as well. When building against the current SDK version, it hits https://github.com/ndless-nspire/Ndless/issues/287. The fix is to use `_exit(0);` in `main` when making it resident, instead of simply returning.

It might be possible to improve the way the hook mechanism stores the SP, but I don't think that's worth it, if not disabling optimizations is sufficient for all known cases for now.

**Comment by CamooCodee** [comment]
Thanks for the response. I don‘t get what you mean by the method body being too big. I tried looking it up but I couldn‘t find something similar to what you described (a maximum function size). Also what do you mean by „without `-O0`“ what is `-O0` and how can I get rid of it?

**Comment by adriweb** [comment]
Yes, the size of the function for the hook.
`-O0` is the optimization level that would be used for debug (supposedly, I didn't check). If you use a higher level, for instance `-O1` or `-O2`, even though it would make debugging quite a bit harder, it would make the generated asm smaller, just a bit so that it fits, apparently.

**Comment by CamooCodee** [comment]
So the function body is too long for the debugger only? That means everything that caused the crash is the return instead of the exit call, correct? I didn‘t get the chance to try it I just wanna make sure I try the right things.

**Comment by adriweb** [comment]
Not to the debugger, but the fact of building in debug (or at least with optimizations disabled, which is generally the case for debug builds).

But yeah, the exit thing is related to the crash.

**Comment by CamooCodee** [comment]
Thanks a lot for the help. The _exit call was the problem!
