### ISSUE TITLE
When will there be an update to support v5.4.0.257?

### ISSUE THREAD

**Issue by Fran7Ribeiro** [ndless-nspire/Ndless#327]

**Comment by Xandrzejak28** [comment]
I agree, I have an os 5.3, but my friend is using a 5.4, so can you at least make a ndless for 5.4, or at least an os downgrader that doesnt require ndless? Thanks, I have ADHD and have been obsessivly trying to figure this out for the whole day.

**Comment by adriweb** [comment]
Not available for now, so be sure to subscribe to github releases and/or regularly watch ndless.me

**Comment by Xandrzejak28** [comment]
ok, thanks

**Comment by Vogtinator** [comment]
Duplicate of #300
