### ISSUE TITLE
build_toolchain.sh taking hours to complete

### ISSUE THREAD

**Issue by TechCraft09** [ndless-nspire/Ndless#333]
I'm currently trying to compile the Ndless SDK but after following all the specified steps here:
https://hackspire.org/index.php/C_and_assembly_development_introduction
but build_toolchain.sh has been working for 5 hours straight. Does anyone know why this happens or if this is normal?

* Windows 10 21H2 (10.0.19044.1568)
* WSL 2 (all packages installed as far as I know)
* AMD Ryzen 5 1600

(also not because of disk speed)

**Comment by TechCraft09** [comment]
The folder ndless-sdk is currently at 6.88 GB if that is an issue

**Comment by adriweb** [comment]
That's probably fine under WSL. Give it a few more hours, I guess... at least it's not stuck.

**Comment by Vogtinator** [comment]
If you build inside a WSL volume that might suffer a lot from slow Windows I/O. On native linux this takes ~30min. You can try moving ndless onto native linux volumes, wherever they are in the WSL2 environment.

**Comment by TechCraft09** [comment]
I'm not running it on a WSL volume because of speed, but it has word after a total of 6 hours

**Comment by adriweb** [comment]
Well that's good to know.
