### ISSUE TITLE
can't build the toolchain

### ISSUE THREAD

**Issue by imadtg** [ndless-nspire/Ndless#337]
whenever i try and build the toolchain it throws some warnings at the end and then errors. i'm on win 10 using cygwin 
```
make[2]: *** [Makefile:1123: pex-unix.o] Error 1
make[2]: Leaving directory '/home/PC/Ndless/ndless-sdk/toolchain/build/libiberty'
make[1]: *** [Makefile:8073: all-libiberty] Error 2
make[1]: Leaving directory '/home/PC/Ndless/ndless-sdk/toolchain/build'
make: *** [Makefile:856: all] Error 2
```
full traceback : [https://pastebin.com/v4wgpZAY](url)

**Comment by Vogtinator** [comment]
Looks like binutils 2.34 is not compatible with Cygwin (anymore). However, the SDK uses newer binutils for quite some time now, so please try latest git master.

**Comment by imadtg** [comment]
now i get this
```
make[1]: Leaving directory '/home/PC/Ndless/ndless-sdk/toolchain/build'
make: *** [Makefile:1003: all] Error 2 
```

[https://pastebin.com/mVC4KKri](https://pastebin.com/mVC4KKri)

**Comment by Vogtinator** [comment]
https://stackoverflow.com/questions/32232495/binutils-build-fails-because-of-pex-unix-file suggests to pass `--build=i686-w64-mingw32` to the `configure` arguments to `binutils` and `gcc`.

Can you add that to `OPTIONS_BINUTILS` and `OPTIONS_GCC` in `build_toolchain.sh` and try again?

**Comment by imadtg** [comment]
to it's credit it did go alot further but still, i encounter this 
```
make[1]: Leaving directory '/home/PC/Ndless/ndless-sdk/toolchain/build'
make: *** [Makefile:1012: all] Error 2
```
[https://pastebin.com/nvfrxrQV](url)

**Comment by Vogtinator** [comment]
That's just `makeinfo: command not found`, install it and try again.

**Comment by imadtg** [comment]
now i get this
```
gcc.exe: error: /home/PC/Ndless/ndless-sdk/toolchain/build/bfd/.libs/libbfd.a: N
o such file or directory
make[4]: *** [Makefile:1041: objdump.exe] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/home/PC/Ndless/ndless-sdk/toolchain/build/binutils'
make[3]: *** [Makefile:1431: all-recursive] Error 1
make[3]: Leaving directory '/home/PC/Ndless/ndless-sdk/toolchain/build/binutils'
make[2]: *** [Makefile:875: all] Error 2
make[2]: Leaving directory '/home/PC/Ndless/ndless-sdk/toolchain/build/binutils'
make[1]: *** [Makefile:4031: all-binutils] Error 2
make[1]: Leaving directory '/home/PC/Ndless/ndless-sdk/toolchain/build'
make: *** [Makefile:1012: all] Error 2
```
[https://pastebin.com/jgsNN6zj](url)
thanks for your time anyway.

**Comment by Vogtinator** [comment]
Looks like Cygwin might be a dead-end then... Can you build it on Linux, e.g. inside WSL?

**Comment by imadtg** [comment]
that did the trick, thanks for your time.
