### ISSUE TITLE
Error while installing ndless

### ISSUE THREAD

**Issue by StickyChannel92** [ndless-nspire/Ndless#344]
Error

Page 1.1 has encountered an error. Please contact the author with the following information.

Line 58:
cannot add or remove a shape, body or constraint from this callback.

Files in root:\\ndless\
![image](https://user-images.githubusercontent.com/48563620/169150029-aa9bfce7-b010-4861-9c9a-1680abe18f23.png)

**Comment by Vogtinator** [comment]
Same as #300
