### ISSUE TITLE
problem ndless software 5.4.0 for ti nspire cx ii-t

### ISSUE THREAD

**Issue by rusha00** [ndless-nspire/Ndless#347]
i just bought the ti-nspire cx ii-t calculator; I tried to install the latest version ndless but it gives me an error. i have read that is not possible to make a downgrade, could anyone tell me when ndless version 5.4.0 will come out ??

**Comment by rusha00** [comment]
does anyone know when the new version of ndless will come out? Was there any communication?

**Comment by adriweb** [comment]
Nope - check out the linked issue to know how to subscribe to updates in the future.
