### ISSUE TITLE
arm-none-eabi-gcc: No such file or directory

### ISSUE THREAD

**Issue by DanThePman** [ndless-nspire/Ndless#35]
Hi,
I recently discovered this nice sdk.
Im using Windows 10 and I installed it with Cygwin.
Because a docker is needed to "make" the c/c++ files I used the one of docker.com.

Anyway, I followed the instructions of hackspire.com but instead of
`$ make
nspire-gcc -Wall -W -marm -Os -c hello-sdl.c
mkdir -p .
nspire-ld hello-sdl.o -o ./helloworld-sdl.elf 
genzehn --input ./helloworld-sdl.elf --output ./helloworld-sdl.tns --name "helloworld-sdl"
make-prg ./helloworld-sdl.tns ./helloworld-sdl.prg.tns`

I get

`Daniel@DESKTOP-3C5D8NA MINGW64 ~/Desktop/ndless/Ndless-master/ndless-sdk/samples/helloworld-sdl
$ make
nspire-gcc -Wall -W -marm -Os -c hello-sdl.c
/cygdrive/c/Users/Daniel/Desktop/ndless/Ndless-master/ndless-sdk/bin/nspire-gcc: Zeile 20: /c/Users/Daniel/Desktop/ndless/Ndless-master/ndless-sdk/toolchain/install/bin/arm-none-eabi-gcc: No such file or directory
Makefile:29: die Regel für Ziel „hello-sdl.o“ scheiterte
make: *** [hello-sdl.o] Fehler 127`

In the "bin/arm-none-eabi-gcc" directory are a couple of files located (also a file called arm-none-eabi-gcc) but they have got the extension .exe

Any tips?

**Comment by Vogtinator** [comment]
> Because a docker is needed to "make" the c/c++ files I used the one of docker.com.

No docker needed, plain cygwin is enough.

> In the "bin/arm-none-eabi-gcc" directory are a couple of files located (also a file called arm-none-eabi-gcc) but they have got the extension .exe

Is "bin/arm-none-eabi-gcc" a folder or is "bin/arm-none-eabi-gcc.exe" a file?

**Comment by DanThePman** [comment]
> Is "bin/arm-none-eabi-gcc" a folder or is "bin/arm-none-eabi-gcc.exe" a file?
It's the exe file in the bin folder, sorry.

> No docker needed, plain cygwin is enough.
As soon as I use the Makefile in the helloworld-sdl folder the following error appears because of the last line in the Makefile:
`ndless-sdk/bin-docker/nspire-docker: Zeile 18: docker: Kommando nicht gefunden.`

**Comment by Vogtinator** [comment]
Don't use the docker images, build the toolchain yourself.
The docker image is too old to be usable.

**Comment by DanThePman** [comment]
> Don't use the docker images, build the toolchain yourself.
> The docker image is too old to be usable.

Can you explain that to me, please?
After reinstalling the sdk with build_toolchain.sh, I can't build any c or c++ file because the command "genzehn" is unknown.
When I add "ndless-sdk\bin-docker" (the folder which contains genzehn) to the environment path, this particular error disappears but the console prints "docker command not found" afterwards.

**Comment by Vogtinator** [comment]
genzehn is under ndless-sdk/tools and installed into ndless-sdk/bin, which needs to be in your $PATH. Just ignore bin-docker completely.

**Comment by DanThePman** [comment]
Now I understand the problem.
Normally the genzehn file should be located in "ndless-sdk/bin" but for me the only file called "genzehn" exists in a bin-docker folder.
That's why I chose the wrong one everytime.

Probably it's because some files haven't been created and this file doesn't exist in the bin folder.
Hackspire says that I should run the Makefile in the ndless-sdk folder but when I do so, I'm getting the following error message:
`genzehn.cpp: In Funktion »std::string zehn_get_string(uint32_t, std::vector<unsigned char>&)«:
genzehn.cpp:36:73: Fehler: »strnlen« wurde in diesem Gültigkeitsbereich nicht definiert
     return std::string(start, strnlen(start, extra_data.size() - pos - 1));
                                                                         ^
genzehn.cpp: In Funktion »std::string zehn_get_string(uint32_t, std::vector<unsigned char>&)«:
genzehn.cpp:36:73: Fehler: »strnlen« wurde in diesem Gültigkeitsbereich nicht definiert
     return std::string(start, strnlen(start, extra_data.size() - pos - 1));
`

Im sure if I could install the the Makefile without those errors, the "real" genzehn file will be created.
But how to fix them?
cstring.h is already included in the cpp file that contains the error.

**Comment by DanThePman** [comment]
Found the problem.
Add
`size_t strnlen(const char *s, size_t max_len)
{
    size_t i = 0;
    for(; (i < max_len) && s[i]; ++i);
    return i;
}`
to genzehn.cpp

**Comment by Vogtinator** [comment]
Yeah, looks like strnlen isn't provided by MinGW.

**Comment by Vogtinator** [comment]
Fixed in git, please reopen if it's still broken somehow!
