### ISSUE TITLE
gPSP hardlocks on TI Nspire CX II

### ISSUE THREAD

**Issue by MuskettDev** [ndless-nspire/Ndless#350]
gPSP hardlocks on TI Nspire CX II when I am playing Dragon Ball Advanced Adventure v 5.2.0.771. I am using the gPSP launcher modified for TI Nspire CX II. I noticed that anytime I kill an enemy or press the L Button, the game freezes and I can't exist gPSP or go back to the File Explorer, all I'm left with is resetting the system each time. Although the game itself does load and run fine otherwise. For instance, if you play "One on One" mode in the menu and play against Krillin, the game runs just fine, although I didn't press L then.

I can also remember playing this game on version r2015 of ndless when it just came out and the game ran on my Nspire without this issue.

**Comment by Vogtinator** [comment]
> I can also remember playing this game on version r2015 of ndless when it just came out and the game ran on my Nspire without this issue.

Did you only upgrade Ndless compared to then or also the OS?

**Comment by MuskettDev** [comment]
I didn't upgrade the OS, just ndless.

**Comment by Vogtinator** [comment]
Ok, so can you go back to the r2015 `ndless_resources.tns` and check whether it still works? If yes, try r2016, r2017 and r2018 until it no longer works. Then we know which version introduced the incompatibility.

**Comment by MuskettDev** [comment]
It seems like this is just false speculation. As it turns out, I just used savestates before that is why I have a memory of progressing. When I kill enemies, it still freezes on the old releases.

I'm sorry for taking out of your time and hope I was not a huge bother.
