### ISSUE TITLE
Downgrading the Nspire

### ISSUE THREAD

**Issue by SophisticatedFox4** [ndless-nspire/Ndless#351]
Here @Vogtinator and everyone else, this article might interest you:
https://tiplanet.org/forum/viewtopic.php?t=17770&lang=en

**Comment by SophisticatedFox4** [comment]
Or just google "how to downgrade ti-nspire"

**Comment by unilock** [comment]
You need Ndless to downgrade your calculator, which you can't install unless you downgrade, making this pretty useless for the end user, unfortunately.

I do recall there being a way to downgrade an Nspire over RS232; does that still work?

**Comment by Vogtinator** [comment]
> You need Ndless to downgrade your calculator, which you can't install unless you downgrade, making this pretty useless for the end user, unfortunately.

Correct.

> I do recall there being a way to downgrade an Nspire over RS232; does that still work?

What you can do over RS232 is flash a different manuf/boot2/diags, for which there is no downgrade protection. That by itself doesn't let you downgrade the OS. What you might be thinking of is to use RS232 to downgrade boot2 and install nLaunch(y).

**Comment by SophisticatedFox4** [comment]
Maybe we should download the other file first.

**Comment by SophisticatedFox4** [comment]
I have never tried this yet.

**Comment by adriweb** [comment]
Also, this would not work on the CX II, btw.
