### ISSUE TITLE
Downgrading the Nspire

### ISSUE THREAD

**Issue by SophisticatedFox4** [ndless-nspire/Ndless#352]
Here is a very helpful youtube link explaining about the downgrade and a link.
https://www.youtube.com/watch?v=ZNBxjZNI10s

**Comment by SophisticatedFox4** [comment]
Unfortunately, the tiplanet link doesn't work anymore. Here is the new link:
https://tiplanet.org/forum/archives_list.php?id=OS+Nspire

**Comment by unilock** [comment]
This video is 9 years old. The method it describes no longer works, as the calculator now checks whether the user is trying to install an OS older than what's currently installed, and refuses to install it if so.

**Comment by SophisticatedFox4** [comment]
Oh, my bad. But perhaps the ti planet link works?

**Comment by SophisticatedFox4** [comment]
> This video is 9 years old. The method it describes no longer works, as the calculator now checks whether the user is trying to install an OS older than what's currently installed, and refuses to install it if so.

Also, we are trying to install an OS that is younger than what's currently installed, so maybe it might work.

**Comment by unilock** [comment]
The TI-Planet link does work, yes, but it's just an archive of OS installers for the TI-Nspire. The calculator won't let you install them, unfortunately.

> Also, we are trying to install an OS that is younger than what's currently installed, so maybe it might work.

Sorry, there must be a language barrier - I mean that the calculator won't let you install a version of the OS that was created before the version of the OS that is currently installed on the calculator.

Basically, at the moment, downgrading is completely impossible without installing Ndless, and you can't install Ndless without downgrading.
The only answer is to wait until Ndless is released for a newer version of the TI-Nspire OS.

**Comment by SophisticatedFox4** [comment]
Hmmm... Can you tell me when the newer version will come out?

**Comment by adriweb** [comment]
No, follow this repo's update in general to be notified (specifically #300)

**Comment by SophisticatedFox4** [comment]
Ok, Thanks!
