### ISSUE TITLE
Ndless_resources problem

### ISSUE THREAD

**Issue by SophisticatedFox4** [ndless-nspire/Ndless#355]
Just so you know, version 5.3.2.129 can't open ndless_resources.

**Comment by Vogtinator** [comment]
It's not a normal .tns file, so that's expected.

**Comment by SophisticatedFox4** [comment]
But Readme.md says that in order to uninstall ndless you must open ndless_resources.

**Comment by adriweb** [comment]
Yes, when Ndless is already installed. If it's not installed, you won't be able to open the file, so there's nothing to uninstall
