### ISSUE TITLE
Not many edits

### ISSUE THREAD

**Issue by SophisticatedFox4** [ndless-nspire/Ndless#359]
When will the new version come out? The latest edit was last month, can you hurry up, please? I want the update because now I have version 5.4.0. @Vogtinator Please hurry

**Comment by debrouxl** [comment]
Maybe English is not your native language, but it remains that this is yet another duplicate of #300 , which was pointed in the multiple previous duplicate issues you posted. Please read prior discussions, which show that Ndless releases are never pre-announced... and stop wasting the already scarce maintainer time having to read and close duplicate issues. Thanks in advance :)
