### ISSUE TITLE
Where is the graphical SDK?

### ISSUE THREAD

**Issue by MishaShapo** [ndless-nspire/Ndless#36]
The link on https://ndlessly.wordpress.com/ndless-for-developers/ leads me here, but I only see the CLI version of the SDK. Am I missing something? I apologize for the noob-ness of the question.

**Comment by Legimet** [comment]
It was removed. I think only one person was using it anyway.

**Comment by Vogtinator** [comment]
You probably mean the bundled version of SciTE.
It wasn't really useful anyway and likely broken anyway due to massive changes in the SDK.
To get your own "graphical SDK" just setup your favorite IDE that understands C and can run specified commands on build.

**Comment by MishaShapo** [comment]
I see. Alright, I was just wondering. Thank you for the clarification. I will just use the CLI commands. Thanks again for making Ndless a reality. :)
