### ISSUE TITLE
Default Makefile not including .h/.hpp

### ISSUE THREAD

**Issue by TechCraft09** [ndless-nspire/Ndless#360]
When compiling a project using ndless with the default `nspire-tools new <name>` Makefile, header files such as .h/.hpp aren't compiled or referenced. This can lead to errors such as:
```
header.c:1:10: fatal error: header.h: No such file or directory
    1 | #include <header.h>
      |          ^~~~~~~
compilation terminated.
```
Is there any way to include these files in the Makefile, so they can be detected automatically?
This is the Makefile I'm using: [Makefile.txt](https://github.com/ndless-nspire/Ndless/files/9491401/Makefile.txt)

**Comment by Vogtinator** [comment]
Header files don't need to be mentioned in the `Makefile` other than for dependency tracking. Just make sure that the directory containing `header.h` is included in the search path. If it's in the same directory as `header.c`, you should use `#include "header.h"`.

**Comment by TechCraft09** [comment]
Thanks, I fixed the issue with the -I option. I forgot, gcc needs the header file location instead of compiling it seperately.
