### ISSUE TITLE
Downgrade from 5.4.x to 5.3.x

### ISSUE THREAD

**Issue by Vainstains** [ndless-nspire/Ndless#361]
is it possible? this is a new calc I just got today, that came with 5.4.0.259. if it's not possible then:

A: will there ever in the future be a version supporting 5.4.x,
B: is there a place I can find aftermarket calcs with a specific version number, or
C: is there ANY way to write a .tns file, since I know there are existing "games", but they can't have come from nowhere.

this question is also for any random googles that find this issue.

**Comment by BBQGiraffe** [comment]
to answer question C, [Luna](https://github.com/ndless-nspire/Luna) is what you're looking for, [here](https://education.ti.com/html/webhelp/EG_TINspireLUA/EN/index.html) is the official documentation for the Lua API

**Comment by debrouxl** [comment]
A: see #300 and all of its recent duplicates :)
B: indeed, many aftermarket places make it possible for communicate with sellers so as to avoid buying a calculator already equipped with one of the OS versions not supported by Ndless.
C: the Ndless SDK for native code programs is part of this repository.

**Comment by Vainstains** [comment]
Thanks!
