### ISSUE TITLE
New version of Ndless for OS 5.4?

### ISSUE THREAD

**Issue by Link1122** [ndless-nspire/Ndless#363]
This question is for any members of the Ndless team. Are you working on a version compatible with CX Ii CAS OS 5.4? And do you have an estimate of when you'll be done? I'm trying to decide if I should return my calculator or not...

**Comment by Vogtinator** [comment]
Duplicate of #300

**Comment by adriweb** [comment]
If you really **can't** do without Ndless, yes I guess you can return it and try to buy a used one instead 🤷‍♂️
