### ISSUE TITLE
Questions about 5.4 (not an issue per se)

### ISSUE THREAD

**Issue by FredsMedia** [ndless-nspire/Ndless#374]
Hey all!

I was just wondering how support for 5.4 is coming along. I accidentally upgraded and I feel like my calculator is so basic now!
Also is there anything we as the community can do to help speed this process along?

Looking forward to hearing from you!
-FredsMedia

**Comment by Vogtinator** [comment]
Let's keep this topic in #300.

> Also is there anything we as the community can do to help speed this process along?

If there's any info that might be helpful, you can write a mail (don't post it publicly)
