### ISSUE TITLE
Ndless app library has shutdown.

### ISSUE THREAD

**Issue by ethkoth** [ndless-nspire/Ndless#376]
The app library for ndless has been shutdown as of december 16 2022 and from what I can tell there is no alternative libary. If there is please tell me.
![ndless rip](https://user-images.githubusercontent.com/118388147/217590271-3a36c8ca-fd29-46cc-9184-6bfa13ac0a51.PNG)

**Comment by ethkoth** [comment]
The database dump was also really confusing and unorganized, so I couldn't work out how to find apps in it.

**Comment by adriweb** [comment]
That isn't related to this repo, but anyway as mentioned in the notice he put, you can find programs on TI-Planet.org, CodeWalrus, ticalc.org...

**Comment by ethkoth** [comment]
Ok, thanks.
