### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by ElainaJeansonne** [ndless-nspire/Ndless#381]
Is anyone working on upgrading Ndledss? I would like to help if possible, but I am not familiar with the TI programming...

**Comment by debrouxl** [comment]
Duplicate of #300 ...

**Comment by Vogtinator** [comment]
> I would like to help if possible, but I am not familiar with the TI programming...

Unfortunately that won't be easy, some reverse engineering of ARM assembly is required for that.

**Comment by PinkHatGithub** [comment]
oh dam. alr then
