### ISSUE TITLE
msleep() link is invalid

### ISSUE THREAD

**Issue by miracade** [ndless-nspire/Ndless#388]
In the code for msleep(), the [link](https://github.com/ndless-nspire/Ndless/blob/93b33530440428245d10a33e69a63cd33dc24460/ndless-sdk/libndls/sleep.c#L40) to the documentation for the timer module no longer works. 

I think I've found the hardware info on hackspire, as well as the updated documentation.

If I'm not wrong, then the documentation for the SP804 can still be found at
[https://developer.arm.com/documentation/ddi0271/d/](https://developer.arm.com/documentation/ddi0271/d/).

Alternatively, [here](https://documentation-service.arm.com/static/5e8e2102fd977155116a4aef) is a static PDF version.

**Comment by Vogtinator** [comment]
> I've found the hardware info on hackspire, as well as the updated documentation.

Looks like the link on hackspire is also broken...

Will you open a PR?

**Comment by miracade** [comment]
Sure, here it is: https://github.com/ndless-nspire/Ndless/pull/389
(I'm still kind of new to pull requests, did I do it right?)

**Comment by Vogtinator** [comment]
Thanks, looks good! Making edits and commits using the GH Web UI is rather limited and unusual (using git locally is the "normal" way) but is fine for smaller changes like this.
