### ISSUE TITLE
Question regading PATH

### ISSUE THREAD

**Issue by Eiyeron** [ndless-nspire/Ndless#39]
Hi, I recently remarked something about the way Ndless sets its equivalent of PATH, and something that could be added.

For now, what we have is the ability to use the executable's current folder as the equivalent of PWD for local paths. It's pretty useful but raises possible issues with files opened automatically with the extension association when porting or programming stuff with computer habits. For instance, when one executes a script in a (computer) OS environment, the PWD is the script's folder where Ndless doesn't. This, for instance, is currently blocking nSquirrel from being able to bundle a script with its data in its own folder and would force it to be in the same folder of the executable (and ultimately `ndless/` in most cases). This isn't a unfixable issue from my side, yeah (I'd just have to colelct the script's path from `argv) but it's a undocumented quirk that should be at least indicated for further reference, nah?

**Comment by Vogtinator** [comment]
> For instance, when one executes a script in a (computer) OS environment, the PWD is the script's folder where Ndless doesn't

This is not true at all.

```
fvogt@linux-lm3i:/opt> echo "pwd" > /tmp/script.sh
fvogt@linux-lm3i:/opt> chmod u+x /tmp/script.sh
fvogt@linux-lm3i:/opt> /tmp/script.sh
/opt
```

> This, for instance, is currently blocking nSquirrel from being able to bundle a script with its data in its own folder and would force it to be in the same folder of the executable (and ultimately ndless/ in most cases).

See https://hackspire.unsads.com/index.php/Libndls#Filesystem

**Comment by Eiyeron** [comment]
Yeah sorry, I had an issue with my mind right now (also, maybe getting another way to contact would be interesting to avoid cluttering the issue tracker with such issues). What I had in mind was *clickling* on a script as you would in a UI. I expected the PWD to become the folder's because it's like what it seems to do (at least on Windows). Also, we already talked about the `enable_relative_paths` function, but it only does this for the executable name.

Sorry for the misunderstanding.

**Comment by Vogtinator** [comment]
> Yeah sorry, I had an issue with my mind right now (also, maybe getting another way to contact would be interesting to avoid cluttering the issue tracker with such issues)

IMO this place is good, as it's central and has a user- and search-engine friendly UI.
On CW/omni/TI-P it may get lost deep in the archives.

> What I had in mind was clickling on a script as you would in a UI

So, the document browser? That's exactly what enable_relative_paths does. It chdir's to the the parent dir of the script.

> Also, we already talked about the enable_relative_paths function, but it only does this for the executable name.

I vaguely remember that, what do you mean by "only [...] for the executable name"?

**Comment by Eiyeron** [comment]
>So, the document browser? That's exactly what enable_relative_paths does. It chdir's to the the parent dir of the script.
It doesn't. In my configuration I have : 
```
main/
- sokoban.nut # The file executed
- character.bmp # The file to be loaded
...
ndless/
- sq # nSquirrel's executable
```

After registration, when launching sokoban.nut, it doesn't find character.bmp, but if I put sq in main and register it again, it does find character.bmp.

**Comment by Vogtinator** [comment]
Of course, the script in this case is /documents/ndless/sq.

It calls

```/documents/ndless/sq /documents/main/sokoban.nut``` so $PWD is going to be /documents/ndless.

To implement the behaviour you want, you need to do it yourself. That's the same on all platforms (Linux, Windows, OS X).

**Comment by Eiyeron** [comment]
I must be tired to make such thinking mistakes. Thanks for the help.
