### ISSUE TITLE
Will we be getting 5.4 support?

### ISSUE THREAD

**Issue by retroprestoz** [ndless-nspire/Ndless#392]
Just got the nspire cx2 and made the mistake of getting the newest version without thinking about. Is a 5.4 version being worked on in any capacity to be released?

Also, just a quick question, why is a completely different release required for every OS version? I'm assuming it's something to do with the OS itself but just wondering.

**Comment by adriweb** [comment]
Dup of #300 

and yes it's because it's OS-specific, ti patches the bugs in each version

**Comment by retroprestoz** [comment]
> Dup of #300
> 
> and yes it's because it's OS-specific, ti patches the bugs in each version

Interesting. Pretty weird how they're so locked down with the software.
