### ISSUE TITLE
Ndless not working on version 6.0.3

### ISSUE THREAD

**Issue by Benjabeen** [ndless-nspire/Ndless#398]
I know that Ndless doesn't support 6.0.3 yet, but I still want to mention that because I bought an nspire cx ii-t to use Ndless on it, just to find out that it would have to be on an older version.

**Comment by Marcus5408** [comment]
this is on any os version greater than the one in the README, like version 5.4.0.29
![image](https://github.com/ndless-nspire/Ndless/assets/46655509/946ae2d8-43d2-4e8d-afec-815abd3429bd)
![image](https://github.com/ndless-nspire/Ndless/assets/46655509/76ed6564-96d4-4ace-b859-280a37ddf8ea)

**Comment by Vogtinator** [comment]
Same as #300...
