### ISSUE TITLE
Not Working!

### ISSUE THREAD

**Issue by leoniscool101** [ndless-nspire/Ndless#40]
Whenever I click ctrl and w to install Ndless, it sends me back to the home screen. I can't seem to fix it. Can I get some help?

**Comment by Vogtinator** [comment]
What are your OS version and hardware revision?
Have you tried the installation directly after a reboot?

**Comment by leoniscool101** [comment]
I have a TI-Nspire cx cas OS 4.2.0.532
Yes I have tried installation directly after reboot
Hardware revision is HW-W, I think that is what hardware revision is

**Comment by Vogtinator** [comment]
Have you tried the newest installer?

**Comment by leoniscool101** [comment]
Yea, I've tried deleting the installer along with the resource and cfg, then deleting the whole file on my computer, and downloading it again.

**Comment by Vogtinator** [comment]
Is there a vertical bar visible on the installer?

**Comment by leoniscool101** [comment]
There are two weird glitchy bars on my screen, one horizontal and one vertical.

**Comment by leoniscool101** [comment]
Where is it supposed to be in?

**Comment by leoniscool101** [comment]
OK, so I moved the files to a folder and it now says it is installed.
Thanks for everything

**Comment by leoniscool101** [comment]
Keep up the work!

**Comment by Vogtinator** [comment]
I'm glad it's working for you now.

> Keep up the work!

I'll try :-)
