### ISSUE TITLE
Where to download OS version 5.2.0.771 for CX II?

### ISSUE THREAD

**Issue by Hed0nium** [ndless-nspire/Ndless#400]
Note: I already have ndless installed.

Sorry that is not directly related to ndless but I need to downgrade to 5.2.0.771 from 5.3.0.564 using backspire.

KhiCas exam mode said it's not compatible with 5.3.0.564 so I need 5.2.0.771.

Only problem is that I don't know where to get 5.2.0.771.

I checked TI Planet (https://tiplanet.org/forum/archives_list.php?order=id&cat=OS+Nspire#files) and I saw some files that say 5.2 but not exactly 5.2.0.771.

Only reason why I'm asking here is because I don't want to make a mistake and forever ruin my ndless compatibility. Getting this question answered might help other people too.

**Comment by adriweb** [comment]
This is indeed not related to Ndless but anyway there's only this 5.2 so you're fine.
