### ISSUE TITLE
Firmware 6.00 Nspire CX II CAS compatibility?

### ISSUE THREAD

**Issue by d1ddle** [ndless-nspire/Ndless#403]
Looking to purchase a TI Nspire CX II CAS but unsure if ndless supports it since ndless website doesn't say anything about fw 6 and the Amazon listing could be loaded with the newest firmware 6.00
https://www.amazon.co.uk/Texas-Instruments-Nspire-Graphing-Calculator/dp/B07RL7HM5V?th=1
https://education.ti.com/en/software/update/ti-nspire-software-update/nspire-download?q1=cx-II-cas-hh&count=1
Many thanks

**Comment by PinkHatGithub** [comment]
The Newest models ( what you would be purchasing) do not support ndless
unfortunately, if you are looking to buy a CX II CAS with ndless
campabitility aim for OS 5.3.0.564 or lower

**Comment by Vogtinator** [comment]
If an OS version is not listed, it's not supported.
