### ISSUE TITLE
Are you working on a new ndless

### ISSUE THREAD

**Issue by Valaxe** [ndless-nspire/Ndless#406]
i know you gonna close this ticket and say its a dupe of #300 but just give this community and answer of wether or not you've abandoned ndless or if your still working on it just doesn't have a backdoor yet or something and if you do not want to explain at least give us a yes or no on wether or not we will someday get a new ndless,

**Comment by ExpertPhisherman** [comment]
Stop asking

**Comment by Valaxe** [comment]
I will once we get a definitive answer since it has been a year almost since they have said anything about the newer versions

**Comment by ExpertPhisherman** [comment]
Join the discord and try your luck there (it’s already been answered countless times) https://discord.gg/qjtgqxAkgV

**Comment by Valaxe** [comment]
shit didnt know that was a thing fuck sorry mods and vog
