### ISSUE TITLE
Guys I can't get my light to flash on my n-spire cx ii-t

### ISSUE THREAD

**Issue by Hoolaf** [ndless-nspire/Ndless#416]
For several hours I've been trying to make my calculator's led flash for the game I'm developing but I can't. I code in c and I found this example on the net 
*(volatile uint32_t*)(0x90000010) &= ~(1<<4);
while(!any_key_pressed()) {
    *(volatile uint32_t*)(0x90000014) &= ~(1<<4);
    sleep(2000);
    *(volatile uint32_t*)(0x90000014) |= 1<<4;
    sleep(2000);
}

**Comment by Vogtinator** [comment]
The LED is special, it's got some protections around it, as it is meant to show whether Press-To-Test is active. On the classic calcs it was relatively easy to control, on the CX it got harder and IIRC the CX II made some more changes on top.

**Comment by Hoolaf** [comment]
Oh ok it's nice it's going to be hard, have you tried doing it?

**Comment by adriweb** [comment]
Considering this has direct cheating-related applications (exam mode uses
this and is now required in many countries) and the Ndless team does not
condone cheating, you won't get help for this...

**Comment by Hoolaf** [comment]
AH sorry these not serious I will continue but research my cotes these nice to have helped me [Vogtinator](https://github.com/Vogtinator):)

**Comment by Hoolaf** [comment]
Just one last question: how did you observe this protection?

**Comment by Vogtinator** [comment]
TBH I haven't tried doing anything with the LED on CX II (not even CX IIRC), it's just not that useful.

> Just one last question: how did you observe this protection?

https://www.omnimaga.org/ti-nspire-projects/led-protection-in-ti-nspires-partially-cracked/

There's probably more stuff floating around somewhere, but probably incomplete and boring.
