### ISSUE TITLE
Asking about ndless update

### ISSUE THREAD

**Issue by wilkowskyy** [ndless-nspire/Ndless#417]
I bought a ti-nspire cx cas calc with os version 4.5.5. Im asking if update will come out one day to support the newest version?

 If not i may try using the usb to serial adapter and downgrading my os that way.
 I will be really grateful if some of you have tips and things to avoid while downgrading os.

**Comment by reoccurcat** [comment]
Duplicate of #300, wish this would stop getting asked because it clogs up people's emails
