### ISSUE TITLE
Programs with headers generated by make-prg do not run unless compressed

### ISSUE THREAD

**Issue by t3mp0r4ry23** [ndless-nspire/Ndless#418]
Programs built with the default Makefile or any other method that results in `make-prg` being run on a zehn binary that was generated without the `--compress` flag is unable to run on my calculator.

In all situations, compilation occurs without error, however:
- When attempting to run an uncompressed program generated with headers from `make-prg`, the compatibility warning pop-up appears, after which pressing okay the screen warps for a split-second, then returns to normal, which implies the program exited for some reason
- When attempting to run an uncompressed program without headers from `make-prg` (as in the generated zehn binaries that would normally be deleted by the default Makefile), the program runs as expected
- When attempting to run a compressed program (with or without headers from `make-prg`), the program runs as expected

For reference:
- I am using the latest version of the Ndless SDK
- My calculator is using the latest release of Ndless
- My calculator is a TI-Nspire CX II running OS version `5.2.0.711`
- This issue consistently occurs, including with programs that should run fine (e.g. the samples included with the SDK)

Any insight would be appreciated.
Thanks for developing and maintaining such a cool project!

**Comment by Vogtinator** [comment]
The plain zehn binary and compressed make-prg output do not trigger the compatibility warning?

If so, the binary loader in Ndless is apparently unable to find the real Zehn header after the make-prg stub. The relevant code is here: https://github.com/ndless-nspire/Ndless/blob/e07d8056ca5216d690ee9582e2c572c5c708e234/ndless/src/resources/ploaderhook.c#L96

It gives up after the first `Zehn 0x00000001` signature match, maybe there's a false positive within the stub? Can you attach an affected file?

**Comment by Vogtinator** [comment]
The other issue is that the program doesn't run correctly. That might be a side effect of the lcd_compat mode, but could also be an independent issue.

**Comment by t3mp0r4ry23** [comment]
Here's an affected file, along with its source and Makefile
[nspire-test.zip](https://github.com/ndless-nspire/Ndless/files/15337094/nspire-test.zip)

**Comment by t3mp0r4ry23** [comment]
Looking at the file in a hex editor, it seems like the generated make-prg stub resulted in the `Zehn 0x00000001` signature being offset by one byte, thus making it impossible for the function to find it, as it's no longer aligned to the 4 byte chunks the search uses.

**Comment by t3mp0r4ry23** [comment]
Resolved by recompiling `zehn-loader.tns`, I'm guessing just something weird happened when first I first compiled the SDK. (I had a couple of power issues going on at the time, if memory serves)

**Comment by Vogtinator** [comment]
It's actually a valid issue. While there was an attempt to ensure that the file is padded properly, that didn't work.
I assume it ended up aligned properly by accident, probably because it all ended up in `.text` anyway.

Please give https://github.com/ndless-nspire/Ndless/pull/419 a try, it should at least not break it.

**Comment by legimet** [comment]
I was getting back into Nspire development and encountered this same issue. I can confirm that #419 fixes the padding of zehn_loader.tns.
