### ISSUE TITLE
Reboots when CTRL+W is pressed

### ISSUE THREAD

**Issue by jhanlo** [ndless-nspire/Ndless#43]
Hello,

I have firmware 4.0.0.235. I have tried installing the 4.0.3 installer and the 4.2.0 installer with no avail. They are placed in the correct folder in the correct  location but when I try to press CTRL+W it simply reboots my calculator. Any help will be much appreciated. My serial ends with P-0313J btw.

**Comment by Vogtinator** [comment]
You need to install either OS 4.0.3 or 4.2.0, 4.0.0 is not supported.

**Comment by jhanlo** [comment]
Ok got it running, thank you.
