### ISSUE TITLE
HW-W+ compatibility layer: linuxloader doesn't work (yet!)

### ISSUE THREAD

**Issue by laci420** [ndless-nspire/Ndless#49]
Hello!

I have hardware revision X (yes, X the newest one ! - ) with the updated boot1 and the new LCD. The compatibility layer mostly works fine, however when i try to run Linux on it (with linuxloader), it just gives me a blank screen and freezes. 

Also, on an unrelated note, on version 4.0.3 i can't install ndless (reboots when i press the 'w' key). I don't know why this happens... Could it be the updated boot1?

Is there any way to solve the linux issue (either trough ndless or updating the linuxloader)? 
Thanks in advance

**Comment by Vogtinator** [comment]
> when i try to run Linux on it (with linuxloader), it just gives me a blank screen and freezes.

linuxloader itself uses nspire-io for display output, which does not support HW-W.
Linux itself does not support HW-W either and can't be fixed by compatibility modes in ndless as linux completely removes everything which is not itself from RAM.

> Also, on an unrelated note, on version 4.0.3 i can't install ndless (reboots when i press the 'w' key). I don't know why this happens... Could it be the updated boot1?

Ndless 4.0.3 does not support HW-W+.

**Comment by laci420** [comment]
But how can the linux issue be fixed? Should i create a issue over at https://github.com/tangrs/nspire-linux-loader2 ?

**Comment by Vogtinator** [comment]
It needs a new devicetree and a new "cx-cr4" lcd-type in https://github.com/torvalds/linux/blob/master/arch/arm/mach-nspire/clcd.c

**Comment by laci420** [comment]
Thanks a lot! i'll look into it and i think i'll code it myself!
