### ISSUE TITLE
Ndless 4.2 doesn't work/stuck in loading screen after starting gbc4nspire

### ISSUE THREAD

**Issue by ShoootLight** [ndless-nspire/Ndless#50]
When I try to install Ndless 4.2, the calculator just reboots after pressing Crtl-W (the document looks exactly the same like in the linked installation guide (https://i.imgur.com/h6fW5Sq.png))and after the reboot it hasn't the green text "Ndless installed" in the top-left corner (hope dies at last). I tested it with Ndless 4.2 and 4.0.3 and the ressources inside the archive (https://tiplanet.org/forum/archives_voir.php?id=44445). At the first time it just returns to the homescreen. There were 2 new files but no green text. In order to uninstall it (I tried first to run the ndless_resources.tns with a result of an error message) I deleted all files that I saw (the both installers, ressources, themes and the logs) trough TI-Nspire ™ Computer Link Software, I also used it to move all files to the device.
I got the TI-Nspire CX (P-1015W) with the version 4.0.3.29
Thanks in advance and sorry for my bad english

**Comment by adriweb** [comment]
"Ndless 4.2" [...] "version 4.0.3.29"
I guess you can figure out what to do ;)

**Comment by ShoootLight** [comment]
I'm sorry I can't, I got this thing 1 day ago and don't know the basics

**Comment by adriweb** [comment]
You just have to update to OS 4.2 (from [here](https://tiplanet.org/forum/archives_voir.php?id=435379) for instance) then try again.

**Comment by ShoootLight** [comment]
How do I do this?

**Comment by adriweb** [comment]
Plug your calculator, launch the computer [link] software, drag'n'drop the os file onto the calc in the software

**Comment by ShoootLight** [comment]
Thank you very very much :)
One more question I'm looking for a source for the basics of the calculator and for applications (gba emulator :D) for the jailbreak. Do you have useful sites or something like that?

**Comment by adriweb** [comment]
For instance, https://tiplanet.org/forum/archives_cat.php?cat=Nspire , https://ndless-apps.org ...

**Comment by ShoootLight** [comment]
Thanks :D are there incompatibilities because of the new screen or sth.?

**Comment by adriweb** [comment]
Yep, starting with your calculator revision (W)

**Comment by ShoootLight** [comment]
OK, then thanks (again) for your really quick help :)

**Comment by ShoootLight** [comment]
I have another problem: I tried to install gbc4nspire and the whole screen had graphical issues (https://cloud.githubusercontent.com/assets/17526972/13492805/81dbaf0e-e13a-11e5-8749-cc16b6c48689.jpg), pressing Crtl + on coloured the screen to green and after pressing the reset button I was stuck in the loading screen. Then I opened the EE + doc + enter menu, deinstalled the OS (Option 4) and through the link software I reinstalled it with this file https://tiplanet.org/forum/archives_voir.php?id=435379 and it still stucks in the loading screen :(
I really appreciate a fast answer

**Comment by ShoootLight** [comment]
The EE + enter + doc menu is still accessable

**Comment by ShoootLight** [comment]
Shall/Can I try to install another Version like 4.0.3.29?

**Comment by ShoootLight** [comment]
The problem has been done. After the battery was dead I plugged it into my computer and the thing just started right and seems to work.
