### ISSUE TITLE
Mouse support

### ISSUE THREAD

**Issue by Waishon** [ndless-nspire/Ndless#51]
Hello,

does ndless provide a mouse integration? Your website is saying "Plug in USB keyboards and mice.".
I tried it using an Mini USB Adapter to connect my mouse to the TI NSpire CX CAS, but it doesn't work. No mouse movements and a keyboard won't work, too. I tried also the old Hidn-USB driver which doesn't work.

So for further debugging it would be interesting if you haven't implemented a mouse integration yet or if my adapter cable is broken.

**Comment by Vogtinator** [comment]
Ndless itself does not provide mouse integration. HIDn has the drivers for it, it should still work fine. Which OS and HW are you using? Do you get a message that the device is not supported when you plug the mouse in without having ndless installed? If not, your cable is either broken or the wrong kind.
