### ISSUE TITLE
Hardware Revision Y

### ISSUE THREAD

**Issue by ZdidasZ** [ndless-nspire/Ndless#53]
My Nspire Cx non CAS has software 4.2.0 but the hardware revision is Y. The calculator is really new so that might be why. i have installed ndless 4.2 but if I try to run any apps, an error message appears saying ndless is not compatible with the hardware. I have the latest version of ndless which is supposed to work with 4.2.0 so the problem must be with this new hardware revision, as I cannot find anyone online with a Y at the end of the P- number string at the back of their calculator. Is there a solution? if not when will Ndless be compatible with this hardware revision?

**Comment by ZdidasZ** [comment]
"Ndless- Activating compatibility mode. This application has not been updated to work with your hardware. You may run into weird issues!" that is the message my calculator shows when i try to launch ANY app and the app never works.

**Comment by Vogtinator** [comment]
Ndless 4.2 on HW-Y is reported to work fine, the message window is intentional.
Most apps should still work.
What happens if you launch "ndless_resources.tns" itself?

**Comment by ZdidasZ** [comment]
"Do you really want to uninstall Ndless r2006? The device will reboot." that message appears

**Comment by Vogtinator** [comment]
This means that the compatibility mode is only activated when needed. Which applications don't work with the compat mode?

**Comment by ZdidasZ** [comment]
gbc4nspire does not work, nQuake says "could not load gfx.wad". i have tried the last mission just now and that seems to work fine. I will go and check more apps.

**Comment by ZdidasZ** [comment]
Nespire just froze my calculator so I had to reset it

**Comment by adriweb** [comment]
Speaking of the hw-revision, what's the datecode? From what we know so far, it's probably somewhere between 0416 and 0716.

**Comment by adriweb** [comment]
@ZdidasZ Speaking of the hw-revision, what's the datecode before the 'Y'? From what is known so far, it's probably somewhere between 0416 and 0716.

**Comment by BrandonLundh** [comment]
Any update on this? Ndless 4.4 dropped today. Has anyone tried it on rev. Y yet? I can’t find anything in the release notes that confirms or denies support for W or later revisions.

**Comment by adriweb** [comment]
Works just fine on a Y I have.

**Comment by BrandonLundh** [comment]
@adriweb I went ahead and tried and it did work, but in compatibility mode. I’ve only been successful using one app in that mode.

**Comment by Legimet** [comment]
Hardware revisions W and later have a new LCD. A lot of programs haven't been 
updated to support the new LCD, so Ndless includes a compatibility layer. Some 
programs might not work with the compatibility layer, and you'll have to ask 
the author to update them, or do it yourself.

**Comment by Vogtinator** [comment]
Everything works as expected on Ndless' side.
