### ISSUE TITLE
Support for OS 4.4

### ISSUE THREAD

**Issue by VegaRoXas** [ndless-nspire/Ndless#57]
Using ndless worked flawlessly on some older version I had. Today in class the calculator was somehow turned off so I turned it on. It just said System Error so I reinstalled the os. It seems like there's a new 4.4 os now which I now have installed on my calculator :/ I remember reading something about UART at the bottom connection of the calculator, am I somehow able to downgrade? I am on hardware revision U

**Comment by organism-in-charge** [comment]
Downgrading was restricted in the new OS.

**Comment by Vogtinator** [comment]
Fixed!
