### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by jussipu** [ndless-nspire/Ndless#60]
What is a problem?

$ make
make -C ndless-sdk
make[1]: Entering directory '/home/jussi/Ndless/ndless-sdk'
make -C libsyscalls
make[2]: Entering directory '/home/jussi/Ndless/ndless-sdk/libsyscalls'
php mkStubs.php > ../include/syscall-decls.h
/bin/sh: 1: php: not found
Makefile:23: recipe for target 'stubs.cpp' failed
make[2]: *** [stubs.cpp] Error 127
make[2]: Leaving directory '/home/jussi/Ndless/ndless-sdk/libsyscalls'
Makefile:13: recipe for target 'build-libsyscalls' failed
make[1]: *** [build-libsyscalls] Error 2
make[1]: Leaving directory '/home/jussi/Ndless/ndless-sdk'
Makefile:19: recipe for target 'build-ndless-sdk' failed
make: *** [build-ndless-sdk] Error 2

**Comment by Vogtinator** [comment]
You need to install php.

**Comment by jussipu** [comment]
Thanks! :)
