### ISSUE TITLE
Can't install ndless-sdk toolchain with build_toolchain.sh

### ISSUE THREAD

**Issue by AlekMabry** [ndless-nspire/Ndless#61]
Hello!
I am using Ubuntu 16.04, and I am trying to install the Ndless-SDK. The instructions say to go into Ndless/ndless-sdk/toolchain/ and run './build_toolchain.sh.' However when I run './build_toolchain.sh' I get:
Building and installing to '/home/alek-ubuntuparallel/Ndless/ndless-sdk/toolchain/install'...
./build_toolchain.sh: 50: ./build_toolchain.sh: makeinfo: not found
makeinfo (texinfo) dependency seems to be missing!

And yes, I did use: 'git clone --recursive https://github.com/ndless-nspire/Ndless.git' I've also installed all the required packages.

**Comment by Vogtinator** [comment]
> I've also installed all the required packages.

Apparently you did not:

> makeinfo (texinfo) dependency seems to be missing!

**Comment by AlekMabry** [comment]
OH I thought makeinfo was a makefile for some reason, it ran properly now. However when I run 'make' in the ndless-sdk folder I now get:

make[1]: Entering directory '/home/alek-ubuntuparallel/Ndless/ndless-sdk/libsyscalls'
php mkStubs.php > ../include/syscall-decls.h
/bin/sh: 1: php: not found
Makefile:23: recipe for target 'stubs.cpp' failed
make[1]: *** [stubs.cpp] Error 127
make[1]: Leaving directory '/home/alek-ubuntuparallel/Ndless/ndless-sdk/libsyscalls'
Makefile:13: recipe for target 'build-libsyscalls' failed
make: *** [build-libsyscalls] Error 2

I think the problem has to do with this:
export PATH=:"~/Ndless/ndless-sdk/toolchain/install/bin:~/Ndless/ndless-sdk/bin:${PATH}"
Did I configure this correctly?

**Comment by adriweb** [comment]
(it turns out texinfo wasn't actually needed, the check is being removed in a PR)

> /bin/sh: 1: php: not found

Now, install php...

**Comment by Legimet** [comment]
On Ubuntu, you can install the package `php-cli`.
