### ISSUE TITLE
Keyboard layout?

### ISSUE THREAD

**Issue by Irides-Chromium** [ndless-nspire/Ndless#67]
Currently, it seems that the keyboard mapping is a little different in Ndless C programs than in the documents, and the project doesn't give a layout for the characters (especially for the special signs like `@`, `&`, `[]{}` etc.). I've tried to look into the source code, but I cannot find the part where the keys are mapped. Is there actually a part of Ndless, or is it built-in? Can I configure my own layout (by a configuration file or embedded in code)? THANKS!

**Comment by Legimet** [comment]
The list of keys is here: https://github.com/ndless-nspire/Ndless/blob/master/ndless-sdk/include/keys.h. The Ndless SDK provides a library function `isKeyPressed` to tell if a particular key is pressed. It doesn't provide any specific way to input characters (unless you use the msgbox functions) and different programs can do different things.

**Comment by Irides-Chromium** [comment]
Isn't that in the SDK? So you mean that the layout is embedded when the sdk compiles my program? 'cause I'm wondering like what determines the output when I press <kbd>Ctrl</kbd>+<kbd>.</kbd> (it currently outputs <kbd>:</kbd>).

**Comment by Legimet** [comment]
The Ndless SDK just provides a way to check whether a particular key is pressed. The program can choose what to do with that information. The program you are talking about apparently checks that the <kbd>Ctrl</kbd> and <kbd>.</kbd> keys are pressed, and prints : on the screen. If you want to change this behavior, you will have to modify the program (or perhaps a thirdparty library that it uses).

**Comment by Irides-Chromium** [comment]
Sorry, it is <kbd>Shift</kbd> + <kbd>.</kbd>. Anyway, the program I want to talk about is the `newlib-c++` project in the Ndless SDK samples. The source obviously doesn't map the keys, and I've checked that if you press <kbd>Shift</kbd> + <kbd>.</kbd> in a normal nspire document, it would just print a single dot. So the mapping should be somewhere in Ndless itself, and that's what I'm concerned about.

**Comment by Legimet** [comment]
That program is linked with the [Nspire I/O](https://github.com/Vogtinator/nspire-io) library (see the --nspireio flag in the Makefile, I don't know where it's documented, but it causes the program to redirect std* streams to an nspireio console). You can look into the source code of nspireio, specifically https://github.com/Vogtinator/nspire-io/blob/history/arch-nspire/nspire.c.

**Comment by Irides-Chromium** [comment]
I looked in to the Nspire IO library, and I found the part I want. Thanks very much for your patience and answers!
