### ISSUE TITLE
‘scm_new_port_table_entry’ was not declared in this scope

### ISSUE THREAD

**Issue by FrostyPenguin** [ndless-nspire/Ndless#72]
When I try to compile Ndless SDK on ArchLinux (GNU+Linux) using "build_toolchain.sh" the compiler exits returning the following error message:
```
../../gdb-7.12.1/gdb/guile/scm-ports.c: In function ‘scm_unused_struct* ioscm_open_port(scm_t_bits, long int)’:
../../gdb-7.12.1/gdb/guile/scm-ports.c:139:10: error: ‘scm_new_port_table_entry’ was not declared in this scope
   port = scm_new_port_table_entry (port_type);
          ^~~~~~~~~~~~~~~~~~~~~~~~
```
Installed programs:

- git 2.13.1
- gcc (GCC) 7.1.1 20170516(& g++)
- binutils 2.28.0-3
- gmp 6.1.2-1
- mpfr 3.1.5.p2-1
- libmpc 1.0.3-2
- zlib 1:1.2.11-1
- boost 1.64.0-1
- wget 1.19.1-2

**Comment by Legimet** [comment]
It has something to do with the guile version, I think because Arch has too new of a version of guile.
https://github.com/riscv/riscv-binutils-gdb/issues/82
https://github.com/riscv/riscv-gnu-toolchain/issues/244

You can try adding `--with-guile=no` to `OPTIONS_GDB` in the script to disable guile.

**Comment by Vogtinator** [comment]
You can also try to bump the GDB version to 8.0.

**Comment by FrostyPenguin** [comment]
@Vogtinator I tried using gdb-8.0 and building failed with almost the same error message:
```
../../gdb-8.0/gdb/guile/scm-ports.c: In function ‘scm_unused_struct* ioscm_open_port(scm_t_bits, long int)’:
../../gdb-8.0/gdb/guile/scm-ports.c:146:10: error: ‘scm_new_port_table_entry’ was not declared in this scope
   port = scm_new_port_table_entry (port_type);
          ^~~~~~~~~~~~~~~~~~~~~~~~
```
@Legimet compiling with "--with-guile=no" worked. The only thing that worries me is whether I disabled some (important) features by doing so 😅

**Comment by Legimet** [comment]
It's not a big deal, unless you really wanted to use guile scripting in gdb.

**Comment by FrostyPenguin** [comment]
OK, thank you for your quick support! :smile:
If nobody else wants to add something I'm going to close this issue now.

**Comment by The-Compiler** [comment]
I just ran into the same - what do you think about adding `--with-guile=no` to the default `OPTIONS_GDB` so this works out of the box (assuming nobody wants to use guile scripting, that is)?

**Comment by FrostyPenguin** [comment]
If we do so, I'd recommend adding a warning to [Hackspire](https://hackspire.org/index.php/C_and_assembly_development_introduction) and [GitHub Wiki](https://github.com/ndless-nspire/Ndless/wiki/Ndless-SDK:-C-and-assembly-development-introduction) in case someone wants to use guile scripts.
