### ISSUE TITLE
arm-none-eabi-g++: Command not found in Cygwin, Other errors in realpath,strlcpy

### ISSUE THREAD

**Issue by Kunait** [ndless-nspire/Ndless#75]
I get this error when I "make"(Ndless folder) in cygwin even though I followed every step on the github tutorial. I first tried all steps for the windows Subsystem for Ubuntu but I just got stuck there and couldnt finish the make command because there were several errors with the realpath,strlcpy, etc. functions.
I really want to start developing but i can't because i cant compile the sdk :(

**Comment by Vogtinator** [comment]
Did you build the toolchain correctly and adjust the PATH variable?

**Comment by CuneytTas** [comment]
Yeah I did and I even reinstalled Cygwin and tried everything from step one again but it still doesnt work.

Atleast u replied really fast :D

**Comment by CuneytTas** [comment]
Maybe I did something wrong, but I dont see what

**Comment by Vogtinator** [comment]
What's your $PATH? Does ndless-sdk/toolchain/install/bin contain arm-none-eabi-g++?

**Comment by CuneytTas** [comment]
Nope it doesn't, but why doesn't it?

**Comment by Vogtinator** [comment]
Because build_toolchain.sh failed for some reason. Please post its full output somewhere.

**Comment by CuneytTas** [comment]
I'll try it again and post the result

**Comment by CuneytTas** [comment]
https://pastebin.com/iLnM6Epv
This is the paste bin
But i copied everything the shell said so its 3000 lines...
When i do echo $? it outputs 1

**Comment by Vogtinator** [comment]
```../../../gcc-7.1.0/libcpp/include/cpplib.h:286:3: Fehler: #error "Cannot find a least-32-bit signed integer type"```

this is the reason it doesn't build... You can try to replace "gcc-7.1.0" with "gcc-7.0.0" in build_toolchain.sh, ```rm .downloaded``` and try again. I'm not sure why Cygwin's GCC does not want to build GCC 7.1.

**Comment by CuneytTas** [comment]
Ok I'll try that

**Comment by CuneytTas** [comment]
Now this:
binutils-2.28/zlib/zutil.c
binutils-2.28/zlib/zutil.h
--2017-07-26 21:19:09--  ftp://ftp.gnu.org/gnu/gcc/gcc-7.0.0/gcc-7.0.0.tar.bz2
           => »download/gcc-7.0.0.tar.bz2«
Auflösen des Hostnamens ftp.gnu.org… 2001:4830:134:3::b, 208.118.235.20
Verbindungsaufbau zu ftp.gnu.org|2001:4830:134:3::b|:21 … verbunden.
Anmelden als anonymous … Angemeldet!
==> SYST ... fertig.    ==> PWD ... fertig.
==> TYPE I ... fertig.  ==> CWD (1) /gnu/gcc/gcc-7.0.0 ...
Das Verzeichnis »gnu/gcc/gcc-7.0.0« existiert nicht.

**Comment by Vogtinator** [comment]
Right, the weird GCC versioning scheme... You can try ```6.4.0``` or ```6.3.0``` instead.

**Comment by CuneytTas** [comment]
Okay I'll try that

**Comment by CuneytTas** [comment]
So im again building the toolchain but it still goes on for 41 min when i wrote my last message and I see how several parts are just repeating and repeating and no end is in sight...

**Comment by Vogtinator** [comment]
Yes, building can take a bit, depending on the speed of your CPU, RAM and disk, between 20 minutes and four hours.

**Comment by CuneytTas** [comment]
So that is normal? Ok then, but please dont go offline yet:D
I might need you :(

**Comment by CuneytTas** [comment]
Just joking :)

**Comment by CuneytTas** [comment]
Got a BSOD....

**Comment by CuneytTas** [comment]
Does it do everythign from beginning or does it pick up from the last place?

**Comment by CuneytTas** [comment]
@Vogtinator Thank you so much, the only error I got was to install Texinfo but after that everything worked flawlessly! Thank you sooooo much <3

**Comment by Legimet** [comment]
What asked you to install texinfo?

**Comment by CuneytTas** [comment]
I dont really know but it prompted me to install at the end of build_toolchain.sh and when I installed it and restarted it everything worked

_Sent from my ZTE Blade L5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
