### ISSUE TITLE
Error when running build_toolchain.sh

### ISSUE THREAD

**Issue by Winter-of-Cirno** [ndless-nspire/Ndless#76]
I ran build_toolchain.sh but it stopped here...
Any suggestions would help  :)

Building and installing to '/home/pc/Ndless/ndless-sdk/toolchain/install'...
Building Binutils...
Building GCC (step 1)...
Building Newlib...
Building GCC (step 2)...
Building GDB...
/home/pc/Ndless/ndless-sdk/toolchain/gdb-7.12.1/missing makeinfo --split-size=5000000 --split-size=5000000   -I ../../../gdb-7.12.1/gdb/doc/../../readline/doc -I ../../../gdb-7.12.1/gdb/doc/../mi -I ../../../gdb-7.12.1/gdb/doc \
	-o gdb.info ../../../gdb-7.12.1/gdb/doc/gdb.texinfo
Makefile:488: recipe for target 'gdb.info' failed
make[5]: Leaving directory '/home/pc/Ndless/ndless-sdk/toolchain/build/gdb/doc'
Makefile:1504: recipe for target 'subdir_do' failed
make[4]: Leaving directory '/home/pc/Ndless/ndless-sdk/toolchain/build/gdb'
Makefile:1238: recipe for target 'install-only' failed
make[3]: Leaving directory '/home/pc/Ndless/ndless-sdk/toolchain/build/gdb'
Makefile:1235: recipe for target 'install' failed
make[2]: Leaving directory '/home/pc/Ndless/ndless-sdk/toolchain/build/gdb'
Makefile:9189: recipe for target 'install-gdb' failed
make[1]: Leaving directory '/home/pc/Ndless/ndless-sdk/toolchain/build'
Makefile:2252: recipe for target 'install' failed

**Comment by Vogtinator** [comment]
> missing makeinfo

So install makeinfo and try again.

If you don't need gdb you can also just ignore the error, as the rest was built successfully already.

**Comment by Winter-of-Cirno** [comment]
Thanks!It works now after installing makeinfo.
