### ISSUE TITLE
Is it safe to use it?

### ISSUE THREAD

**Issue by DesWurstes** [ndless-nspire/Ndless#78]
Does it alter the kernel? Does it alter the OS?

**Comment by Vogtinator** [comment]
Yes to all three questions! After a reboot every change is gone until to install it again.

**Comment by DesWurstes** [comment]
@Vogtinator May I suggest you a simple app idea? https://www.omnimaga.org/general-calculator-help/shutdown-the-nspire-completely/msg337159/#msg337159
I don't understand why no one implemented such a simple app.

**Comment by Vogtinator** [comment]
Nobody so far investigated deep enough to find the OS's shutdown routines and reimplement them.
I guess it wouldn't be too hard, but still a fair amount of work.
