### ISSUE TITLE
Particles render issue

### ISSUE THREAD

**Issue by DesWurstes** [ndless-nspire/Ndless#79]
Video: https://drive.google.com/open?id=0B4tqQioIpV0ySFhWQXk3WVhodzA

**Comment by Vogtinator** [comment]
The particles demo is largely unmodified from its original version from several years ago and does not support newer hardware. The compatibility mode does not support the display mode it needs yet. This shouldn't be an issue for anything besides that demo though.

**Comment by DesWurstes** [comment]
> This shouldn't be an issue for anything besides that demo though.

Yes.
