### ISSUE TITLE
4.5 installer hangs/crashes

### ISSUE THREAD

**Issue by The-Compiler** [ndless-nspire/Ndless#80]
When running the 4.5 installer on a 4.5.0.1180 OS, I just get a spinning clock icon, then get thrown back into the home screen after a few seconds. Is that intended? Also, once out of 3 times I tried I got a complete hang. Any way I can help with debugging this?

**Comment by Vogtinator** [comment]
> When running the 4.5 installer on a 4.5.0.1180 OS, I just get a spinning clock icon, then get thrown back into the home screen after a few seconds. Is that intended?

Yes, you should see the "Ndless installed!" message in the top left. If not, make sure that ndless_resources.tns is in the correct location.

**Comment by The-Compiler** [comment]
Okay - What about the hang/freeze I got once though? I guess there's no way I can get some useful information now, after the fact? Is there a way I could do something useful to help debug this if I'm able to reproduce it?

**Comment by Vogtinator** [comment]
The way the installer works relies heavily on the pseudo-random placement of structures in memory, so it is highly dependant of whatever you did before opening the installer. It most likely won't work if you have a big document in the scratchpad opened, for instance.
If you can reproduce it reliably, it might be possible to find a workaround for the issue.

**Comment by The-Compiler** [comment]
Just running the installer twice in a row without doing anything in between (or before) seems to reliably trigger a reboot, FWIW. I think when I saw the freeze it also was when I ran the installer again despite ndless being already installed.

**Comment by Vogtinator** [comment]
Yes, that is known and sadly unavoidable - after installation, ndless_resources stays in memory, so any newly allocated structures in memory are offset by the size of the resources. This causes the installer to be loaded at a different address in memory, which is enough to cause a crash.

**Comment by The-Compiler** [comment]
Okay, thanks for the explanation! Closing this then.
