### ISSUE TITLE
Undocumented PHP Dependency

### ISSUE THREAD

**Issue by hexane360** [ndless-nspire/Ndless#81]
Compiling/building 'libsyscalls' requires PHP to be installed. However, this dependency isn't listed in the installation guide: https://github.com/ndless-nspire/Ndless/wiki/Ndless-SDK:-C-and-assembly-development-introduction#On_Linux_distros

**Comment by Vogtinator** [comment]
I'll actually fix that a different way, by removing stubs.cpp from the .gitignore. That way php won't be necessary anymore. The Makefile should take care of keeping it up-to-date, so nothing should break.

**Comment by hexane360** [comment]
We should also probably remove stubs.cpp from the 'clean' recipe then, if it's not created by a normal build.
