### ISSUE TITLE
Cant download Ndless 4.5

### ISSUE THREAD

**Issue by ueberBrot** [ndless-nspire/Ndless#85]
Hey,

maybe its just a issue for me but i cant download it.  The download starts and crashes because of a timeout. Tried it from my home wifi, from my university wifi and from my phone.

Can anyone help me ?

**Comment by adriweb** [comment]
Are you talking about this link? https://github.com/ndless-nspire/Ndless/releases/download/v4.5/ndless.zip
Because it's working fine for me (and lots of other people)

**Comment by ueberBrot** [comment]
Yes thats the one. I cant download it. Same goes for the nPDF downloadlink https://github.com/Legimet/nPDF/releases/download/v0.4b/nPDF-0.4b.zip and i need both. I can download programms and other files from any other given site. 

I dont understand why its working for you but not for me
