### ISSUE TITLE
Makefile error when compiling sdk

### ISSUE THREAD

**Issue by TheWithz** [ndless-nspire/Ndless#86]
I'm opening a separate issue because the error message is different. 

> /home/thewithz/lib/Ndless/ndless-sdk/bin/../system/crt0.o: In function `_start':
(.text+0x1c): undefined reference to `main'
collect2: error: ld returned 1 exit status
make[3]: *** [builds/freetype.mk:207: objs/ftsystem.o] Error 1
make[3]: Leaving directory '/home/thewithz/lib/Ndless/ndless-sdk/thirdparty/freetype2'
make[2]: *** [Makefile:43: freetype] Error 2
make[2]: Leaving directory '/home/thewithz/lib/Ndless/ndless-sdk/thirdparty'
make[1]: *** [Makefile:14: build-thirdparty] Error 2
make[1]: Leaving directory '/home/thewithz/lib/Ndless/ndless-sdk'
make: *** [Makefile:19: build-ndless-sdk] Error 2

OS: Solus3

**Comment by Legimet** [comment]
Can you post the full log?

**Comment by TheWithz** [comment]
https://hastebin.com/vayemalefi.go

**Comment by TheWithz** [comment]
Hopefully this can provide some more incite, When i run `make` on the sample `helloworld-sdl` I recieve this error 
>genzehn --input ./helloworld-sdl.elf --output ./helloworld-sdl.tns --name "helloworld-sdl"
/bin/sh: genzehn: command not found
make: *** [Makefile:43: helloworld-sdl.tns] Error 127

I didn't recognize that command from the dependencies list so I assume the initial make on the root was supposed to create it?

**Comment by Vogtinator** [comment]
> nspire-gcc -O2 -Wall -Wextra -DFT_CONFIG_OPTION_SYSTEM_ZLIB -I./objs -I./builds/ansi -I./include  -g2 -O3 -pipe -fPIC -Wformat -Wformat-security -fno-omit-frame-pointer -fexceptions -D_FORTIFY_SOURCE=2 -fstack-protector --param ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT -DFT2_BUILD_LIBRARY -DFT_CONFIG_MODULES_H="<ftmodule.h>"  -o objs/ftsystem.o src/base/ftsystem.c

Looks very much like the ```-c``` parameter is missing. Any idea, @Legimet ?

> I didn't recognize that command from the dependencies list so I assume the initial make on the root was supposed to create it?

Yes. The source is in ndless-sdk/tools/genzehn and the binary gets placed into ndless-sdk/bin.

**Comment by TheWithz** [comment]
I went into `ndless-sdk/tools/genzehn` and compiled it manually. I can now compile the sample correctly. However, running `make` in the root still fails with the same error as posted above.

**Comment by Vogtinator** [comment]
Yes, it fails during the freetype build. Generally everything that doesn't rely on freetype being present (Only nPDF so far?) should work fine.

**Comment by Legimet** [comment]
It looks like you have CFLAGS set, so try unsetting it. Are you using Solus?

**Comment by TheWithz** [comment]
Sorry for the late reply, I've been in classes all day. Yes, I am using the Solus Project. the latest release of Solus3. Do you mean the Environment variable CFLAGS? I'll try unsetting it like you say, though I don't remember ever setting it's value.

**Comment by TheWithz** [comment]
running `unset CFLAGS` then running `make` ran into a `command not found: php` error. After running `eopkg install php` I reran `make` and it worked without error. Thanks for your help!
