### ISSUE TITLE
SDK fails to compile on Windows Subsystem for linux

### ISSUE THREAD

**Issue by deadmeatpt** [ndless-nspire/Ndless#90]
Hello, not sure if this is because the subsystem is still in beta and works badly, but when I built the toolchain, no errors were presented. When I try to go to the compile SDK part, I get this error:

make -C ndless-sdk
make[1]: Entering directory '/home/nuno/Ndless/ndless-sdk'
make -C libsyscalls
make[2]: Entering directory '/home/nuno/Ndless/ndless-sdk/libsyscalls'
arm-none-eabi-g++ -mcpu=arm926ej-s -std=c++11 -nostdlib -O3 -fPIE -fno-exceptions -fno-rtti -mlong-calls -Wall -Werror -I ../include/ -I ../thirdparty/nspire-io/include/ -D_TINSPIRE -ffunction-sections -fdata-sections -c stubs.cpp -o stubs.o
make[2]: arm-none-eabi-g++: Command not found
Makefile:18: recipe for target 'stubs.o' failed
make[2]: *** [stubs.o] Error 127
make[2]: Leaving directory '/home/nuno/Ndless/ndless-sdk/libsyscalls'
Makefile:14: recipe for target 'build-libsyscalls' failed
make[1]: *** [build-libsyscalls] Error 2
make[1]: Leaving directory '/home/nuno/Ndless/ndless-sdk'
Makefile:19: recipe for target 'build-ndless-sdk' failed
make: *** [build-ndless-sdk] Error 2

In older SDK releases I would get an ending message like "Done: don't forget to add ndless/bin/something to PATH", but in this one I only get this:

checking for working strncmp... yes
checking for working strncmp... yes
yes
configure: updating cache ./config.cache
configure: updating cache ./config.cache
configure: creating ./config.status
configure: creating ./config.status
config.status: creating Makefile
config.status: creating Makefile
config.status: creating testsuite/Makefile
config.status: creating testsuite/Makefile
config.status: creating config.h
config.status: creating config.h
config.status: executing default commands
config.status: executing default commands
nuno@nuno-Laptop:~/Ndless/ndless-sdk/toolchain$ cd ..

Not quite sure if my system is not working okay, or if the SDK is still not 100% supported in Windows Subsystem for Linux. Help would be appreciated. 
I would like to add have ndless sdk in my PATH set in ~/.profile, not sure if that place also works.

**Comment by Vogtinator** [comment]
After running ```build_toolchain.sh```, what's the exit status? (```echo $?```)

**Comment by deadmeatpt** [comment]
like this?
nuno@nuno-Laptop:~/Ndless/ndless-sdk/toolchain$ echo $?
0

returns 0

**Comment by Vogtinator** [comment]
That is strange, what's the output of ```ls -la```?

**Comment by deadmeatpt** [comment]
nuno@nuno-Laptop:~/Ndless/ndless-sdk/toolchain$ ls -la
total 8
drwxrwxrwx 0 nuno nuno  512 Oct 22 12:15 .
drwxrwxrwx 0 nuno nuno  512 Oct 22 11:54 ..
drwxrwxrwx 0 nuno nuno  512 Oct 22 11:58 binutils-2.28
drwxrwxrwx 0 nuno nuno  512 Oct 22 12:15 build
-rwxrwxrwx 1 nuno nuno 5707 Oct 22 11:54 build_toolchain.sh
-rw-rw-rw- 1 nuno nuno    0 Oct 22 12:15 .built_binutils
drwxrwxrwx 0 nuno nuno  512 Oct 22 12:10 download
-rw-rw-rw- 1 nuno nuno    0 Oct 22 12:12 .downloaded
drwxr-xr-x 0 nuno nuno  512 Aug 14 09:37 gcc-7.2.0
drwxrwxrwx 0 nuno nuno  512 Oct 22 12:12 gdb-8.0
-rw-rw-rw- 1 nuno nuno   91 Oct 22 11:54 .gitignore
drwxrwxrwx 0 nuno nuno  512 Oct 22 12:15 install
drwxr-xr-x 0 nuno nuno  512 Mar 29  2016 newlib-2.4.0

**Comment by Vogtinator** [comment]
Ok, that means gcc (part 1) isn't built successfully. Can you upload the full output of ```./build_toolchain.sh``` somewhere?

**Comment by deadmeatpt** [comment]
Here it is: [](https://pastebin.com/H1bmJFGS)

**Comment by deadmeatpt** [comment]
Here it is: [https://pastebin.com/H1bmJFGS](https://pastebin.com/H1bmJFGS)

**Comment by Vogtinator** [comment]
```
checking whether abort is declared... configure: error: C++ compiler missing or inoperational
```

-> check config.log

**Comment by deadmeatpt** [comment]
Thanks Vogtinator, I installed g++, it wasn't installed and gcc is compiling now. Let's see. I will post an update to see if it did fine, but looks like it :)

**Comment by deadmeatpt** [comment]
Worked fine, just needed to install texinfo. Thanks Vogtinator, you can close this thread.

**Comment by Legimet** [comment]
By the way, the texinfo requirement is a bug in GDB.

**Comment by deadmeatpt** [comment]
@Legimet Really? that's interesting. It works after installing texinfo, but it's related to makeinfo command from texinfo.

@Vogtinator it was this message:

make[1]: Nothing to be done for 'install-target'.
make[1]: Leaving directory '/home/nuno/Ndless/ndless-sdk/toolchain/build'
Done!
Don't forget to add '/home/nuno/Ndless/ndless-sdk/toolchain/install/bin' to your $PATH along with /home/nuno/Ndless/ndless-sdk/toolchain/../bin.
nuno@nuno-Laptop:~/Ndless/ndless-sdk/toolchain$
