### ISSUE TITLE
Compile GMP as static library for TI-Nspire programs

### ISSUE THREAD

**Issue by FrostyPenguin** [ndless-nspire/Ndless#91]
I'm currently writing a program that signs files on a calculator using RSA and SHA1.
For these algorithms I need to calculate huge (**really** huge) numbers and test their primality.
Therefore, I want to compile GNU MP as a static library for TI-Nspire.    
1. Is there a way to do this without rewriting (parts of) GMP? Some parts of it seam to be written in ASM.
2. Are there other ways to make these calculations without having to reinvent the wheel?

I'm looking forward to hearing from you,
~ FrostyPenguin

**Comment by Vogtinator** [comment]
Building GMP should be straightforward, just the usual ```./configure --host=arm-none-eabi --prefix=$(nspire-tools path)/toolchain/install && make && make install```

**Comment by FrostyPenguin** [comment]
Configuring GMP with the given command or even with `./configure --host=arm-none-eabi --prefix=$(nspire-tools path)/toolchain/install --disable-shared` crashes with the following warnings / error messages:
```
checking if globals are prefixed by underscore... /home/FrostyPenguin/.local/src/Ndless/ndless-sdk/toolchain/install/bin/arm-none-eabi-nm: conftest.o: File format not recognized
unknown
configure: WARNING: +----------------------------------------------------------
configure: WARNING: | Cannot determine global symbol prefix.
configure: WARNING: | /home/FrostyPenguin/.local/src/Ndless/ndless-sdk/toolchain/install/bin/arm-none-eabi-nm -B output doesn't contain a global data symbol.
configure: WARNING: | Will proceed with no underscore.
configure: WARNING: | If this is wrong then you'll get link errors referring
configure: WARNING: | to ___gmpn_add_n (note three underscores).
configure: WARNING: | In this case do a fresh build with an override,
configure: WARNING: |     ./configure gmp_cv_asm_underscore=yes
configure: WARNING: +----------------------------------------------------------
checking how to switch to read-only data section... 	.section	.rodata
checking for assembler .type directive... .type	$1,@$2
checking for assembler .size directive... .size	$1,$2
checking for assembler local label prefix... configure: WARNING: "/home/FrostyPenguin/.local/src/Ndless/ndless-sdk/toolchain/install/bin/arm-none-eabi-nm -B" failure
configure: WARNING: cannot determine local label, using default L
L
checking for assembler byte directive... .byte
checking how to define a 32-bit word... /home/FrostyPenguin/.local/src/Ndless/ndless-sdk/toolchain/install/bin/arm-none-eabi-nm: conftest.o: File format not recognized
/home/FrostyPenguin/.local/src/Ndless/ndless-sdk/toolchain/install/bin/arm-none-eabi-nm: conftest.o: File format not recognized
configure: error: cannot determine how to define a 32-bit word
```

**Comment by Vogtinator** [comment]
No, you need to pass the correct flags for ./configure to enable cross-compiling.

**Comment by FrostyPenguin** [comment]
> you need to pass the correct flags for ./configure to enable cross-compiling.
I've passed --host and --build to GMP's configure script. What am I missing?

**Comment by Vogtinator** [comment]
How did you invoke configure exactly?

**Comment by FrostyPenguin** [comment]
`./configure --host=arm-none-eabi --build=sandybridge-linux-gnu --prefix=$(nspire-tools path)/toolchain/install && make && make install`

**Comment by Vogtinator** [comment]
Can you upload config.log?

**Comment by FrostyPenguin** [comment]
[config.log](https://github.com/ndless-nspire/Ndless/files/1441190/config.log)

**Comment by Vogtinator** [comment]
That's a different run, it succeeded and was not cross-compiling.

**Comment by FrostyPenguin** [comment]
Oh... then this is the log of my first build... 😇

[Here](https://github.com/ndless-nspire/Ndless/files/1441211/config.log) is a new one

**Comment by Vogtinator** [comment]
Apparently a known issue, ```NM=nm``` should work as a workaround: https://gmplib.org/list-archives/gmp-bugs/2012-January/002511.html

**Comment by FrostyPenguin** [comment]
Great, this specific problem is fixed!
However, now I'm getting this error message:
```
checking size of mp_limb_t... 8
configure: error: Oops, mp_limb_t is 64 bits, but the assembler code
in this configuration expects 32 bits.
./configure --host=arm-none-eabi --build=sandybridge-linux-gnu  NM=nm  7.00s user 2.33s system 100% cpu 9.285 total
```

~~~
Attachments: 
[config.log](https://github.com/ndless-nspire/Ndless/files/1441269/config.log)

**Comment by Vogtinator** [comment]
For some reason it builds conftest with the wrong gcc. No idea there off the top of my head.

**Comment by FrostyPenguin** [comment]
I tried to run `./configure --host=arm-none-eabi --build=sandybridge-linux-gnu --prefix=$(nspire-tools path)/toolchain/install NM=nm CC=arm-none-eabi-gcc`

But it crashed with:

```
checking whether arm-none-eabi-gcc is gcc... yes
checking compiler arm-none-eabi-gcc -O2 -pedantic -fomit-frame-pointer ... no
configure: error: could not find a working compiler, see config.log for details
```

In config.log it says:
```
configure:5858: checking compiler arm-none-eabi-gcc -O2 -pedantic -fomit-frame-pointer 
Test compile: 
configure:5872: arm-none-eabi-gcc -O2 -pedantic -fomit-frame-pointer  conftest.c >&5
/home/FrostyPenguin/.local/src/Ndless/ndless-sdk/toolchain/install/lib/gcc/arm-none-eabi/7.2.0/../../../../arm-none-eabi/lib/libc.a(lib_a-exit.o): In function `exit':
exit.c:(.text.exit+0x2c): undefined reference to `_exit'
collect2: error: ld returned 1 exit status
configure:5875: $? = 1
failed program was:

int main () { return 0; }
configure:6962: result: no
configure:7200: error: could not find a working compiler, see config.log for details
```

Does that mean it's a compiler problem (arm-none-eabi-gcc)?

Attachments:

[config.log](https://github.com/ndless-nspire/Ndless/files/1442309/config.log)

**Comment by Legimet** [comment]
Try using CC=nspire-gcc

**Comment by FrostyPenguin** [comment]
The same. 😞

`checking compiler nspire-gcc -O2 -pedantic -fomit-frame-pointer ... no`

[config.log](https://github.com/ndless-nspire/Ndless/files/1442314/config.log)

**Comment by FrostyPenguin** [comment]
Interestingly, after I rebuilt my Ndless-SDK linking programs didn't not work any longer:
I created a new folder and executed the following commands:
```sh
$ nspire-tools main

$ nspire-tools new nspire-gcc-test

$ ls -l
total 8
-rw-r--r-- 1 FrostyPenguin FrostyPenguin  79 Nov  4 15:10 main.c
-rw-r--r-- 1 FrostyPenguin FrostyPenguin 901 Nov  4 15:10 Makefile

$ make all
nspire-gcc -Wall -W -marm -Os -c main.c -o main.o
mkdir -p .
nspire-ld main.o -o nspire-gcc-test.elf 
arm-none-eabi-ld: cannot find -lnspireio
arm-none-eabi-ld: cannot find -lndls
arm-none-eabi-ld: cannot find -lsyscalls
collect2: error: ld returned 1 exit status
make: *** [Makefile:40: nspire-gcc-test.elf] Error 1
```

**Comment by Vogtinator** [comment]
This means you somehow deleted the libraries in ndless-sdk/lib

**Comment by FrostyPenguin** [comment]
Oops!
#MyFault
I forgot to run `make` in the top-level directory of Ndless after reinstalling the IDE.
After running 
`~/.local/src/gmp-6.1.2/configure --prefix=/home/FrostyPenguin/.ndless --host=arm-none-eabi --disable-shared NM=nm CC=nspire-gcc` everything configured and compiled / installed successfully.
I feel somewhat dumb for wasting your time so much :sweat:
However, thank you for your incredibly fast and patient support! 👍

PS
@Vogtinator, I installed the library to `~/.ndless` and not to `$(nspire-tools path)/toolchain/install` because [hackspire recommended doing so](https://hackspire.org/index.php/Ndless_features_and_limitations#Using_static_libraries).

// Closing this as my problem is fixed.
