### ISSUE TITLE
Problem with make

### ISSUE THREAD

**Issue by ozzietheostrich** [ndless-nspire/Ndless#92]
I have followed the guide on https://github.com/ndless-nspire/Ndless/wiki/Ndless-SDK:-C-and-assembly-development-introduction and I have Mac OS Sierra High Public Beta 1 (is that important?) Everything else has been going smoothly until I have put in `Make` in Terminal. Everything seems fine until a few errors so I'll put in the end part but I'll update it to the whole thing if asked.

`/Applications/Xcode.app/Contents/Developer/usr/bin/make -C installer-4.5
nspire-as -Os -Wall -Wextra -nostdlib -fPIE -DSTAGE1 -D NDLESS_450 -c stage0.S -o stage0.o
nspire-g++ -Os -Wall -Wextra -nostdlib -fPIE -DSTAGE1 -D NDLESS_450 -std=c++11 -fno-exceptions -fno-rtti -c stage1.cpp -o stage1.o
nspire-gcc -Os -Wall -Wextra -nostdlib -fPIE -DSTAGE1 -D NDLESS_450 -c utils.c -o utils.o
"/Users/austin.schaap/Ndless/ndless-sdk/toolchain/install/bin/arm-none-eabi-ld" -nostdlib -Tldscript stage0.o stage1.o utils.o -o ndless_installer.elf
"/Users/austin.schaap/Ndless/ndless-sdk/toolchain/install/bin/arm-none-eabi-objcopy" -O binary ndless_installer.elf ndless_installer.bin
(../tools/MakeChunkDispatch/MakeChunkDispatch 0x1800e7f4 0x12480000; cat ndless_installer.bin) | base64 -w0 > payload || rm payload
base64: invalid option -- w
Usage:	base64 [-hvD] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -D, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
cat Problem1_top.xml Problem1_mid.xml payload Problem1_bot.xml > Problem1.xml
cat: payload: No such file or directory
make[3]: *** [Problem1.xml] Error 1
make[2]: *** [build-installer-4.5] Error 2
make[1]: *** [build-src] Error 2
make: *** [build-ndless] Error 2`

**Comment by ozzietheostrich** [comment]
Okay, so I skipped this step and went straight to typing `nspire-gcc` and it did it with no problems that I could see. I have made my first C++ program and typing `make` made the file perfectly so is there a problem I'm not noticing that could possibly blow up my calculator or install things that make the FBI knock on my door?

**Comment by Vogtinator** [comment]
See https://github.com/ndless-nspire/Ndless/issues/88#issuecomment-336932044 for a workaround.

**Comment by ozzietheostrich** [comment]
@Vogtinator I can't find any reference to base64. I do have another problem as well, which is that when I try to open my .tns file that I have made using `cd "/Users/austin.schaap/Ndless/ndless-sdk/samples/MyFirstProgram"` and then `nspire-tools new MyFirstProgram` and I have placed a .cpp file in there, it makes the .tns file but when I try to open it on my calculator, it doesn't do anything.

**Comment by Vogtinator** [comment]
What does your code do?

**Comment by ozzietheostrich** [comment]
It's just a simple hello world program (not a good one though) to check if I can do C++ on my calculator.
`#include <iostream>

using namespace std;

int main()
{
    cout << "Hello world!" << endl;
    return 0;
}
`

**Comment by Vogtinator** [comment]
That is going to write to the serial connection at the bottom of the calc, you won't see anything on screen.
Also, it's going to exit immediately after writing that, so you won't even notice that it did anything.

**Comment by ozzietheostrich** [comment]
Is there a way to make it a visible program? As in one you can see it say Hello World or maybe later on one that's interactive as in one that prints a user's name?

**Comment by Vogtinator** [comment]
Yes, set ```LDFLAGS = -Wl,--nspireio``` in the Makefile, just like ```samples/helloworld-cpp```

**Comment by ozzietheostrich** [comment]
That worked but is there a way of making it stay on the screen?

**Comment by Legimet** [comment]
wait_key_pressed() from libndls.h

**Comment by ozzietheostrich** [comment]
Will I have to add the header library to the calculator or is it already installed on there?

**Comment by Legimet** [comment]
It's a static library, will be included in the executable. All you need to do 
is #include <libndls.h> in your source.

**Comment by ozzietheostrich** [comment]
Thank you so much! It worked! I have another question now though. Is it possible to code on the calculator and test it on the calculator without using the computer?

**Comment by Legimet** [comment]
In what language?

**Comment by ozzietheostrich** [comment]
C++

**Comment by Legimet** [comment]
Not unless you can find a fast, tiny C++ compiler and port it to the Nspire.

**Comment by ozzietheostrich** [comment]
Okay, thank you for your help.
