### ISSUE TITLE
Update NDless-SDK Docker images

### ISSUE THREAD

**Issue by FrostyPenguin** [ndless-nspire/Ndless#93]
Ndless' Docker images were last updated 2 years ago.
Therefore, my CI which pulls ndless-sdk directly from docker hub crashed with the error message:
```
genzehn --input MyProject.elf --output MyProject.tns.zehn --name "MyProject" --uses-lcd-blit yes
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >'
  what():  unrecognised option '--uses-lcd-blit'
Aborted (core dumped)
make: *** [MyProject.tns] Error 134
```
I'd kindly ask someone who's got access to the `ndless` Docker-Hub account to push a fresh build.

**Comment by Vogtinator** [comment]
I have no idea how that all is supposed to work together (I don't use docker) and the parts are probably all broken by now. I don't have access to push new images anyway (at least I think so) so this is unlikely to happen for now.

**Comment by FrostyPenguin** [comment]
@Vogtinator I'll try to rebuild `ndless-sdk` and `ndless-gcc` and push them to my (private) GitLab Registry.
It's just a huge bunch of work every time you guys update the SDK 😆.

**Comment by Vogtinator** [comment]
@OlivierA Ok, I created an account "vogtinator" (it does not like capital letters for some reason...)

@FrostyPenguin SDK updates shouldn't be too bad - only toolchain updates require a rather time-consuming rebuild. Luckily those aren't really mandatory.

**Comment by OlivierA** [comment]
@Vogtinator Done!

**Comment by FrostyPenguin** [comment]
I had to [change Docker.arm-gcc a bit](https://github.com/FrostyPenguin/Ndless/commit/157604f36965bb9201ea0072c23a01c41d38eb38). Now the docker-images are compiling, but a new problem occurred when trying to compile Ndless-programs from inside the docker image (as my CI does):
genzehn crashes with the following error message:
```
nspire-gcc -Wall -W -marm -Os -c main.c -o main.o
mkdir -p .
nspire-ld main.o -o test.elf 
genzehn --input test.elf --output test.tns.zehn --name "test"
genzehn: error while loading shared libraries: libboost_program_options.so.1.65.1: cannot open shared object file: No such file or directory
make: *** [test.tns] Error 127
```
I compiled ndless with boost 1.65.1 on my Arch Linux (the Ubuntu docker image serves 1.54.0). However, this shouldn't be a problem because I suggest toolchain and SDK are compiled in the Docker image.

**Comment by FrostyPenguin** [comment]
After looking into this a second time (after some years :watch:) I noticed that the Dockerfile indeed does not call `make clean` and/or `make` at any time. I will try to open a merge request in the next days that fixes the Dockerfile completely. However, this might take some time as I'm really busy these days, and for some reason my connection to `sourceware.org` takes ages to download newlib...
