### ISSUE TITLE
Warranty

### ISSUE THREAD

**Issue by phyllocrania** [ndless-nspire/Ndless#99]
Does ndless void my warranty?

TI nspire CX revision AB os 4.5

**Comment by Vogtinator** [comment]
No, as you can always uninstall it.

**Comment by phyllocrania** [comment]
That's great

**Comment by phyllocrania** [comment]
I am wondering if there is any danger of bricking or gears on startup (or any other booting issues, stuck on clock screen included)

**Comment by Vogtinator** [comment]
If you don't do any dangerous things like playing with the boot process or the hardware directly, not really.

**Comment by phyllocrania** [comment]
One last question, would it remove any existing OS features or make it incompatible with certain tests?

**Comment by Vogtinator** [comment]
Don't install ndless in tests, it can be considered cheating.

**Comment by phyllocrania** [comment]
Okay, If I have it installed and a test is coming up, should I uninstall it??
